# **Downloading The Data and Converting to Dataframe**

## *Downloading the Data*

In [1]:
import requests
from pathlib import Path

save_folder = Path("data/tennis_atp")
save_folder.mkdir(exist_ok = True)

for year in range(1991,2027):
    file_types = ["atp_matches", "atp_matches_futures", "atp_matches_qual_chall"]

    for file_type in file_types:
        file_name = f"{file_type}_{year}.csv"

        url = f"https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/{file_name}"

        try:
            response = requests.get(url)

            if response.status_code == 200:
                with open(save_folder / file_name, "wb") as f:
                    f.write(response.content)
                    print(f"Downloaded {file_name}")

            else:
                print(f"Missing {file_name}")

        
        except Exception as e:
            print(e)

Downloaded atp_matches_1991.csv
Downloaded atp_matches_futures_1991.csv
Downloaded atp_matches_qual_chall_1991.csv
Downloaded atp_matches_1992.csv
Downloaded atp_matches_futures_1992.csv
Downloaded atp_matches_qual_chall_1992.csv
Downloaded atp_matches_1993.csv
Downloaded atp_matches_futures_1993.csv
Downloaded atp_matches_qual_chall_1993.csv
Downloaded atp_matches_1994.csv
Downloaded atp_matches_futures_1994.csv
Downloaded atp_matches_qual_chall_1994.csv
Downloaded atp_matches_1995.csv
Downloaded atp_matches_futures_1995.csv
Downloaded atp_matches_qual_chall_1995.csv
Downloaded atp_matches_1996.csv
Downloaded atp_matches_futures_1996.csv
Downloaded atp_matches_qual_chall_1996.csv
Downloaded atp_matches_1997.csv
Downloaded atp_matches_futures_1997.csv
Downloaded atp_matches_qual_chall_1997.csv
Downloaded atp_matches_1998.csv
Downloaded atp_matches_futures_1998.csv
Downloaded atp_matches_qual_chall_1998.csv
Downloaded atp_matches_1999.csv
Downloaded atp_matches_futures_1999.csv
Downloaded atp_matches_qual_chall_1999.csv
Downloaded atp_matches_2000.csv
Downloaded atp_matches_futures_2000.csv
Downloaded atp_matches_qual_chall_2000.csv
Downloaded atp_matches_2001.csv
Downloaded atp_matches_futures_2001.csv
Downloaded atp_matches_qual_chall_2001.csv
Downloaded atp_matches_2002.csv
Downloaded atp_matches_futures_2002.csv
Downloaded atp_matches_qual_chall_2002.csv
Downloaded atp_matches_2003.csv
Downloaded atp_matches_futures_2003.csv
Downloaded atp_matches_qual_chall_2003.csv
Downloaded atp_matches_2004.csv
Downloaded atp_matches_futures_2004.csv
Downloaded atp_matches_qual_chall_2004.csv
Downloaded atp_matches_2005.csv
Downloaded atp_matches_futures_2005.csv
Downloaded atp_matches_qual_chall_2005.csv
Downloaded atp_matches_2006.csv
Downloaded atp_matches_futures_2006.csv
Downloaded atp_matches_qual_chall_2006.csv
Downloaded atp_matches_2007.csv
Downloaded atp_matches_futures_2007.csv
Downloaded atp_matches_qual_chall_2007.csv
Downloaded atp_matches_2008.csv
Downloaded atp_matches_futures_2008.csv
Downloaded atp_matches_qual_chall_2008.csv
Downloaded atp_matches_2009.csv
Downloaded atp_matches_futures_2009.csv
Downloaded atp_matches_qual_chall_2009.csv
Downloaded atp_matches_2010.csv
Downloaded atp_matches_futures_2010.csv
Downloaded atp_matches_qual_chall_2010.csv
Downloaded atp_matches_2011.csv
Downloaded atp_matches_futures_2011.csv
Downloaded atp_matches_qual_chall_2011.csv
Downloaded atp_matches_2012.csv
Downloaded atp_matches_futures_2012.csv
Downloaded atp_matches_qual_chall_2012.csv
Downloaded atp_matches_2013.csv
Downloaded atp_matches_futures_2013.csv
Downloaded atp_matches_qual_chall_2013.csv
Downloaded atp_matches_2014.csv
Downloaded atp_matches_futures_2014.csv
Downloaded atp_matches_qual_chall_2014.csv
Downloaded atp_matches_2015.csv
Downloaded atp_matches_futures_2015.csv
Downloaded atp_matches_qual_chall_2015.csv
Downloaded atp_matches_2016.csv
Downloaded atp_matches_futures_2016.csv
Downloaded atp_matches_qual_chall_2016.csv
Downloaded atp_matches_2017.csv
Downloaded atp_matches_futures_2017.csv
Downloaded atp_matches_qual_chall_2017.csv
Downloaded atp_matches_2018.csv
Downloaded atp_matches_futures_2018.csv
Downloaded atp_matches_qual_chall_2018.csv
Downloaded atp_matches_2019.csv
Downloaded atp_matches_futures_2019.csv
Downloaded atp_matches_qual_chall_2019.csv
Downloaded atp_matches_2020.csv
Downloaded atp_matches_futures_2020.csv
Downloaded atp_matches_qual_chall_2020.csv
Downloaded atp_matches_2021.csv
Downloaded atp_matches_futures_2021.csv
Downloaded atp_matches_qual_chall_2021.csv
Downloaded atp_matches_2022.csv
Downloaded atp_matches_futures_2022.csv
Downloaded atp_matches_qual_chall_2022.csv
Downloaded atp_matches_2023.csv
Downloaded atp_matches_futures_2023.csv
Downloaded atp_matches_qual_chall_2023.csv
Downloaded atp_matches_2024.csv
Downloaded atp_matches_futures_2024.csv
Downloaded atp_matches_qual_chall_2024.csv
Downloaded atp_matches_2025.csv
Downloaded atp_matches_futures_2025.csv
Downloaded atp_matches_qual_chall_2025.csv
Downloaded atp_matches_2026.csv
Downloaded atp_matches_futures_2026.csv
Downloaded atp_matches_qual_chall_2026.csv

## *Combining and Converting to Dataframe*

In [2]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("data/tennis_atp")

dfs = list()

for year in range(1991, 2027):
    file_types = ["atp_matches", "atp_matches_futures", "atp_matches_qual_chall"]

    for file in file_types:
        file_name = f"{file}_{year}.csv"
        file = DATA_DIR / file_name

        if file.exists():
            print(f"Loading {file_name}")
            df = pd.read_csv(file)
            dfs.append(df)
        else:
            print(f"Skipping missing file: {file_name}")

matches_df = pd.concat(dfs, axis = 0, ignore_index= True, sort= False)

Loading atp_matches_1991.csv
Loading atp_matches_futures_1991.csv
Loading atp_matches_qual_chall_1991.csv
Loading atp_matches_1992.csv
Loading atp_matches_futures_1992.csv
Loading atp_matches_qual_chall_1992.csv
Loading atp_matches_1993.csv
Loading atp_matches_futures_1993.csv
Loading atp_matches_qual_chall_1993.csv
Loading atp_matches_1994.csv
Loading atp_matches_futures_1994.csv
Loading atp_matches_qual_chall_1994.csv
Loading atp_matches_1995.csv
Loading atp_matches_futures_1995.csv
Loading atp_matches_qual_chall_1995.csv
Loading atp_matches_1996.csv
Loading atp_matches_futures_1996.csv
Loading atp_matches_qual_chall_1996.csv
Loading atp_matches_1997.csv
Loading atp_matches_futures_1997.csv
Loading atp_matches_qual_chall_1997.csv
Loading atp_matches_1998.csv
Loading atp_matches_futures_1998.csv
Loading atp_matches_qual_chall_1998.csv
Loading atp_matches_1999.csv
Loading atp_matches_futures_1999.csv
Loading atp_matches_qual_chall_1999.csv
Loading atp_matches_2000.csv
Loading atp_matches_futures_2000.csv
Loading atp_matches_qual_chall_2000.csv
Loading atp_matches_2001.csv
Loading atp_matches_futures_2001.csv
Loading atp_matches_qual_chall_2001.csv
Loading atp_matches_2002.csv
Loading atp_matches_futures_2002.csv
Loading atp_matches_qual_chall_2002.csv
Loading atp_matches_2003.csv
Loading atp_matches_futures_2003.csv
Loading atp_matches_qual_chall_2003.csv
Loading atp_matches_2004.csv
Loading atp_matches_futures_2004.csv
Loading atp_matches_qual_chall_2004.csv
Loading atp_matches_2005.csv
Loading atp_matches_futures_2005.csv
Loading atp_matches_qual_chall_2005.csv
Loading atp_matches_2006.csv
Loading atp_matches_futures_2006.csv
Loading atp_matches_qual_chall_2006.csv
Loading atp_matches_2007.csv
Loading atp_matches_futures_2007.csv
Loading atp_matches_qual_chall_2007.csv
Loading atp_matches_2008.csv
Loading atp_matches_futures_2008.csv
Loading atp_matches_qual_chall_2008.csv
Loading atp_matches_2009.csv
Loading atp_matches_futures_2009.csv
Loading atp_matches_qual_chall_2009.csv
Loading atp_matches_2010.csv
Loading atp_matches_futures_2010.csv
Loading atp_matches_qual_chall_2010.csv
Loading atp_matches_2011.csv
Loading atp_matches_futures_2011.csv
Loading atp_matches_qual_chall_2011.csv
Loading atp_matches_2012.csv
Loading atp_matches_futures_2012.csv
Loading atp_matches_qual_chall_2012.csv
Loading atp_matches_2013.csv
Loading atp_matches_futures_2013.csv
Loading atp_matches_qual_chall_2013.csv
Loading atp_matches_2014.csv
Loading atp_matches_futures_2014.csv
Loading atp_matches_qual_chall_2014.csv
Loading atp_matches_2015.csv
Loading atp_matches_futures_2015.csv
Loading atp_matches_qual_chall_2015.csv
Loading atp_matches_2016.csv
Loading atp_matches_futures_2016.csv
Loading atp_matches_qual_chall_2016.csv
Loading atp_matches_2017.csv
Loading atp_matches_futures_2017.csv
Loading atp_matches_qual_chall_2017.csv
Loading atp_matches_2018.csv
Loading atp_matches_futures_2018.csv
Loading atp_matches_qual_chall_2018.csv
Loading atp_matches_2019.csv
Loading atp_matches_futures_2019.csv
Loading atp_matches_qual_chall_2019.csv
Loading atp_matches_2020.csv
Loading atp_matches_futures_2020.csv
Loading atp_matches_qual_chall_2020.csv
Loading atp_matches_2021.csv
Loading atp_matches_futures_2021.csv
Loading atp_matches_qual_chall_2021.csv
Loading atp_matches_2022.csv
Loading atp_matches_futures_2022.csv
Loading atp_matches_qual_chall_2022.csv
Loading atp_matches_2023.csv
Loading atp_matches_futures_2023.csv
Loading atp_matches_qual_chall_2023.csv
Loading atp_matches_2024.csv
Loading atp_matches_futures_2024.csv
Loading atp_matches_qual_chall_2024.csv
Loading atp_matches_2025.csv
Loading atp_matches_futures_2025.csv
Loading atp_matches_qual_chall_2025.csv
Loading atp_matches_2026.csv
Loading atp_matches_futures_2026.csv
Loading atp_matches_qual_chall_2026.csv

In [ ]:
DF_DIR = Path("data/created_data")

matches_df.to_csv(DF_DIR / "matches_1991_2026_combined.csv", index = False)

# **Analysing the Data**

In [1]:
import pandas as pd
from pathlib import Path

DF_DIR = Path("data/created_data")

matches_df = pd.read_csv(DF_DIR / "matches_1991_2026_combined.csv")

In [2]:
unique_players = pd.unique(pd.concat([matches_df["winner_id"], matches_df["loser_id"]])).size

unique_tournaments = matches_df["tourney_id"].nunique()

print(f"Unique players: {unique_players}")
print(f"Unique tournaments: {unique_tournaments}")

Unique players: 25232
Unique tournaments: 27180

In [3]:
pd.set_option("display.max_columns", None)
matches_df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1991-339,Adelaide,Hard,32,A,19901231,1,101723,NaN,NaN,Magnus Larsson,R,193.0,SWE,20.7,101414,1.0,NaN,Boris Becker,R,190.0,GER,23.1,6-4 3-6 7-6(2),3,R32,130.0,6.0,2.0,96.0,55.0,39.0,25.0,15.0,2.0,4.0,8.0,3.0,95.0,62.0,44.0,23.0,16.0,6.0,8.0,56.0,NaN,2.0,NaN
1,1991-339,Adelaide,Hard,32,A,19901231,2,100946,NaN,Q,Slobodan Zivojinovic,R,198.0,YUG,27.4,101256,NaN,NaN,Mark Kratzmann,L,178.0,AUS,24.6,6-3 3-6 7-6(6),3,R32,119.0,19.0,4.0,101.0,56.0,45.0,25.0,15.0,9.0,10.0,8.0,2.0,84.0,41.0,35.0,27.0,15.0,1.0,2.0,304.0,NaN,75.0,NaN
2,1991-339,Adelaide,Hard,32,A,19901231,3,101234,NaN,NaN,Patrik Kuhnen,R,190.0,GER,24.8,101421,NaN,NaN,Veli Paloheimo,R,183.0,FIN,23.0,6-0 6-4,3,R32,71.0,6.0,1.0,54.0,31.0,24.0,13.0,8.0,1.0,1.0,2.0,2.0,60.0,37.0,22.0,6.0,8.0,4.0,8.0,82.0,NaN,69.0,NaN
3,1991-339,Adelaide,Hard,32,A,19901231,4,101889,8.0,NaN,Todd Woodbridge,R,178.0,AUS,19.7,101703,NaN,NaN,Guillaume Raoux,R,180.0,FRA,20.8,7-6(2) 6-1,3,R32,85.0,2.0,0.0,60.0,40.0,30.0,14.0,9.0,3.0,3.0,3.0,3.0,74.0,45.0,30.0,11.0,10.0,5.0,8.0,50.0,NaN,84.0,NaN
4,1991-339,Adelaide,Hard,32,A,19901231,5,101274,NaN,NaN,Udo Riglewski,R,185.0,GER,24.4,101843,4.0,NaN,Sergi Bruguera,R,188.0,ESP,19.9,7-5 6-3,3,R32,90.0,4.0,2.0,72.0,40.0,33.0,14.0,10.0,7.0,8.0,2.0,2.0,77.0,41.0,28.0,15.0,11.0,4.0,8.0,88.0,NaN,28.0,NaN

In [4]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 855194 entries, 0 to 855193
Data columns (total 49 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          855194 non-null  object
 1   tourney_name        855194 non-null  object
 2   surface             855141 non-null  object
 3   draw_size           855194 non-null  int64
 4   tourney_level       855194 non-null  object
 5   tourney_date        855194 non-null  int64
 6   match_num           855194 non-null  int64
 7   winner_id           855194 non-null  int64
 8   winner_seed         373653 non-null  float64
 9   winner_entry        153924 non-null  object
 10  winner_name         855194 non-null  object
 11  winner_hand         855192 non-null  object
 12  winner_ht           596330 non-null  float64
 13  winner_ioc          855194 non-null  object
 14  winner_age          849770 non-null  float64
 15  loser_id            855194 non-null  int64
 16  loser_seed          193863 non-null  float64
 17  loser_entry         273240 non-null  object
 18  loser_name          855194 non-null  object
 19  loser_hand          855174 non-null  object
 20  loser_ht            494223 non-null  float64
 21  loser_ioc           855181 non-null  object
 22  loser_age           844254 non-null  float64
 23  score               855113 non-null  object
 24  best_of             855194 non-null  int64
 25  round               855194 non-null  object
 26  minutes             252728 non-null  float64
 27  w_ace               259680 non-null  float64
 28  w_df                259680 non-null  float64
 29  w_svpt              259680 non-null  float64
 30  w_1stIn             259680 non-null  float64
 31  w_1stWon            259680 non-null  float64
 32  w_2ndWon            259680 non-null  float64
 33  w_SvGms             259678 non-null  float64
 34  w_bpSaved           259680 non-null  float64
 35  w_bpFaced           259680 non-null  float64
 36  l_ace               259680 non-null  float64
 37  l_df                259680 non-null  float64
 38  l_svpt              259680 non-null  float64
 39  l_1stIn             259680 non-null  float64
 40  l_1stWon            259680 non-null  float64
 41  l_2ndWon            259680 non-null  float64
 42  l_SvGms             259678 non-null  float64
 43  l_bpSaved           259680 non-null  float64
 44  l_bpFaced           259680 non-null  float64
 45  winner_rank         811544 non-null  float64
 46  winner_rank_points  801475 non-null  float64
 47  loser_rank          747661 non-null  float64
 48  loser_rank_points   738557 non-null  float64
dtypes: float64(29), int64(6), object(14)
memory usage: 319.7+ MB

around 30.4% of the data has the required columns to calculate 'p'.

In [5]:
pd.set_option("display.max_columns", None)
matches_df.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,loser_age,best_of,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,855194.000000,8.551940e+05,855194.000000,855194.000000,373653.000000,596330.000000,849770.000000,855194.000000,193863.000000,494223.000000,844254.000000,855194.000000,252728.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259678.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259678.000000,259680.000000,259680.000000,811544.000000,801475.000000,747661.000000,738557.000000
mean,37.036018,2.010063e+07,93.190606,120873.069384,4.821243,184.240276,23.915665,123400.974548,5.558234,184.127101,23.510117,3.057847,101.607602,5.398629,2.607598,72.338520,44.680980,33.154571,15.137461,11.448398,3.389533,5.019478,3.983337,3.367229,74.964083,45.104833,29.190261,13.421977,11.273870,4.598567,8.518492,485.546930,305.682507,603.759626,214.939695
std,20.156683,9.895995e+04,150.389028,35198.472661,3.757301,8.249421,3.864606,36606.790094,4.100638,8.476154,4.061711,0.335182,38.898360,4.639122,2.243477,25.893545,16.939184,11.877792,6.262052,3.596989,2.962924,3.894749,4.054815,2.488483,25.527579,16.974382,12.732663,6.519178,3.600828,3.100304,3.810911,375.333661,824.534052,461.234328,506.990527
min,2.000000,1.990123e+07,1.000000,100113.000000,1.000000,3.000000,14.000000,100063.000000,1.000000,3.000000,14.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,32.000000,2.002062e+07,11.000000,103385.000000,2.000000,180.000000,21.000000,103554.000000,3.000000,180.000000,20.400000,3.000000,75.000000,2.000000,1.000000,53.000000,33.000000,25.000000,11.000000,9.000000,1.000000,2.000000,1.000000,2.000000,57.000000,33.000000,20.000000,9.000000,9.000000,2.000000,6.000000,197.000000,28.000000,224.000000,12.000000
50%,32.000000,2.011052e+07,23.000000,104963.000000,4.000000,185.000000,23.500000,105318.000000,5.000000,185.000000,23.000000,3.000000,95.000000,4.000000,2.000000,68.000000,42.000000,31.000000,14.000000,11.000000,3.000000,4.000000,3.000000,3.000000,70.000000,42.000000,27.000000,13.000000,10.000000,4.000000,8.000000,413.000000,84.000000,508.000000,55.000000
75%,32.000000,2.018070e+07,110.000000,111466.000000,7.000000,188.000000,26.300000,122621.000000,7.000000,188.000000,26.000000,3.000000,123.000000,7.000000,4.000000,88.000000,54.000000,40.000000,19.000000,14.000000,5.000000,7.000000,6.000000,5.000000,90.000000,55.000000,36.000000,17.000000,14.000000,6.000000,11.000000,676.000000,244.000000,888.000000,208.000000
max,128.000000,2.026060e+07,1701.000000,214625.000000,35.000000,211.000000,63.400000,214629.000000,38.000000,211.000000,72.100000,5.000000,4756.000000,113.000000,34.000000,491.000000,361.000000,292.000000,82.000000,90.000000,25.000000,34.000000,103.000000,51.000000,489.000000,328.000000,284.000000,101.000000,91.000000,28.000000,38.000000,2260.000000,16950.000000,2267.000000,16950.000000

# **Fixing the Data**

In [6]:
import pandas as pd

DF_DIR = Path("data/created_data")

matches_df = pd.read_csv(DF_DIR / "matches_1991_2026_combined.csv")

In [7]:
matches_df_original_copy = matches_df.copy()

## *Fixing the Datatime Column*

In [8]:
matches_df["tourney_date"] = pd.to_datetime(matches_df["tourney_date"].astype(str), format="%Y%m%d")

In [9]:
matches_df['tourney_date'].head()

0   1990-12-31
1   1990-12-31
2   1990-12-31
3   1990-12-31
4   1990-12-31
Name: tourney_date, dtype: datetime64[ns]

## *Arranging in Chronological Order*

In [10]:
matches_df['round'].unique()

array(['R32', 'R16', 'QF', 'SF', 'F', 'R128', 'R64', 'RR', 'BR', 'Q1',
       'Q2', 'Q3', 'ER', 'Q4'], dtype=object)

In [11]:
ROUND_ORDER = {
    "Q1": 1,
    "Q2": 2,
    "Q3": 3,
    "Q4": 4,
    "R128": 6,
    "R64": 7,
    "R32": 8,
    "R16": 9,
    "RR": 10,
    "QF": 11,
    "SF": 12,
    "BR": 13,
    "F": 14,
    "ER": 15
}

matches_df["round_rank"] = (matches_df["round"].map(ROUND_ORDER))

In [12]:
#this check will catch new round codes
matches_df[matches_df["round_rank"].isna()]["round"].unique()

array([], dtype=object)

In [13]:
#verifying if round ranking looks correct

matches_df[['round', 'round_rank']].drop_duplicates().sort_values(by= 'round_rank')

       round  round_rank
182986    Q1           1
183050    Q2           2
183082    Q3           3
396690    Q4           4
124     R128           6
188      R64           7
0        R32           8
16       R16           9
251       RR          10
24        QF          11
28        SF          12
85949     BR          13
30         F          14
316416    ER          15

In [14]:
#sorting the values

matches_df = matches_df.sort_values(by= ["tourney_date", "tourney_name", "round_rank"]).reset_index(drop= True)

In [15]:
#verification-1

matches_df[['tourney_date', 'tourney_name', 'round']].head(10)

  tourney_date     tourney_name round
0   1990-12-29  India Masters 1   R32
1   1990-12-29  India Masters 1   R32
2   1990-12-29  India Masters 1   R32
3   1990-12-29  India Masters 1   R32
4   1990-12-29  India Masters 1   R32
5   1990-12-29  India Masters 1   R32
6   1990-12-29  India Masters 1   R32
7   1990-12-29  India Masters 1   R32
8   1990-12-29  India Masters 1   R32
9   1990-12-29  India Masters 1   R32

In [16]:
#verification-2

matches_df[['tourney_date', 'tourney_name', 'round']].tail(10)

       tourney_date tourney_name round
855184   2026-06-01     Tyler CH   R16
855185   2026-06-01     Tyler CH   R16
855186   2026-06-01     Tyler CH   R16
855187   2026-06-01     Tyler CH    QF
855188   2026-06-01     Tyler CH    QF
855189   2026-06-01     Tyler CH    QF
855190   2026-06-01     Tyler CH    QF
855191   2026-06-01     Tyler CH    SF
855192   2026-06-01     Tyler CH    SF
855193   2026-06-01     Tyler CH     F

## *Converting to PlayerA/PlayerB Format*

In [17]:
import numpy as np
import pandas as pd

np.random.seed(42)

random_num = np.random.rand(len(matches_df))

winner_is_A = random_num < 0.5
matches_df['playerA_wins'] = winner_is_A.astype(int) #1 if A wins, 0 if A loses

In [18]:
player_attributes = [
    "id",
    "seed",
    "entry",
    "name",
    "hand",
    "ht",
    "ioc",
    "age",
    "rank",
    "rank_points"
]

for attr in player_attributes:
    winner_col = f"winner_{attr}"
    loser_col = f"loser_{attr}"

    matches_df[f"playerA_{attr}"] = np.where(winner_is_A, matches_df[winner_col], matches_df[loser_col])
    matches_df[f"playerB_{attr}"] = np.where(winner_is_A, matches_df[loser_col], matches_df[winner_col])

In [19]:
stat_attributes = [
    "ace",
    "df",
    "svpt",
    "1stIn",
    "1stWon",
    "2ndWon",
    "SvGms",
    "bpSaved",
    "bpFaced"
]

for attr in stat_attributes:
    winner_col = f"w_{attr}"
    loser_col = f"l_{attr}"

    matches_df[f"playerA_{attr}"] = np.where(winner_is_A, matches_df[winner_col], matches_df[loser_col])
    matches_df[f"playerB_{attr}"] = np.where(winner_is_A, matches_df[loser_col], matches_df[winner_col])

In [20]:
#dropping old columns

winner_loser_cols = [
    col for col in matches_df.columns
    if col.startswith("winner_")
    or col.startswith("loser_")
    or col.startswith("w_")
    or col.startswith("l_")
]

matches_df = matches_df.drop(columns= winner_loser_cols)

In [21]:
matches_df['winner_is_A'] = winner_is_A

In [22]:
#verification-1
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 855194 entries, 0 to 855193
Data columns (total 52 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   tourney_id           855194 non-null  object
 1   tourney_name         855194 non-null  object
 2   surface              855141 non-null  object
 3   draw_size            855194 non-null  int64
 4   tourney_level        855194 non-null  object
 5   tourney_date         855194 non-null  datetime64[ns]
 6   match_num            855194 non-null  int64
 7   score                855113 non-null  object
 8   best_of              855194 non-null  int64
 9   round                855194 non-null  object
 10  minutes              252728 non-null  float64
 11  round_rank           855194 non-null  int64
 12  playerA_wins         855194 non-null  int64
 13  playerA_id           855194 non-null  int64
 14  playerB_id           855194 non-null  int64
 15  playerA_seed         284059 non-null  float64
 16  playerB_seed         283457 non-null  float64
 17  playerA_entry        213701 non-null  object
 18  playerB_entry        213463 non-null  object
 19  playerA_name         855194 non-null  object
 20  playerB_name         855194 non-null  object
 21  playerA_hand         855179 non-null  object
 22  playerB_hand         855187 non-null  object
 23  playerA_ht           545385 non-null  float64
 24  playerB_ht           545168 non-null  float64
 25  playerA_ioc          855187 non-null  object
 26  playerB_ioc          855188 non-null  object
 27  playerA_age          847016 non-null  float64
 28  playerB_age          847008 non-null  float64
 29  playerA_rank         779861 non-null  float64
 30  playerB_rank         779344 non-null  float64
 31  playerA_rank_points  770253 non-null  float64
 32  playerB_rank_points  769779 non-null  float64
 33  playerA_ace          259680 non-null  float64
 34  playerB_ace          259680 non-null  float64
 35  playerA_df           259680 non-null  float64
 36  playerB_df           259680 non-null  float64
 37  playerA_svpt         259680 non-null  float64
 38  playerB_svpt         259680 non-null  float64
 39  playerA_1stIn        259680 non-null  float64
 40  playerB_1stIn        259680 non-null  float64
 41  playerA_1stWon       259680 non-null  float64
 42  playerB_1stWon       259680 non-null  float64
 43  playerA_2ndWon       259680 non-null  float64
 44  playerB_2ndWon       259680 non-null  float64
 45  playerA_SvGms        259678 non-null  float64
 46  playerB_SvGms        259678 non-null  float64
 47  playerA_bpSaved      259680 non-null  float64
 48  playerB_bpSaved      259680 non-null  float64
 49  playerA_bpFaced      259680 non-null  float64
 50  playerB_bpFaced      259680 non-null  float64
 51  winner_is_A          855194 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(29), int64(7), object(14)
memory usage: 333.6+ MB

In [23]:
#verification-2
matches_df["playerA_wins"].mean()

np.float64(0.49958722816109563)

In [24]:
#verification-3
matches_df[["playerA_name", "playerB_name", "playerA_wins", "winner_is_A"]].head()

           playerA_name      playerB_name  playerA_wins  winner_is_A
0  Vladimir Gabrichidze  Emilio Marturano             1         True
1      Goran Mihajlovic       Danilo Pila             0        False
2      York Heidenreich      Mark Joachim             0        False
3              Eno Polo     Eugenio Rossi             0        False
4  Srinivasan Vasudevan       Jake Martyn             1         True

In [25]:
matches_df.drop(columns= "winner_is_A", inplace= True)

## *Reseting Index*

In [26]:
matches_df = matches_df.reset_index(drop=True)
matches_df["match_id"] = matches_df.index

In [27]:
matches_df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,score,best_of,round,minutes,round_rank,playerA_wins,playerA_id,playerB_id,playerA_seed,playerB_seed,playerA_entry,playerB_entry,playerA_name,playerB_name,playerA_hand,playerB_hand,playerA_ht,playerB_ht,playerA_ioc,playerB_ioc,playerA_age,playerB_age,playerA_rank,playerB_rank,playerA_rank_points,playerB_rank_points,playerA_ace,playerB_ace,playerA_df,playerB_df,playerA_svpt,playerB_svpt,playerA_1stIn,playerB_1stIn,playerA_1stWon,playerB_1stWon,playerA_2ndWon,playerB_2ndWon,playerA_SvGms,playerB_SvGms,playerA_bpSaved,playerB_bpSaved,playerA_bpFaced,playerB_bpFaced,match_id
0,1991-M-SA-IND-02A-1990a,India Masters 1,Hard,32,S,1990-12-29,1,6-2 7-5,3,R32,NaN,8,1,101484,106937,1.0,NaN,NaN,NaN,Vladimir Gabrichidze,Emilio Marturano,R,R,175.0,NaN,GEO,ITA,22.6,23.5,266.0,805.0,82.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1991-M-SA-IND-02A-1990a,India Masters 1,Hard,32,S,1990-12-29,2,6-3 6-2,3,R32,NaN,8,0,107116,106819,NaN,NaN,NaN,Q,Goran Mihajlovic,Danilo Pila,R,R,NaN,NaN,YUG,PHI,19.6,30.2,692.0,941.0,8.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,1991-M-SA-IND-02A-1990a,India Masters 1,Hard,32,S,1990-12-29,3,6-1 6-3,3,R32,NaN,8,0,108562,102216,NaN,NaN,NaN,LL,York Heidenreich,Mark Joachim,R,R,NaN,NaN,GER,GER,NaN,17.6,862.0,862.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1991-M-SA-IND-02A-1990a,India Masters 1,Hard,32,S,1990-12-29,4,6-4 6-4,3,R32,NaN,8,0,106941,101663,8.0,NaN,NaN,NaN,Eno Polo,Eugenio Rossi,R,R,NaN,NaN,KEN,ITA,23.5,21.1,588.0,703.0,14.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,1991-M-SA-IND-02A-1990a,India Masters 1,Hard,32,S,1990-12-29,5,6-3 7-6,3,R32,NaN,8,1,100794,101480,4.0,NaN,NaN,NaN,Srinivasan Vasudevan,Jake Martyn,R,R,190.0,NaN,IND,GBR,28.9,22.6,420.0,862.0,33.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [28]:
matches_df.to_csv(DF_DIR / "matches_1991_to_2026_cleaned.csv", index = False)

# **Adding Features**

In [29]:
from pathlib import Path
import pandas as pd

DF_DIR = Path("data/created_data")
matches_df = pd.read_csv(DF_DIR / "matches_1991_to_2026_cleaned.csv")

In [30]:
matches_df_fixed_copy = matches_df.copy()

## *Matchup Features*

In [31]:
#data test-1
matches_df['playerA_hand'].value_counts(dropna= False)

playerA_hand
R      656887
U      103465
L       94508
A         319
NaN        15
Name: count, dtype: int64

In [32]:
#data test-2
matches_df['playerB_hand'].value_counts(dropna = False)

playerB_hand
R      657928
U      103117
L       93832
A         310
NaN         7
Name: count, dtype: int64

In [33]:
#data fix-1
matches_df['playerA_hand'] = matches_df['playerA_hand'].fillna(value= 'U')
matches_df['playerB_hand'] = matches_df['playerB_hand'].fillna(value= 'U')

matches_df['playerA_hand'].value_counts(dropna= False)

playerA_hand
R    656887
U    103480
L     94508
A       319
Name: count, dtype: int64

In [34]:
#data test-3
matches_df['surface'].isna().sum()

np.int64(53)

In [35]:
matches_df = matches_df.dropna(subset=['surface'])
matches_df['surface'] = matches_df['surface'].str.capitalize()
matches_df['surface'].isna().sum()

np.int64(0)

In [36]:
#data test-4
matches_df['playerA_wins'].value_counts(dropna=False)

playerA_wins
0    427920
1    427221
Name: count, dtype: int64

In [37]:
#creating features

from collections import defaultdict, deque
import numpy as np

#storage dictioneries
h2h_record = defaultdict(lambda: [0,0]) #key (playerA, playerB)
surface_h2h_record = defaultdict(lambda: [0,0]) #key ((playerA, playerB), surface)
last5_h2h_record = defaultdict(lambda: deque(maxlen= 5)) #key (playerA, playerB)
top20_record = defaultdict(lambda: [0,0]) #key player
hand_record = defaultdict(lambda: defaultdict(lambda: [0,0])) #key [player][opp_hand]

#feature_lists
h2h_playerA_wins = []
h2h_playerB_wins = []
h2h_total = []
h2h_diff = []

surface_h2h_playerA_wins = []
surface_h2h_playerB_wins = []
surface_h2h_total = []
surface_h2h_diff = []

last5_h2h_playerA_wins = []
last5_h2h_playerB_wins = []
last5_total = []
last5_h2h_diff = []

playerA_top20_wins = []
playerA_top20_losses = []
playerA_top20_win_pct = []
playerB_top20_wins = []
playerB_top20_losses = []
playerB_top20_win_pct = []

playerA_hand_wins = []
playerA_hand_losses = []
playerA_hand_win_pct = []
playerB_hand_wins = []
playerB_hand_losses = []
playerB_hand_win_pct = []


#loop to create the features
for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id
    winner = row.playerA_id if row.playerA_wins ==1 else row.playerB_id
    loser = row.playerB_id if row.playerA_wins == 1 else row.playerA_id
    surface = row.surface

    pair = (min(playerA, playerB), max(playerA, playerB))

    #---------------
    # OVERALL H2H
    #---------------
    h2h_record_pair_0 = h2h_record[pair][0]
    h2h_record_pair_1 = h2h_record[pair][1]

    if playerA == pair[0]:
        wins_A = h2h_record_pair_0
        wins_B = h2h_record_pair_1
    else:
        wins_A = h2h_record_pair_1
        wins_B = h2h_record_pair_0

    h2h_playerA_wins.append(wins_A)
    h2h_playerB_wins.append(wins_B)
    h2h_total.append(wins_A + wins_B)
    h2h_diff.append(wins_A - wins_B)


    #----------------
    # SURFACE H2H
    #----------------
    surface_pair = (pair, surface)

    surface_pair_0 = surface_h2h_record[surface_pair][0]
    surface_pair_1 = surface_h2h_record[surface_pair][1]

    if playerA == pair[0]:
        wins_A = surface_pair_0
        wins_B = surface_pair_1
    else:
        wins_A = surface_pair_1
        wins_B = surface_pair_0

    surface_h2h_playerA_wins.append(wins_A)
    surface_h2h_playerB_wins.append(wins_B)
    surface_h2h_diff.append(wins_A - wins_B)
    surface_h2h_total.append(wins_A + wins_B)


    #-----------------
    # LAST 5 H2H
    #-----------------
    history = last5_h2h_record[pair]

    pair0_wins = sum(history)
    pair1_wins = len(history) - pair0_wins

    if playerA == pair[0]:
        playerA_last5 = pair0_wins
        playerB_last5 = pair1_wins
    else:
        playerA_last5 = pair1_wins
        playerB_last5 = pair0_wins

    last5_h2h_playerA_wins.append(playerA_last5)
    last5_h2h_playerB_wins.append(playerB_last5)
    last5_total.append(len(history))
    last5_h2h_diff.append(playerA_last5 - playerB_last5)

    
    #----------------------------
    # PERFORMANCE AGAINST TOP20
    #----------------------------
    # for player A
    wins, losses = top20_record[playerA]

    playerA_top20_wins.append(wins)
    playerA_top20_losses.append(losses)
    playerA_top20_win_pct.append(wins/(wins+losses)) if wins+losses>0 else playerA_top20_win_pct.append(0.5)

    #for player B
    wins, losses = top20_record[playerB]

    playerB_top20_wins.append(wins)
    playerB_top20_losses.append(losses)
    playerB_top20_win_pct.append(wins/(wins+losses)) if wins+losses>0 else playerB_top20_win_pct.append(0.5)


    #--------------------------------
    # PERFORMANCE AGAINST OPP HAND
    #--------------------------------
    #for playerA
    opp_hand = row.playerB_hand

    wins, losses = hand_record[playerA][opp_hand]

    playerA_hand_wins.append(wins)
    playerA_hand_losses.append(losses)
    playerA_hand_win_pct.append(wins/(wins+losses)) if wins+losses > 0 else playerA_hand_win_pct.append(0.5)

    #for player B
    opp_hand = row.playerA_hand

    wins, losses = hand_record[playerB][opp_hand]

    playerB_hand_wins.append(wins)
    playerB_hand_losses.append(losses)
    playerB_hand_win_pct.append(wins/(wins+losses)) if wins+losses > 0 else playerB_hand_win_pct.append(0.5)





    #---------------
    # UPDATES
    #---------------
    #overall H2H
    if pair[0] == winner:
        h2h_record[pair][0] += 1
    else:
        h2h_record[pair][1] += 1

    #surface H2H
    if pair[0] == winner:
        surface_h2h_record[surface_pair][0] += 1
    else:
        surface_h2h_record[surface_pair][1] += 1

    #last 5 H2H
    if winner == pair[0]:
        history.append(1)
    else:
        history.append(0)

    #top 20
    if pd.notna(row.playerB_rank) and row.playerB_rank <=20:
        if winner==playerA:
            top20_record[playerA][0] += 1
        else:
            top20_record[playerA][1] += 1
    if pd.notna(row.playerA_rank) and row.playerA_rank <= 20:
        if winner == playerB:
            top20_record[playerB][0] += 1
        else:
            top20_record[playerB][1] +=1

    #hand
    if winner==playerA:
        hand_record[playerA][row.playerB_hand][0] +=1
        hand_record[playerB][row.playerA_hand][1] +=1
    else:
        hand_record[playerB][row.playerA_hand][0] += 1
        hand_record[playerA][row.playerB_hand][1] +=1



#attaching features to the dataframe
matches_df['playerA_h2h_wins'] = h2h_playerA_wins
matches_df['playerB_h2h_wins'] = h2h_playerB_wins
matches_df['h2h_total'] = h2h_total
matches_df['h2h_diff'] = h2h_diff

matches_df["playerA_surface_h2h_wins"] = surface_h2h_playerA_wins
matches_df["playerB_surface_h2h_wins"] = surface_h2h_playerB_wins
matches_df['surface_h2h_total'] = surface_h2h_total
matches_df['surface_h2h_diff'] = surface_h2h_diff

matches_df['playerA_last5_h2h_wins'] = last5_h2h_playerA_wins
matches_df['playerB_last5_h2h_wins'] = last5_h2h_playerB_wins
matches_df['last5_h2h_total'] = last5_total
matches_df['last5_h2h_diff'] = last5_h2h_diff

matches_df['playerA_top20_wins'] = playerA_top20_wins
matches_df['playerA_top20_losses'] = playerA_top20_losses
matches_df['playerA_top20_total'] = matches_df['playerA_top20_wins'] + matches_df['playerA_top20_losses'] #new
matches_df['playerA_top20_win_pct'] = playerA_top20_win_pct
matches_df['playerB_top20_wins'] = playerB_top20_wins
matches_df['playerB_top20_losses'] = playerB_top20_losses
matches_df['playerB_top20_total'] = matches_df['playerB_top20_wins'] + matches_df['playerB_top20_losses'] #new
matches_df['playerB_top20_win_pct'] = playerB_top20_win_pct

matches_df['playerA_hand_wins'] = playerA_hand_wins
matches_df['playerA_hand_losses'] = playerA_hand_losses
matches_df['playerA_hand_total'] = matches_df['playerA_hand_losses'] + matches_df['playerA_hand_wins'] #new
matches_df['playerA_hand_win_pct'] = playerA_hand_win_pct
matches_df['playerB_hand_wins'] = playerB_hand_wins
matches_df['playerB_hand_losses'] = playerB_hand_losses
matches_df['playerB_hand_total'] = matches_df['playerB_hand_losses'] + matches_df['playerB_hand_wins'] #new
matches_df['playerB_hand_win_pct'] = playerB_hand_win_pct

In [38]:
#test-1
test = matches_df[
    (
        (matches_df["playerA_name"] == "Novak Djokovic")
        & (matches_df["playerB_name"] == "Rafael Nadal")
    )
    |
    (
        (matches_df["playerA_name"] == "Rafael Nadal")
        & (matches_df["playerB_name"] == "Novak Djokovic")
    )
]

test[
    [
        "playerA_name",
        "playerB_name",
        "playerA_h2h_wins",
        "playerB_h2h_wins",
        "h2h_total"
    ]
]

,playerA_name,playerB_name,playerA_h2h_wins,playerB_h2h_wins,h2h_total
301480,Novak Djokovic,Rafael Nadal,0,0,0
319170,Novak Djokovic,Rafael Nadal,0,1,1
320414,Rafael Nadal,Novak Djokovic,2,0,2
323638,Rafael Nadal,Novak Djokovic,2,1,3
325481,Novak Djokovic,Rafael Nadal,1,3,4
328360,Rafael Nadal,Novak Djokovic,4,1,5
331418,Rafael Nadal,Novak Djokovic,5,1,6
340323,Novak Djokovic,Rafael Nadal,2,5,7
345947,Rafael Nadal,Novak Djokovic,6,2,8
349722,Novak Djokovic,Rafael Nadal,3,6,9
351274,Novak Djokovic,Rafael Nadal,3,7,10
352533,Rafael Nadal,Novak Djokovic,8,3,11
357210,Novak Djokovic,Rafael Nadal,3,9,12
358487,Rafael Nadal,Novak Djokovic,9,4,13
372004,Novak Djokovic,Rafael Nadal,4,10,14
374266,Novak Djokovic,Rafael Nadal,4,11,15
375348,Rafael Nadal,Novak Djokovic,12,4,16
376228,Rafael Nadal,Novak Djokovic,13,4,17
384567,Rafael Nadal,Novak Djokovic,14,4,18
392151,Novak Djokovic,Rafael Nadal,5,14,19
392845,Rafael Nadal,Novak Djokovic,14,6,20
410844,Rafael Nadal,Novak Djokovic,14,7,21
417450,Rafael Nadal,Novak Djokovic,15,7,22
422258,Novak Djokovic,Rafael Nadal,7,16,23
423235,Novak Djokovic,Rafael Nadal,8,16,24
425611,Rafael Nadal,Novak Djokovic,16,9,25
426139,Rafael Nadal,Novak Djokovic,16,10,26
430538,Novak Djokovic,Rafael Nadal,11,16,27
437061,Rafael Nadal,Novak Djokovic,16,12,28
445066,Novak Djokovic,Rafael Nadal,13,16,29
451203,Novak Djokovic,Rafael Nadal,14,16,30
453565,Novak Djokovic,Rafael Nadal,14,17,31
454947,Rafael Nadal,Novak Djokovic,18,14,32
478202,Rafael Nadal,Novak Djokovic,19,14,33
482678,Rafael Nadal,Novak Djokovic,19,15,34
489521,Rafael Nadal,Novak Djokovic,20,15,35
492618,Novak Djokovic,Rafael Nadal,15,21,36
495438,Novak Djokovic,Rafael Nadal,15,22,37
499268,Novak Djokovic,Rafael Nadal,16,22,38
506888,Rafael Nadal,Novak Djokovic,22,17,39
511000,Rafael Nadal,Novak Djokovic,22,18,40
512682,Novak Djokovic,Rafael Nadal,19,22,41
538586,Rafael Nadal,Novak Djokovic,23,19,42
542701,Novak Djokovic,Rafael Nadal,20,23,43
556795,Rafael Nadal,Novak Djokovic,23,21,44
560684,Novak Djokovic,Rafael Nadal,22,23,45
562832,Rafael Nadal,Novak Djokovic,23,23,46
567199,Rafael Nadal,Novak Djokovic,23,24,47
572948,Rafael Nadal,Novak Djokovic,23,25,48
604887,Novak Djokovic,Rafael Nadal,26,23,49
636588,Novak Djokovic,Rafael Nadal,26,24,50
641572,Rafael Nadal,Novak Djokovic,25,26,51
656597,Novak Djokovic,Rafael Nadal,27,25,52
665465,Novak Djokovic,Rafael Nadal,28,25,53
684158,Rafael Nadal,Novak Djokovic,26,28,54
690723,Novak Djokovic,Rafael Nadal,29,26,55
699692,Novak Djokovic,Rafael Nadal,29,27,56
701196,Rafael Nadal,Novak Djokovic,28,29,57
726153,Novak Djokovic,Rafael Nadal,30,28,58
795946,Novak Djokovic,Rafael Nadal,30,29,59

In [39]:
#test-2
matches_df[
    matches_df["playerA_name"] == "Roger Federer"
][
    [
        "playerA_name",
        "playerA_top20_wins",
        "playerA_top20_losses",
        "playerA_top20_win_pct"
    ]
].tail(10)

,playerA_name,playerA_top20_wins,playerA_top20_losses,playerA_top20_win_pct
696012,Roger Federer,389,166,0.700901
696020,Roger Federer,389,166,0.700901
701087,Roger Federer,389,166,0.700901
701171,Roger Federer,389,166,0.700901
701185,Roger Federer,389,166,0.700901
701819,Roger Federer,389,167,0.699640
702891,Roger Federer,389,167,0.699640
702931,Roger Federer,389,167,0.699640
702951,Roger Federer,389,167,0.699640
702966,Roger Federer,389,167,0.699640

## *ELO Ratings*

In [40]:
#data check-1
matches_df["tourney_level"].unique()

array(['S', 'A', 'G', 'C', 'D', 'M', 'F', '15', '25', 'O'], dtype=object)

In [41]:
#data fix-1
matches_df["tourney_date"] = pd.to_datetime(matches_df["tourney_date"])

In [42]:
#--------------
#Elo Parameters
#--------------
BASE_ELO = 1500.0
BASE_K = 32.0

# Surface blending weight
SURFACE_WEIGHT = 0.70
OVERALL_WEIGHT = 0.30

# Inactivity decay
DECAY_PER_DAY = 0.9995       # ~16% decay after one year


# ----------------------------------
# Tournament importance multipliers
# ----------------------------------
TOURNAMENT_MULTIPLIER = {
    "G": 2.0, #Grand Slam
    "M": 1.8, #ATP Masters 1000
    "A": 1.6, #ATP Tour 
    "C": 1.2, #Challenger

    # Everything else
    "F": 1.0,
    "S": 1.0,
    "D": 1.0,
    "O": 1.0,
    "15": 1.0,
    "25": 1.0,
}

In [43]:
overall_elo = defaultdict(lambda: BASE_ELO)
surface_elo = defaultdict(lambda: None)
matches_played = defaultdict(int)
elo_history = defaultdict(list)
last_match_date = {}
last_match_date_by_surface = {}

In [44]:
import re
def expected_score(rating_a, rating_b):
    """
    Computes the expected probability that player A defeats player B.
    """
    return 1.0 / (1.0 + 10 ** ((rating_b - rating_a) / 400))


def dynamic_k(matches_played):
    """
    Continuous K-factor that decreases as players become
    more established.
    """
    return BASE_K * (60 / (60 + matches_played))



def tournament_multiplier(level):
    """
    Returns the tournament importance multiplier.
    """
    return TOURNAMENT_MULTIPLIER.get(level, 1.0)


def best_of_five_multiplier(best_of):
    """
    Grand Slam men's matches (best-of-5) provide
    stronger evidence than best-of-3 matches.
    """
    if best_of == 5:
        return 1.15

    return 1.0



def margin_multiplier(score_string):
    """
    Computes a multiplier based on the total games won.

    Returns:
        1.0 if the score cannot be parsed.
    """

    if not isinstance(score_string, str):
        return 1.0

    score_string = score_string.upper()

    if "RET" in score_string or "W/O" in score_string:
        return 1.0

    winner_games = 0
    loser_games = 0

    sets = score_string.split()

    for s in sets:
        m = re.match(r"(\d+)-(\d+)", s)
        if m:
            winner_games += int(m.group(1))
            loser_games += int(m.group(2))

    margin = winner_games - loser_games

    if margin <= 0:
        return 1.0

    multiplier = np.log1p(margin)

    # Prevents extremely dominant wins from exploding Elo updates
    return min(multiplier, 2.5)


def apply_overall_inactivity_decay(player, current_date):
    """
    Applies rating decay towards BASE_ELO after
    30 days of inactivity overall.
    """

    if player not in last_match_date:
        return

    days_inactive = (current_date - last_match_date[player]).days

    if days_inactive <= 30:
        return

    decay = DECAY_PER_DAY ** (days_inactive - 30)

    # Overall Elo
    overall_elo[player] = BASE_ELO + (overall_elo[player] - BASE_ELO) * decay


def apply_surface_inactivity_decay(player, surface, current_date):
    """
    Applies rating decay towards BASE_ELO after
    30 days of inactivity on a specific surface.
    """
    key = (player, surface)
    if key not in last_match_date_by_surface:
        return

    days_inactive = (current_date - last_match_date_by_surface[key]).days

    if days_inactive <= 30:
        return

    decay = DECAY_PER_DAY ** (days_inactive - 30)

    # Surface Elo
    if surface_elo[key] is not None:
        surface_elo[key] = BASE_ELO + (surface_elo[key] - BASE_ELO) * decay


def get_surface_rating(player, surface):
    """
    Initializes a player's surface rating using
    their current overall Elo.
    """

    key = (player, surface)
    if surface_elo[key] is None:
        surface_elo[key] = overall_elo[player]

    return surface_elo[key]


def effective_k(matches_played, tourney_level, best_of, score):
    return (
        dynamic_k(matches_played)
        * tournament_multiplier(tourney_level)
        * best_of_five_multiplier(best_of)
        * margin_multiplier(score)
    )

In [45]:
#--------------
#Feature Lists
#--------------

playerA_elo = []
playerB_elo = []
elo_diff = []

playerA_surface_elo = []
playerB_surface_elo = []
surface_elo_diff = []

playerA_blended_elo = []
playerB_blended_elo = []
blended_elo_diff = []

playerA_elo_ratio = []
playerB_elo_ratio = []

playerA_elo_momentum = []
playerB_elo_momentum = []

playerA_elo_volatility = []
playerB_elo_volatility = []


#----------
#Main Loop
#----------
for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id
    surface = row.surface
    current_date = row.tourney_date

    apply_overall_inactivity_decay(playerA, current_date)
    apply_overall_inactivity_decay(playerB, current_date)
    apply_surface_inactivity_decay(playerA, surface, current_date)
    apply_surface_inactivity_decay(playerB, surface, current_date)

    overall_A = overall_elo[playerA]
    overall_B = overall_elo[playerB]

    surface_A = get_surface_rating(playerA, surface)
    surface_B = get_surface_rating(playerB, surface)

    blended_A = SURFACE_WEIGHT*surface_A + OVERALL_WEIGHT*overall_A
    blended_B = SURFACE_WEIGHT*surface_B + OVERALL_WEIGHT*overall_B


    #storing features
    playerA_elo.append(overall_A)
    playerB_elo.append(overall_B)
    elo_diff.append(overall_A - overall_B)

    playerA_surface_elo.append(surface_A)
    playerB_surface_elo.append(surface_B)
    surface_elo_diff.append(surface_A - surface_B)

    playerA_blended_elo.append(blended_A)
    playerB_blended_elo.append(blended_B)
    blended_elo_diff.append(blended_A - blended_B)

    playerA_elo_ratio.append(overall_A / max(overall_B, 1))
    playerB_elo_ratio.append(overall_B / max(overall_A, 1))


    #elo momentum 
    if len(elo_history[playerA]) >= 10:
        playerA_momentum = overall_A - elo_history[playerA][-10]
    else:
        playerA_momentum = 0.0

    if len(elo_history[playerB]) >= 10:
        playerB_momentum = overall_B - elo_history[playerB][-10]
    else:
        playerB_momentum = 0.0
    playerA_elo_momentum.append(playerA_momentum)
    playerB_elo_momentum.append(playerB_momentum)



    #elo volatility
    if len(elo_history[playerA]) >= 20:
        playerA_volatility = np.std(elo_history[playerA][-20:])
    else:
        playerA_volatility = 0.0

    if len(elo_history[playerB]) >= 20:
        playerB_volatility = np.std(elo_history[playerB][-20:])
    else:
        playerB_volatility = 0.0

    playerA_elo_volatility.append(playerA_volatility)
    playerB_elo_volatility.append(playerB_volatility)



    #winner/loser
    if row.playerA_wins == 1:
        winner = playerA
        loser = playerB
        winner_rating = overall_A
        loser_rating = overall_B
        winner_surface = surface_A
        loser_surface = surface_B

    else:
        winner = playerB
        loser = playerA
        winner_rating = overall_B
        loser_rating = overall_A
        winner_surface = surface_B
        loser_surface = surface_A

    #expected scores
    winner_expected = expected_score(winner_rating, loser_rating)
    loser_expected = 1 - winner_expected

    winner_surface_expected = expected_score(winner_surface, loser_surface)
    loser_surface_expected = 1 - winner_surface_expected


    #effective k
    K_winner = (dynamic_k(matches_played[winner]) * tournament_multiplier(row.tourney_level) * best_of_five_multiplier(row.best_of) 
         * margin_multiplier(row.score))
    K_loser = (dynamic_k(matches_played[loser]) * tournament_multiplier(row.tourney_level) * best_of_five_multiplier(row.best_of) 
         * margin_multiplier(row.score))
    

    #updating elo
    overall_elo[winner] += K_winner * (1 - winner_expected)
    overall_elo[loser] += K_loser * (0 - loser_expected)

    surface_elo[(winner, surface)] += K_winner * (1 - winner_surface_expected)
    surface_elo[(loser, surface)] += K_loser * (0 - loser_surface_expected)

    elo_history[playerA].append(overall_elo[playerA])
    elo_history[playerB].append(overall_elo[playerB])


    matches_played[playerA] += 1
    matches_played[playerB] += 1

    last_match_date[playerA] = current_date
    last_match_date[playerB] = current_date
    last_match_date_by_surface[(playerA, surface)] = current_date
    last_match_date_by_surface[(playerB, surface)] = current_date

In [46]:
# ---------------
# Storing Features
# ---------------
matches_df["playerA_elo"] = playerA_elo
matches_df["playerB_elo"] = playerB_elo
matches_df["elo_diff"] = elo_diff

matches_df["playerA_surface_elo"] = playerA_surface_elo
matches_df["playerB_surface_elo"] = playerB_surface_elo
matches_df["surface_elo_diff"] = surface_elo_diff

matches_df["playerA_blended_elo"] = playerA_blended_elo #new
matches_df["playerB_blended_elo"] = playerB_blended_elo #new
matches_df["blended_elo_diff"] = blended_elo_diff #new

matches_df["elo_ratio"] = playerA_elo_ratio #new

matches_df["playerA_elo_momentum"] = playerA_elo_momentum #new 
matches_df["playerB_elo_momentum"] = playerB_elo_momentum #new 

matches_df["playerA_elo_volatility"] = playerA_elo_volatility #new 
matches_df["playerB_elo_volatility"] = playerB_elo_volatility #new

matches_df['blended_elo_ratio'] = matches_df['playerA_blended_elo']/matches_df['playerB_blended_elo'] #new
matches_df['surface_elo_ratio'] = matches_df['playerA_surface_elo']/matches_df['playerB_surface_elo'] #new

In [47]:
#old elo computation


# from collections import defaultdict
# import numpy as np

# #storage dictioneries
# elo_rating = defaultdict(lambda: 1500.0) #key player
# surface_elo_rating = defaultdict(lambda: 1500.0) #key (player, surface)

# #feature lists
# playerA_elo = []
# playerB_elo = []
# elo_diff = []

# playerA_surface_elo = []
# playerB_surface_elo = []
# surface_elo_diff = []

# #function to calculate expected score after match ends
# def expected_score(rating_a, rating_b):
#     return 1/(1 + 10 ** ((rating_b - rating_a) / 400))

# K = 32 #can be experimented with


# #main loop
# for row in matches_df.itertuples():
#     playerA = row.playerA_id
#     playerB = row.playerB_id
#     winner = row.playerA_id if row.playerA_wins ==1 else row.playerB_id
#     loser = row.playerB_id if row.playerA_wins == 1 else row.playerA_id
#     surface = row.surface

#     playA_elo = elo_rating[playerA]
#     playB_elo = elo_rating[playerB]

#     playerA_elo.append(playA_elo)
#     playerB_elo.append(playB_elo)
#     elo_diff.append(playA_elo - playB_elo)


#     playA_surface_elo = surface_elo_rating[(playerA, surface)]
#     playB_surface_elo = surface_elo_rating[(playerB, surface)]

#     playerA_surface_elo.append(playA_surface_elo)
#     playerB_surface_elo.append(playB_surface_elo)
#     surface_elo_diff.append(playA_surface_elo - playB_surface_elo)


#     #updating elo rating after match
#     expected_playerA = expected_score(playA_elo, playB_elo)
#     expected_playerB = expected_score(playB_elo, playA_elo)

#     elo_rating[playerA] = (playA_elo + K*(1 - expected_playerA)) if winner==playerA else (playA_elo + K*(0 - expected_playerA))
#     elo_rating[playerB] = (playB_elo + K*(1 - expected_playerB)) if winner==playerB else (playB_elo + K*(0 - expected_playerB))


#     #updating surface elo ratings after match
#     surface_expected_playerA = expected_score(playA_surface_elo, playB_surface_elo)
#     surface_Expected_playerB = expected_score(playB_surface_elo, playA_surface_elo)

#     surface_elo_rating[(playerA, surface)] = ((playA_surface_elo + K*(1 - surface_expected_playerA)) if winner == playerA
#                                               else (playA_surface_elo + K*(0 - surface_expected_playerA)))
#     surface_elo_rating[(playerB, surface)] = ((playB_surface_elo + K*(1 - surface_Expected_playerB)) if winner == playerB
#                                               else (playB_surface_elo + K*(0 - surface_Expected_playerB)))
    

# matches_df["playerA_elo"] = playerA_elo
# matches_df["playerB_elo"] = playerB_elo
# matches_df['elo_diff'] = elo_diff

# matches_df["playerA_surface_elo"] = playerA_surface_elo
# matches_df["playerB_surface_elo"] = playerB_surface_elo
# matches_df["surface_elo_diff"] = surface_elo_diff

In [48]:
#test-1
matches_df[
    ["playerA_elo",
     "playerB_elo",
     "playerA_surface_elo",
     "playerB_surface_elo"]
].describe()

         playerA_elo    playerB_elo  playerA_surface_elo  playerB_surface_elo
count  855141.000000  855141.000000        855141.000000        855141.000000
mean     1636.781298    1636.575996          1565.462905          1565.271209
std       173.621516     173.653399           112.837970           112.906853
min      1147.030234    1145.156568          1159.889916          1157.890261
25%      1500.000000    1500.000000          1482.893712          1482.475523
50%      1627.779723    1627.722392          1564.139747          1563.828055
75%      1744.490120    1744.380317          1643.588509          1643.448488
max      2484.402227    2486.179369          2150.249617          2152.181600

In [49]:
#test-2
matches_df[
    [
        "playerA_name",
        "playerB_name",
        "playerA_elo",
        "playerB_elo"
    ]
].head(10)

           playerA_name        playerB_name  playerA_elo  playerB_elo
0  Vladimir Gabrichidze    Emilio Marturano       1500.0       1500.0
1      Goran Mihajlovic         Danilo Pila       1500.0       1500.0
2      York Heidenreich        Mark Joachim       1500.0       1500.0
3              Eno Polo       Eugenio Rossi       1500.0       1500.0
4  Srinivasan Vasudevan         Jake Martyn       1500.0       1500.0
5           Asif Ismail  Mohesh Koregaonkar       1500.0       1500.0
6       Sebastien Hette       Mark Ferreira       1500.0       1500.0
7       Manuel Gasbarri          Nick Adams       1500.0       1500.0
8        Enrico Piperno        Rohit Rajpal       1500.0       1500.0
9    David Kvaratshelia      Massimo Valeri       1500.0       1500.0

In [50]:
#test-3
matches_df[
    matches_df["playerA_name"] == "Roger Federer"
][
    [
        "playerA_name",
        "playerA_elo"
    ]
].tail(20)

         playerA_name  playerA_elo
679751  Roger Federer  2259.527430
680445  Roger Federer  2258.497492
680461  Roger Federer  2258.949649
680469  Roger Federer  2259.490134
680475  Roger Federer  2261.062327
682770  Roger Federer  2262.146951
685041  Roger Federer  2247.470813
685061  Roger Federer  2248.845129
685076  Roger Federer  2250.450724
685079  Roger Federer  2250.800503
696012  Roger Federer  2118.379152
696020  Roger Federer  2118.883570
701087  Roger Federer  2102.499269
701171  Roger Federer  2105.267185
701185  Roger Federer  2106.132293
701819  Roger Federer  2104.764890
702891  Roger Federer  2103.222461
702931  Roger Federer  2103.843934
702951  Roger Federer  2105.530410
702966  Roger Federer  2108.981983

In [51]:
#test-4
print("Overall Elo Range:")
print(matches_df["playerA_elo"].min(), matches_df["playerA_elo"].max())

print("\nSurface Elo Range:")
print(matches_df["playerA_surface_elo"].min(), matches_df["playerA_surface_elo"].max())

print("\nBlended Elo Range:")
print(matches_df["playerA_blended_elo"].min(), matches_df["playerA_blended_elo"].max())

Overall Elo Range:
1147.030234192891 2484.402226861422

Surface Elo Range:
1159.8899160206022 2150.2496168573043

Blended Elo Range:
1160.1168460439383 2223.294834365014

In [52]:
#test-5
print("\nMissing Values:")
print(matches_df[
    [
        "playerA_elo",
        "playerA_surface_elo",
        "playerA_blended_elo",
        "playerA_elo_momentum",
        "playerA_elo_volatility",
    ]
].isna().sum())

Missing Values:
playerA_elo               0
playerA_surface_elo       0
playerA_blended_elo       0
playerA_elo_momentum      0
playerA_elo_volatility    0
dtype: int64

In [53]:
#test-6
print("\nExample Features:")
print(
    matches_df[
        [
            "playerA_elo",
            "playerA_surface_elo",
            "playerA_blended_elo",
            "playerA_elo_momentum",
            "playerA_elo_volatility",
        ]
    ].head()
)

Example Features:
   playerA_elo  playerA_surface_elo  playerA_blended_elo  \
0       1500.0               1500.0               1500.0
1       1500.0               1500.0               1500.0
2       1500.0               1500.0               1500.0
3       1500.0               1500.0               1500.0
4       1500.0               1500.0               1500.0

   playerA_elo_momentum  playerA_elo_volatility
0                   0.0                     0.0
1                   0.0                     0.0
2                   0.0                     0.0
3                   0.0                     0.0
4                   0.0                     0.0

## *Recent Form*

In [54]:
from collections import defaultdict

career_record = defaultdict(lambda: [0, 0])      # player -> [wins, losses]
surface_record = defaultdict(lambda: [0, 0])     # (player, surface) -> [wins, losses]



# FEATURE LISTS
playerA_career_wins = []
playerA_career_losses = []
playerA_career_pct = []
playerB_career_wins = []
playerB_career_losses = []
playerB_career_pct = []

playerA_surface_career_wins = []
playerA_surface_career_losses = []
playerA_surface_career_pct = []
playerB_surface_career_wins = []
playerB_surface_career_losses = []
playerB_surface_career_pct = []


# MAIN LOOP
for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id
    surface = row.surface

    winner = playerA if row.playerA_wins == 1 else playerB
    loser  = playerB if row.playerA_wins == 1 else playerA


    # PLAYER A CAREER
    wins, losses = career_record[playerA]

    playerA_career_wins.append(wins)
    playerA_career_losses.append(losses)

    if wins + losses > 0:
        playerA_career_pct.append(wins / (wins + losses))
    else:
        playerA_career_pct.append(0.5)


    # PLAYER B CAREER
    wins, losses = career_record[playerB]

    playerB_career_wins.append(wins)
    playerB_career_losses.append(losses)

    if wins + losses > 0:
        playerB_career_pct.append(wins / (wins + losses))
    else:
        playerB_career_pct.append(0.5)


    # PLAYER A SURFACE CAREER
    wins, losses = surface_record[(playerA, surface)]

    playerA_surface_career_wins.append(wins)
    playerA_surface_career_losses.append(losses)

    if wins + losses > 0:
        playerA_surface_career_pct.append(wins / (wins + losses))
    else:
        playerA_surface_career_pct.append(0.5)


    # PLAYER B SURFACE CAREER
    wins, losses = surface_record[(playerB, surface)]

    playerB_surface_career_wins.append(wins)
    playerB_surface_career_losses.append(losses)

    if wins + losses > 0:
        playerB_surface_career_pct.append(wins / (wins + losses))
    else:
        playerB_surface_career_pct.append(0.5)


    # UPDATE RECORDS
    career_record[winner][0] += 1
    career_record[loser][1] += 1

    surface_record[(winner, surface)][0] += 1
    surface_record[(loser, surface)][1] += 1



# ATTACH FEATURES
matches_df["playerA_career_wins"] = playerA_career_wins
matches_df["playerA_career_losses"] = playerA_career_losses
matches_df['playerA_career_matches'] = matches_df['playerA_career_wins'] + matches_df['playerA_career_losses'] #new
matches_df["playerA_career_pct"] = playerA_career_pct
matches_df["playerB_career_wins"] = playerB_career_wins
matches_df["playerB_career_losses"] = playerB_career_losses
matches_df['playerB_career_matches'] = matches_df['playerB_career_wins'] + matches_df['playerB_career_losses'] #new
matches_df["playerB_career_pct"] = playerB_career_pct

matches_df["playerA_surface_career_wins"] = playerA_surface_career_wins
matches_df["playerA_surface_career_losses"] = playerA_surface_career_losses
matches_df['playerA_surface_career_matches'] = matches_df["playerA_surface_career_wins"] + matches_df["playerA_surface_career_losses"] #new
matches_df["playerA_surface_career_pct"] = playerA_surface_career_pct
matches_df["playerB_surface_career_wins"] = playerB_surface_career_wins
matches_df["playerB_surface_career_losses"] = playerB_surface_career_losses
matches_df['playerB_surface_career_matches'] = matches_df["playerB_surface_career_wins"] + matches_df["playerB_surface_career_losses"] #new
matches_df["playerB_surface_career_pct"] = playerB_surface_career_pct

In [55]:
#test-1
matches_df[matches_df["playerB_name"] == "Roger Federer"][[
                                                    "playerB_name",
                                                    "playerB_career_wins",
                                                    "playerB_career_losses",
                                                    "playerB_career_pct"]].tail(10)

,playerB_name,playerB_career_wins,playerB_career_losses,playerB_career_pct
680473,Roger Federer,1287,290,0.816107
682773,Roger Federer,1290,290,0.816456
682774,Roger Federer,1290,291,0.815939
682776,Roger Federer,1291,291,0.816056
685001,Roger Federer,1291,292,0.815540
685071,Roger Federer,1294,292,0.815889
699810,Roger Federer,1297,294,0.815211
701143,Roger Federer,1298,295,0.814815
701829,Roger Federer,1301,296,0.814652
702961,Roger Federer,1304,297,0.814491

In [56]:
from collections import defaultdict, deque

last10_record = defaultdict(lambda: deque(maxlen=10))
last25_record = defaultdict(lambda: deque(maxlen=25))
surface10_record = defaultdict(lambda: deque(maxlen=10))
surface25_record = defaultdict(lambda: deque(maxlen=25))



# FEATURE LISTS
playerA_last10_wins = []
playerA_last10_matches = []
playerA_last10_pct = []

playerB_last10_wins = []
playerB_last10_matches = []
playerB_last10_pct = []

playerA_last25_wins = []
playerA_last25_matches = []
playerA_last25_pct = []

playerB_last25_wins = []
playerB_last25_matches = []
playerB_last25_pct = []


playerA_surface10_wins = []
playerA_surface10_matches = []
playerA_surface10_pct = []

playerB_surface10_wins = []
playerB_surface10_matches = []
playerB_surface10_pct = []


playerA_surface25_wins = []
playerA_surface25_matches = []
playerA_surface25_pct = []

playerB_surface25_wins = []
playerB_surface25_matches = []
playerB_surface25_pct = []



# MAIN LOOP
for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id
    surface = row.surface

    winner = playerA if row.playerA_wins == 1 else playerB
    loser  = playerB if row.playerA_wins == 1 else playerA


    
    # PLAYER A LAST 10
    history = last10_record[playerA]

    wins = sum(history)
    matches = len(history)

    playerA_last10_wins.append(wins)
    playerA_last10_matches.append(matches)

    playerA_last10_pct.append(wins / matches if matches > 0 else 0.5)



    # PLAYER B LAST 10
    history = last10_record[playerB]

    wins = sum(history)
    matches = len(history)

    playerB_last10_wins.append(wins)
    playerB_last10_matches.append(matches)

    playerB_last10_pct.append(wins / matches if matches > 0 else 0.5)


    
    # PLAYER A LAST 25
    history = last25_record[playerA]

    wins = sum(history)
    matches = len(history)

    playerA_last25_wins.append(wins)
    playerA_last25_matches.append(matches)

    playerA_last25_pct.append(wins / matches if matches > 0 else 0.5)


   
    # PLAYER B LAST 25
    history = last25_record[playerB]

    wins = sum(history)
    matches = len(history)

    playerB_last25_wins.append(wins)
    playerB_last25_matches.append(matches)

    playerB_last25_pct.append(wins / matches if matches > 0 else 0.5)


    
    # PLAYER A SURFACE LAST 10
    history = surface10_record[(playerA, surface)]

    wins = sum(history)
    matches = len(history)

    playerA_surface10_wins.append(wins)
    playerA_surface10_matches.append(matches)

    playerA_surface10_pct.append(wins / matches if matches > 0 else 0.5)



    # PLAYER B SURFACE LAST 10
    history = surface10_record[(playerB, surface)]

    wins = sum(history)
    matches = len(history)

    playerB_surface10_wins.append(wins)
    playerB_surface10_matches.append(matches)

    playerB_surface10_pct.append(wins / matches if matches > 0 else 0.5)


    
    # PLAYER A SURFACE LAST 25
    history = surface25_record[(playerA, surface)]

    wins = sum(history)
    matches = len(history)

    playerA_surface25_wins.append(wins)
    playerA_surface25_matches.append(matches)

    playerA_surface25_pct.append(wins / matches if matches > 0 else 0.5)


    
    # PLAYER B SURFACE LAST 25
    history = surface25_record[(playerB, surface)]

    wins = sum(history)
    matches = len(history)

    playerB_surface25_wins.append(wins)
    playerB_surface25_matches.append(matches)

    playerB_surface25_pct.append(wins / matches if matches > 0 else 0.5)


    # =====================
    # UPDATE HISTORIES
    # =====================

    last10_record[winner].append(1)
    last25_record[winner].append(1)

    last10_record[loser].append(0)
    last25_record[loser].append(0)

    surface10_record[(winner, surface)].append(1)
    surface25_record[(winner, surface)].append(1)

    surface10_record[(loser, surface)].append(0)
    surface25_record[(loser, surface)].append(0)



# ATTACH FEATURES
matches_df["playerA_last10_wins"] = playerA_last10_wins
matches_df["playerA_last10_matches"] = playerA_last10_matches
matches_df['playerA_last10_losses'] = matches_df["playerA_last10_matches"] - matches_df["playerA_last10_wins"] #new
matches_df["playerA_last10_pct"] = playerA_last10_pct

matches_df["playerB_last10_wins"] = playerB_last10_wins
matches_df["playerB_last10_matches"] = playerB_last10_matches
matches_df['playerB_last10_losses'] = matches_df["playerB_last10_matches"] - matches_df["playerB_last10_wins"] #new
matches_df["playerB_last10_pct"] = playerB_last10_pct

matches_df["playerA_last25_wins"] = playerA_last25_wins
matches_df["playerA_last25_matches"] = playerA_last25_matches
matches_df['playerA_last25_losses'] = matches_df["playerA_last25_matches"] - matches_df["playerA_last25_wins"] #new
matches_df["playerA_last25_pct"] = playerA_last25_pct

matches_df["playerB_last25_wins"] = playerB_last25_wins
matches_df["playerB_last25_matches"] = playerB_last25_matches
matches_df['playerB_last25_losses'] = matches_df["playerB_last25_matches"] - matches_df["playerB_last25_wins"] #new
matches_df["playerB_last25_pct"] = playerB_last25_pct

matches_df["playerA_surface10_wins"] = playerA_surface10_wins
matches_df["playerA_surface10_matches"] = playerA_surface10_matches
matches_df['playerA_surface10_losses'] = matches_df["playerA_surface10_matches"] - matches_df["playerA_surface10_wins"] #new
matches_df["playerA_surface10_pct"] = playerA_surface10_pct

matches_df["playerB_surface10_wins"] = playerB_surface10_wins
matches_df["playerB_surface10_matches"] = playerB_surface10_matches
matches_df['playerB_surface10_losses'] = matches_df["playerB_surface10_matches"] - matches_df["playerB_surface10_wins"] #new
matches_df["playerB_surface10_pct"] = playerB_surface10_pct

matches_df["playerA_surface25_wins"] = playerA_surface25_wins
matches_df["playerA_surface25_matches"] = playerA_surface25_matches
matches_df['playerA_surface25_losses'] = matches_df["playerA_surface25_matches"] - matches_df["playerA_surface25_wins"] #new
matches_df["playerA_surface25_pct"] = playerA_surface25_pct

matches_df["playerB_surface25_wins"] = playerB_surface25_wins
matches_df["playerB_surface25_matches"] = playerB_surface25_matches
matches_df['playerB_surface25_losses'] = matches_df["playerB_surface25_matches"] - matches_df["playerB_surface25_wins"] #new
matches_df["playerB_surface25_pct"] = playerB_surface25_pct

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\4004019087.py:217: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_surface25_losses'] = matches_df["playerB_surface25_matches"] - matches_df["playerB_surface25_wins"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\4004019087.py:218: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_surface25_pct"] = playerB_surface25_pct

In [57]:
#test-2
matches_df[["playerA_name", "playerA_last25_matches", "playerA_last25_pct"]].tail(20)

           playerA_name  playerA_last25_matches  playerA_last25_pct
855174    Nicolas Mejia                      25                0.60
855175    Edas Butvilas                      25                0.60
855176     Andre Ilagan                      25                0.64
855177   Murphy Cassone                      25                0.44
855178     Yuta Shimizu                      25                0.52
855179    Andres Martin                      25                0.36
855180    Landon Ardila                       4                0.25
855181       Liam Draxl                      25                0.56
855182     Braden Shick                      25                0.64
855183     Henry Searle                      25                0.84
855184  Blaise Bicknell                      25                0.72
855185     Andre Ilagan                      25                0.68
855186   Murphy Cassone                      25                0.44
855187      Timo Legout                      25                0.68
855188       Liam Draxl                      25                0.56
855189     Henry Searle                      25                0.88
855190     Yuta Shimizu                      25                0.56
855191      Adam Walton                      25                0.64
855192      Karl Poling                      25                0.48
855193     Andre Ilagan                      25                0.68

In [58]:
#check-1
type(matches_df["tourney_date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [59]:
#fix-1
matches_df["tourney_date"] = pd.to_datetime(matches_df["tourney_date"])

In [60]:
from collections import defaultdict, deque
import pandas as pd

history_52w = defaultdict(deque)


# FEATURE LISTS
playerA_52w_wins = []
playerA_52w_matches = []
playerA_52w_pct = []

playerB_52w_wins = []
playerB_52w_matches = []
playerB_52w_pct = []



# MAIN LOOP
for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id

    current_date = row.tourney_date

    winner = playerA if row.playerA_wins == 1 else playerB
    loser  = playerB if row.playerA_wins == 1 else playerA

    cutoff_date = current_date - pd.Timedelta(days=364)


    
    # PLAYER A
    history = history_52w[playerA]

    while history and history[0][0] < cutoff_date:
        history.popleft()

    wins = sum(result for _, result in history)
    matches = len(history)

    playerA_52w_wins.append(wins)
    playerA_52w_matches.append(matches)

    if matches > 0:
        playerA_52w_pct.append(wins / matches)
    else:
        playerA_52w_pct.append(0.5)



    # PLAYER B
    history = history_52w[playerB]

    while history and history[0][0] < cutoff_date:
        history.popleft()

    wins = sum(result for _, result in history)
    matches = len(history)

    playerB_52w_wins.append(wins)
    playerB_52w_matches.append(matches)

    if matches > 0:
        playerB_52w_pct.append(wins / matches)
    else:
        playerB_52w_pct.append(0.5)



    # UPDATE HISTORIES
    history_52w[winner].append((current_date, 1))
    history_52w[loser].append((current_date, 0))



# ATTACH FEATURES
matches_df["playerA_52w_wins"] = playerA_52w_wins
matches_df["playerA_52w_matches"] = playerA_52w_matches
matches_df['playerA_52w_losses'] = matches_df["playerA_52w_matches"] - matches_df["playerA_52w_wins"] #new
matches_df["playerA_52w_pct"] = playerA_52w_pct

matches_df["playerB_52w_wins"] = playerB_52w_wins
matches_df["playerB_52w_matches"] = playerB_52w_matches
matches_df['playerB_52w_losses'] = matches_df["playerB_52w_matches"] - matches_df["playerB_52w_wins"] #new
matches_df["playerB_52w_pct"] = playerB_52w_pct

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_52w_wins"] = playerA_52w_wins
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_52w_matches"] = playerA_52w_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_52w_losses'] = matches_df["playerA_52w_matches"] - matches_df["playerA_52w_wins"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:80: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_52w_pct"] = playerA_52w_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:82: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_52w_wins"] = playerB_52w_wins
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_52w_matches"] = playerB_52w_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:84: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_52w_losses'] = matches_df["playerB_52w_matches"] - matches_df["playerB_52w_wins"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3416356303.py:85: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_52w_pct"] = playerB_52w_pct

In [61]:
#test-3
matches_df[["tourney_date", "playerA_52w_matches", "playerA_52w_pct"]].tail(15)

       tourney_date  playerA_52w_matches  playerA_52w_pct
855179   2026-06-01                   59         0.457627
855180   2026-06-01                    1         1.000000
855181   2026-06-01                   66         0.590909
855182   2026-06-01                   69         0.695652
855183   2026-06-01                   76         0.684211
855184   2026-06-01                   64         0.640625
855185   2026-06-01                   78         0.564103
855186   2026-06-01                   65         0.523077
855187   2026-06-01                   13         0.538462
855188   2026-06-01                   67         0.597015
855189   2026-06-01                   77         0.688312
855190   2026-06-01                   52         0.519231
855191   2026-06-01                   69         0.478261
855192   2026-06-01                   60         0.433333
855193   2026-06-01                   81         0.580247

In [62]:
#test-4
matches_df["playerA_52w_matches"].max()

132

In [63]:
#test-5
matches_df[matches_df["playerA_name"] == "Roger Federer"][["playerA_name", "playerA_52w_matches", "playerA_52w_pct"]].head(10)

         playerA_name  playerA_52w_matches  playerA_52w_pct
100771  Roger Federer                    0         0.500000
116943  Roger Federer                    3         0.666667
116946  Roger Federer                    4         0.750000
116965  Roger Federer                    6         0.666667
116993  Roger Federer                    7         0.571429
116998  Roger Federer                    8         0.625000
117011  Roger Federer                    9         0.555556
120431  Roger Federer                   15         0.533333
120462  Roger Federer                   18         0.555556
139371  Roger Federer                    9         0.333333

## *Serve Statistics*

In [64]:
from collections import defaultdict

serve_stats = defaultdict(lambda: {
    "ace": 0,
    "df": 0,
    "svpt": 0,
    "first_in": 0,
    "first_won": 0,
    "second_won": 0,
    "matches": 0
})


playerA_ace_pct = []
playerA_df_pct = []
playerA_1stIn_pct = []
playerA_1stWon_pct = []
playerA_2ndWon_pct = []
playerA_career_p = []

playerB_ace_pct = []
playerB_df_pct = []
playerB_1stIn_pct = []
playerB_1stWon_pct = []
playerB_2ndWon_pct = []
playerB_career_p = []

playerA_serve_matches = []
playerB_serve_matches = []


for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id

    playerA_stats = serve_stats[playerA]
    playerB_stats = serve_stats[playerB]

    playerA_serve_matches.append(playerA_stats["matches"])
    playerB_serve_matches.append(playerB_stats["matches"])

    
    # PLAYER A FEATURES
    if playerA_stats["svpt"] > 0:
        playerA_ace_pct.append(playerA_stats["ace"] / playerA_stats["svpt"])
        playerA_df_pct.append(playerA_stats["df"] / playerA_stats["svpt"])
        playerA_1stIn_pct.append(playerA_stats["first_in"] / playerA_stats["svpt"])
        playerA_career_p.append((playerA_stats["first_won"] + playerA_stats["second_won"]) / playerA_stats["svpt"])

        if playerA_stats["first_in"] > 0:
            playerA_1stWon_pct.append(playerA_stats["first_won"] / playerA_stats["first_in"])
        else:
            playerA_1stWon_pct.append(np.nan)

        second_attempts = (playerA_stats["svpt"] - playerA_stats["first_in"])
        if second_attempts > 0:
            playerA_2ndWon_pct.append(playerA_stats["second_won"] / second_attempts)
        else:
            playerA_2ndWon_pct.append(np.nan)

    else:
        playerA_ace_pct.append(np.nan)
        playerA_df_pct.append(np.nan)
        playerA_1stIn_pct.append(np.nan)
        playerA_career_p.append(np.nan)

        playerA_1stWon_pct.append(np.nan)
        playerA_2ndWon_pct.append(np.nan)


    
    # PLAYER B FEATURES
    if playerB_stats["svpt"] > 0:
        playerB_ace_pct.append(playerB_stats["ace"] / playerB_stats["svpt"])
        playerB_df_pct.append(playerB_stats["df"] / playerB_stats["svpt"])
        playerB_1stIn_pct.append(playerB_stats["first_in"] / playerB_stats["svpt"])
        playerB_career_p.append((playerB_stats["first_won"] + playerB_stats["second_won"]) / playerB_stats["svpt"])

        if playerB_stats["first_in"] > 0:
            playerB_1stWon_pct.append(playerB_stats["first_won"] / playerB_stats["first_in"])
        else:
            playerB_1stWon_pct.append(np.nan)

        second_attempts = (playerB_stats["svpt"] - playerB_stats["first_in"])
        if second_attempts > 0:
            playerB_2ndWon_pct.append(playerB_stats["second_won"] / second_attempts)
        else:
            playerB_2ndWon_pct.append(np.nan)

    else:
        playerB_ace_pct.append(np.nan)
        playerB_df_pct.append(np.nan)
        playerB_1stIn_pct.append(np.nan)
        playerB_career_p.append(np.nan)

        playerB_1stWon_pct.append(np.nan)
        playerB_2ndWon_pct.append(np.nan)


    # -------------------------
    # UPDATES
    # -------------------------

    if pd.notna(row.playerA_svpt):
        serve_stats[playerA]["ace"] += row.playerA_ace
        serve_stats[playerA]["df"] += row.playerA_df
        serve_stats[playerA]["svpt"] += row.playerA_svpt

        serve_stats[playerA]["first_in"] += row.playerA_1stIn
        serve_stats[playerA]["first_won"] += row.playerA_1stWon
        serve_stats[playerA]["second_won"] += row.playerA_2ndWon

        serve_stats[playerA]["matches"] += 1


        serve_stats[playerB]["ace"] += row.playerB_ace
        serve_stats[playerB]["df"] += row.playerB_df
        serve_stats[playerB]["svpt"] += row.playerB_svpt

        serve_stats[playerB]["first_in"] += row.playerB_1stIn
        serve_stats[playerB]["first_won"] += row.playerB_1stWon
        serve_stats[playerB]["second_won"] += row.playerB_2ndWon

        serve_stats[playerB]["matches"] += 1


matches_df["playerA_ace_pct"] = playerA_ace_pct
matches_df["playerA_df_pct"] = playerA_df_pct
matches_df["playerA_1stIn_pct"] = playerA_1stIn_pct
matches_df["playerA_1stWon_pct"] = playerA_1stWon_pct
matches_df["playerA_2ndWon_pct"] = playerA_2ndWon_pct
matches_df["playerA_career_p"] = playerA_career_p

matches_df["playerB_ace_pct"] = playerB_ace_pct
matches_df["playerB_df_pct"] = playerB_df_pct
matches_df["playerB_1stIn_pct"] = playerB_1stIn_pct
matches_df["playerB_1stWon_pct"] = playerB_1stWon_pct
matches_df["playerB_2ndWon_pct"] = playerB_2ndWon_pct
matches_df["playerB_career_p"] = playerB_career_p

matches_df["playerA_serve_matches"] = playerA_serve_matches
matches_df["playerB_serve_matches"] = playerB_serve_matches

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:127: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_ace_pct"] = playerA_ace_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:128: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_df_pct"] = playerA_df_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:129: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_1stIn_pct"] = playerA_1stIn_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:130: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_1stWon_pct"] = playerA_1stWon_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:131: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_2ndWon_pct"] = playerA_2ndWon_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:132: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_career_p"] = playerA_career_p
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:134: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_ace_pct"] = playerB_ace_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_df_pct"] = playerB_df_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:136: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_1stIn_pct"] = playerB_1stIn_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:137: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_1stWon_pct"] = playerB_1stWon_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:138: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_2ndWon_pct"] = playerB_2ndWon_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:139: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_career_p"] = playerB_career_p
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:141: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_serve_matches"] = playerA_serve_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\694805532.py:142: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_serve_matches"] = playerB_serve_matches

In [65]:
#test-1
matches_df[["playerA_name", "playerA_serve_matches", "playerA_career_p"]].tail(15)

           playerA_name  playerA_serve_matches  playerA_career_p
855179    Andres Martin                    143          0.610996
855180    Landon Ardila                      1          0.687500
855181       Liam Draxl                    194          0.615993
855182     Braden Shick                     72          0.641896
855183     Henry Searle                    121          0.651076
855184  Blaise Bicknell                    136          0.619715
855185     Andre Ilagan                    144          0.621470
855186   Murphy Cassone                    149          0.640489
855187      Timo Legout                     28          0.567141
855188       Liam Draxl                    195          0.615995
855189     Henry Searle                    122          0.651488
855190     Yuta Shimizu                    242          0.606943
855191      Adam Walton                    266          0.650039
855192      Karl Poling                    103          0.601735
855193     Andre Ilagan                    147          0.621562

In [66]:
from collections import defaultdict
import numpy as np
import pandas as pd

matchup_p_record = defaultdict(
    lambda: {
        "p1_won": 0,
        "p1_played": 0,
        "p2_won": 0,
        "p2_played": 0
    }
)

playerA_matchup_p = []
playerB_matchup_p = []

playerA_matchup_service_points = []
playerB_matchup_service_points = []


for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id

    pair = tuple(sorted((playerA, playerB)))

    record = matchup_p_record[pair]

    
    # PLAYER A / PLAYER B HISTORICAL MATCHUP P
    if pair[0] == playerA:
        A_won = record["p1_won"]
        A_played = record["p1_played"]

        B_won = record["p2_won"]
        B_played = record["p2_played"]

    else:
        A_won = record["p2_won"]
        A_played = record["p2_played"]

        B_won = record["p1_won"]
        B_played = record["p1_played"]


   
    # Player A features
    if A_played > 0:
        playerA_matchup_p.append(A_won / A_played)
    else:
        playerA_matchup_p.append(np.nan)

    playerA_matchup_service_points.append(A_played)


    
    # Player B features
    if B_played > 0:
        playerB_matchup_p.append(B_won / B_played)
    else:
        playerB_matchup_p.append(np.nan)

    playerB_matchup_service_points.append(B_played)


    # UPDATE HISTORY
    if (pd.notna(row.playerA_svpt) and pd.notna(row.playerB_svpt)):
        playerA_points_won = (row.playerA_1stWon + row.playerA_2ndWon)
        playerB_points_won = (row.playerB_1stWon + row.playerB_2ndWon)

        if pair[0] == playerA:
            record["p1_won"] += playerA_points_won
            record["p1_played"] += row.playerA_svpt

            record["p2_won"] += playerB_points_won
            record["p2_played"] += row.playerB_svpt

        else:
            record["p2_won"] += playerA_points_won
            record["p2_played"] += row.playerA_svpt

            record["p1_won"] += playerB_points_won
            record["p1_played"] += row.playerB_svpt



# ATTACH FEATURES
matches_df["playerA_matchup_p"] = playerA_matchup_p #label
matches_df["playerB_matchup_p"] = playerB_matchup_p #label

matches_df["playerA_matchup_service_points"] = (playerA_matchup_service_points)
matches_df["playerB_matchup_service_points"] = (playerB_matchup_service_points)

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\688356015.py:88: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_matchup_p"] = playerA_matchup_p #label
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\688356015.py:89: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_matchup_p"] = playerB_matchup_p #label
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\688356015.py:91: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_matchup_service_points"] = (playerA_matchup_service_points)
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\688356015.py:92: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_matchup_service_points"] = (playerB_matchup_service_points)

In [67]:
#test-2
test = matches_df[
    (
        (matches_df["playerA_name"] == "Roger Federer")
        & (matches_df["playerB_name"] == "Rafael Nadal")
    )
    |
    (
        (matches_df["playerA_name"] == "Rafael Nadal")
        & (matches_df["playerB_name"] == "Roger Federer")
    )
]

test[
    [
        "playerA_name",
        "playerB_name",
        "playerA_matchup_p",
        "playerB_matchup_p",
        "playerA_matchup_service_points",
        "playerB_matchup_service_points"
    ]
].tail(20)

,playerA_name,playerB_name,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points
417457,Roger Federer,Rafael Nadal,0.620978,0.630340,2269.0,2294.0
423233,Roger Federer,Rafael Nadal,0.625804,0.630932,2333.0,2360.0
425609,Rafael Nadal,Roger Federer,0.633680,0.623588,2405.0,2391.0
427621,Rafael Nadal,Roger Federer,0.634078,0.620690,2506.0,2494.0
443528,Roger Federer,Rafael Nadal,0.618702,0.632868,2620.0,2653.0
445065,Rafael Nadal,Roger Federer,0.630290,0.621429,2694.0,2660.0
448475,Rafael Nadal,Roger Federer,0.632451,0.621467,2835.0,2795.0
475884,Rafael Nadal,Roger Federer,0.630578,0.621887,2891.0,2851.0
480840,Roger Federer,Rafael Nadal,0.618934,0.631668,2926.0,2943.0
490161,Rafael Nadal,Roger Federer,0.632831,0.615979,2985.0,2979.0
499267,Rafael Nadal,Roger Federer,0.634946,0.617332,3079.0,3081.0
501965,Roger Federer,Rafael Nadal,0.616879,0.636683,3140.0,3135.0
558872,Roger Federer,Rafael Nadal,0.616333,0.639242,3245.0,3221.0
596203,Roger Federer,Rafael Nadal,0.618591,0.639384,3335.0,3311.0
599772,Rafael Nadal,Roger Federer,0.638070,0.620213,3462.0,3473.0
601221,Roger Federer,Rafael Nadal,0.621944,0.637088,3518.0,3516.0
620901,Roger Federer,Rafael Nadal,0.623743,0.636414,3580.0,3581.0
659418,Roger Federer,Rafael Nadal,0.626104,0.635640,3624.0,3642.0
666623,Rafael Nadal,Roger Federer,0.635640,0.626104,3642.0,3624.0
669819,Roger Federer,Rafael Nadal,0.623621,0.636193,3717.0,3730.0

In [68]:
# surface specific p values

surface_serve_stats = defaultdict(
    lambda: {
        "first_won": 0,
        "second_won": 0,
        "svpt": 0,
        "matches": 0
    })

# feature lists
playerA_surface_p = []
playerB_surface_p = []

playerA_surface_serve_matches = []
playerB_surface_serve_matches = []


for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id
    surface = row.surface

   
    # PLAYER A
    playerA_stats = surface_serve_stats[(playerA, surface)]
    playerA_surface_serve_matches.append(playerA_stats["matches"])

    if playerA_stats["svpt"] > 0:
        playerA_surface_p.append((playerA_stats["first_won"] + playerA_stats["second_won"]) / playerA_stats["svpt"])

    else:
        playerA_surface_p.append(np.nan)


    
    # PLAYER B
    playerB_stats = surface_serve_stats[(playerB, surface)]
    playerB_surface_serve_matches.append(playerB_stats["matches"])

    if playerB_stats["svpt"] > 0:
        playerB_surface_p.append(( playerB_stats["first_won"] + playerB_stats["second_won"]) / playerB_stats["svpt"])

    else:
        playerB_surface_p.append(np.nan)


    # -------------------
    # UPDATES
    # -------------------

    if (pd.notna(row.playerA_svpt) and pd.notna(row.playerB_svpt)):

        # Player A
        surface_serve_stats[(playerA, surface)]["first_won"] += row.playerA_1stWon
        surface_serve_stats[(playerA, surface)]["second_won"] += row.playerA_2ndWon
        surface_serve_stats[(playerA, surface)]["svpt"] += row.playerA_svpt
        surface_serve_stats[(playerA, surface)]["matches"] += 1


        # Player B
        surface_serve_stats[(playerB, surface)]["first_won"] += row.playerB_1stWon
        surface_serve_stats[(playerB, surface)]["second_won"] += row.playerB_2ndWon
        surface_serve_stats[(playerB, surface)]["svpt"] += row.playerB_svpt
        surface_serve_stats[(playerB, surface)]["matches"] += 1


matches_df["playerA_surface_p"] = playerA_surface_p
matches_df["playerB_surface_p"] = playerB_surface_p

matches_df["playerA_surface_serve_matches"] = playerA_surface_serve_matches
matches_df["playerB_surface_serve_matches"] = playerB_surface_serve_matches

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1809731944.py:68: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_surface_p"] = playerA_surface_p
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1809731944.py:69: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_surface_p"] = playerB_surface_p
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1809731944.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_surface_serve_matches"] = playerA_surface_serve_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1809731944.py:72: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_surface_serve_matches"] = playerB_surface_serve_matches

In [69]:
#test-3
matches_df[["playerA_career_p", "playerA_surface_p"]].sample(15)

        playerA_career_p  playerA_surface_p
763400          0.571788           0.571788
318923          0.541284           0.541284
1133                 NaN                NaN
660219          0.607526           0.606340
295092               NaN                NaN
848546          0.554662           0.557566
136784               NaN                NaN
473137          0.605563           0.605751
740893          0.521146           0.521146
595308          0.554087           0.548872
176619               NaN                NaN
301163               NaN                NaN
487611          0.521277           0.477477
629324          0.618852                NaN
459074          0.560440           0.540650

## *Return Statistics*

In [70]:
from collections import defaultdict
import numpy as np
import pandas as pd

return_stats = defaultdict(
    lambda: {
        "return_points_won": 0,
        "return_points_played": 0,
        "bp_converted": 0,
        "bp_opportunities": 0,
        "matches": 0
    })

# feature lists
playerA_return_pct = []
playerA_bp_convert_pct = []
playerA_return_matches = []

playerB_return_pct = []
playerB_bp_convert_pct = []
playerB_return_matches = []


for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id


    
    # PLAYER A FEATURES
    playerA_stats = return_stats[playerA]

    playerA_return_matches.append(playerA_stats["matches"])

    if playerA_stats["return_points_played"] > 0:
        playerA_return_pct.append(playerA_stats["return_points_won"] / playerA_stats["return_points_played"])

    else:
        playerA_return_pct.append(0.5)


    if playerA_stats["bp_opportunities"] > 0:
        playerA_bp_convert_pct.append(playerA_stats["bp_converted"] / playerA_stats["bp_opportunities"])

    else:
        playerA_bp_convert_pct.append(0.5)


    
    # PLAYER B FEATURES
    playerB_stats = return_stats[playerB]

    playerB_return_matches.append(playerB_stats["matches"])

    if playerB_stats["return_points_played"] > 0:
        playerB_return_pct.append(playerB_stats["return_points_won"] / playerB_stats["return_points_played"])

    else:
        playerB_return_pct.append(0.5)


    if playerB_stats["bp_opportunities"] > 0:
        playerB_bp_convert_pct.append(playerB_stats["bp_converted"] / playerB_stats["bp_opportunities"])

    else:
        playerB_bp_convert_pct.append(0.5)


    
    # UPDATE RECORDS
    if (pd.notna(row.playerA_svpt) and pd.notna(row.playerB_svpt)):

        # Player A return stats
        playerA_return_points_won = (row.playerB_svpt - (row.playerB_1stWon + row.playerB_2ndWon))

        return_stats[playerA]["return_points_won"] += (playerA_return_points_won)
        return_stats[playerA]["return_points_played"] += (row.playerB_svpt)

        playerA_breaks = (row.playerB_bpFaced - row.playerB_bpSaved)

        return_stats[playerA]["bp_converted"] += (playerA_breaks)
        return_stats[playerA]["bp_opportunities"] += (row.playerB_bpFaced)

        return_stats[playerA]["matches"] += 1


        # Player B return stats
        playerB_return_points_won = (row.playerA_svpt - (row.playerA_1stWon + row.playerA_2ndWon))

        return_stats[playerB]["return_points_won"] += (playerB_return_points_won)
        return_stats[playerB]["return_points_played"] += (row.playerA_svpt)

        playerB_breaks = (row.playerA_bpFaced - row.playerA_bpSaved)

        return_stats[playerB]["bp_converted"] += (playerB_breaks)
        return_stats[playerB]["bp_opportunities"] += (row.playerA_bpFaced)

        return_stats[playerB]["matches"] += 1


matches_df["playerA_return_pct"] = playerA_return_pct
matches_df["playerA_bp_convert_pct"] = playerA_bp_convert_pct
matches_df["playerA_return_matches"] = playerA_return_matches

matches_df["playerB_return_pct"] = playerB_return_pct
matches_df["playerB_bp_convert_pct"] = playerB_bp_convert_pct
matches_df["playerB_return_matches"] = playerB_return_matches

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:101: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_return_pct"] = playerA_return_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_bp_convert_pct"] = playerA_bp_convert_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:103: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_return_matches"] = playerA_return_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:105: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_return_pct"] = playerB_return_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:106: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_bp_convert_pct"] = playerB_bp_convert_pct
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\928339463.py:107: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_return_matches"] = playerB_return_matches

In [71]:
#test-1
matches_df[["playerA_return_pct", "playerB_return_pct"]].describe()

       playerA_return_pct  playerB_return_pct
count       855141.000000       855141.000000
mean             0.415779            0.415813
std              0.072870            0.072866
min              0.000000            0.000000
25%              0.366721            0.366772
50%              0.398667            0.398614
75%              0.500000            0.500000
max              0.923077            1.000000

## *Fatigue Features*

In [72]:
from collections import defaultdict, deque

recent_history = defaultdict(deque)  # key = player_id


# feature lists
playerA_matches_7d = []
playerB_matches_7d = []

playerA_matches_30d = []
playerB_matches_30d = []

playerA_wins_7d = []
playerB_wins_7d = []

playerA_wins_30d = []
playerB_wins_30d = []

playerA_winpct_7d = []
playerB_winpct_7d = []

playerA_winpct_30d = []
playerB_winpct_30d = []


for row in matches_df.itertuples():
    playerA = row.playerA_id
    playerB = row.playerB_id

    current_date = row.tourney_date



    # PLAYER A FEATURES
    history = recent_history[playerA]
    
    # Optimize: Trim elements older than 30 days
    while history and (current_date - history[0][0]).days > 30:
        history.popleft()

    wins_7d = 0
    matches_7d = 0

    for match_date, result in history:
        if (current_date - match_date).days <= 7:
            matches_7d += 1
            wins_7d += result

    playerA_matches_7d.append(matches_7d)
    playerA_wins_7d.append(wins_7d)

    if matches_7d > 0:
        playerA_winpct_7d.append(wins_7d / matches_7d)
    else:
        playerA_winpct_7d.append(0.5)


    wins_30d = 0
    matches_30d = len(history)
    for _, result in history:
        wins_30d += result

    playerA_matches_30d.append(matches_30d)
    playerA_wins_30d.append(wins_30d)

    if matches_30d > 0:
        playerA_winpct_30d.append(wins_30d / matches_30d)
    else:
        playerA_winpct_30d.append(0.5)



    # PLAYER B FEATURES
    history = recent_history[playerB]
    
    # Optimize: Trim elements older than 30 days
    while history and (current_date - history[0][0]).days > 30:
        history.popleft()

    wins_7d = 0
    matches_7d = 0

    for match_date, result in history:
        if (current_date - match_date).days <= 7:

            matches_7d += 1
            wins_7d += result

    playerB_matches_7d.append(matches_7d)
    playerB_wins_7d.append(wins_7d)

    if matches_7d > 0:
        playerB_winpct_7d.append(wins_7d / matches_7d)
    else:
        playerB_winpct_7d.append(0.5)


    wins_30d = 0
    matches_30d = len(history)
    for _, result in history:
        wins_30d += result

    playerB_matches_30d.append(matches_30d)
    playerB_wins_30d.append(wins_30d)

    if matches_30d > 0:
        playerB_winpct_30d.append(wins_30d / matches_30d)
    else:
        playerB_winpct_30d.append(0.5)



    # UPDATE HISTORY
    if row.playerA_wins == 1:
        recent_history[playerA].append((current_date, 1))
        recent_history[playerB].append((current_date, 0))

    else:
        recent_history[playerA].append((current_date, 0))
        recent_history[playerB].append((current_date, 1))


matches_df["playerA_matches_7d"] = playerA_matches_7d
matches_df["playerB_matches_7d"] = playerB_matches_7d

matches_df["playerA_matches_30d"] = playerA_matches_30d
matches_df["playerB_matches_30d"] = playerB_matches_30d

matches_df["playerA_wins_7d"] = playerA_wins_7d
matches_df["playerB_wins_7d"] = playerB_wins_7d

matches_df["playerA_wins_30d"] = playerA_wins_30d
matches_df["playerB_wins_30d"] = playerB_wins_30d

matches_df["playerA_losses_7d"] = matches_df["playerA_matches_7d"] - matches_df["playerA_wins_7d"] #new
matches_df["playerB_losses_7d"] = matches_df["playerB_matches_7d"] - matches_df["playerB_wins_7d"] #new

matches_df["playerA_losses_30d"] = matches_df["playerA_matches_30d"] - matches_df["playerA_wins_30d"] #new
matches_df["playerB_losses_30d"] = matches_df["playerB_matches_30d"] - matches_df["playerB_wins_30d"] #new

matches_df["playerA_winpct_7d"] = playerA_winpct_7d
matches_df["playerB_winpct_7d"] = playerB_winpct_7d

matches_df["playerA_winpct_30d"] = playerA_winpct_30d
matches_df["playerB_winpct_30d"] = playerB_winpct_30d

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:123: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_matches_7d"] = playerA_matches_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:124: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_matches_7d"] = playerB_matches_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:126: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_matches_30d"] = playerA_matches_30d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:127: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_matches_30d"] = playerB_matches_30d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:129: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_wins_7d"] = playerA_wins_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:130: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_wins_7d"] = playerB_wins_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:132: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_wins_30d"] = playerA_wins_30d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:133: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_wins_30d"] = playerB_wins_30d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_losses_7d"] = matches_df["playerA_matches_7d"] - matches_df["playerA_wins_7d"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:136: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_losses_7d"] = matches_df["playerB_matches_7d"] - matches_df["playerB_wins_7d"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:138: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_losses_30d"] = matches_df["playerA_matches_30d"] - matches_df["playerA_wins_30d"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:139: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_losses_30d"] = matches_df["playerB_matches_30d"] - matches_df["playerB_wins_30d"] #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:141: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_winpct_7d"] = playerA_winpct_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:142: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_winpct_7d"] = playerB_winpct_7d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:144: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_winpct_30d"] = playerA_winpct_30d
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3229528906.py:145: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_winpct_30d"] = playerB_winpct_30d

In [73]:
#test-1
matches_df[["playerA_matches_7d", "playerA_wins_7d", "playerA_winpct_7d"]].tail(20)

        playerA_matches_7d  playerA_wins_7d  playerA_winpct_7d
855174                   2                1           0.500000
855175                   1                0           0.000000
855176                   4                3           0.750000
855177                   1                0           0.000000
855178                   2                1           0.500000
855179                   2                1           0.500000
855180                   1                1           1.000000
855181                   1                1           1.000000
855182                   4                3           0.750000
855183                   4                3           0.750000
855184                   2                1           0.500000
855185                   5                4           0.800000
855186                   2                1           0.500000
855187                   4                3           0.750000
855188                   2                2           1.000000
855189                   5                4           0.800000
855190                   4                3           0.750000
855191                   5                4           0.800000
855192                   6                5           0.833333
855193                   8                7           0.875000

## *Rank Features*

In [74]:
matches_df["playerA_is_unranked"] = matches_df["playerA_rank"].isna().astype("int8")
matches_df["playerB_is_unranked"] = matches_df["playerB_rank"].isna().astype("int8")

matches_df["playerA_rank_points_missing"] = (matches_df["playerA_rank_points"].isna().astype("int8"))
matches_df["playerB_rank_points_missing"] = (matches_df["playerB_rank_points"].isna().astype("int8"))

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\2401175602.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_is_unranked"] = matches_df["playerA_rank"].isna().astype("int8")
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\2401175602.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_is_unranked"] = matches_df["playerB_rank"].isna().astype("int8")
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\2401175602.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_rank_points_missing"] = (matches_df["playerA_rank_points"].isna().astype("int8"))
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\2401175602.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_rank_points_missing"] = (matches_df["playerB_rank_points"].isna().astype("int8"))

In [75]:
MAX_RANK = max(matches_df['playerA_rank'].max(), matches_df['playerB_rank'].max())
UNRANKED_RANK = MAX_RANK + 1

matches_df["playerA_rank_filled"] = matches_df["playerA_rank"].fillna(UNRANKED_RANK)
matches_df["playerB_rank_filled"] = matches_df["playerB_rank"].fillna(UNRANKED_RANK)

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\271980594.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_rank_filled"] = matches_df["playerA_rank"].fillna(UNRANKED_RANK)
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\271980594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_rank_filled"] = matches_df["playerB_rank"].fillna(UNRANKED_RANK)

In [76]:
matches_df['rank_diff'] = matches_df['playerA_rank_filled'] - matches_df['playerB_rank_filled']
matches_df['rank_ratio'] = matches_df['playerA_rank_filled'] / matches_df['playerB_rank_filled']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3319253235.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['rank_diff'] = matches_df['playerA_rank_filled'] - matches_df['playerB_rank_filled']
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3319253235.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['rank_ratio'] = matches_df['playerA_rank_filled'] / matches_df['playerB_rank_filled']

In [77]:
rank_points_median = pd.concat([matches_df['playerA_rank_points'], matches_df['playerB_rank_points']]).median()

playerA_points_filled = matches_df['playerA_rank_points'].fillna(rank_points_median)
playerB_points_filled = matches_df['playerB_rank_points'].fillna(rank_points_median)

matches_df['rank_points_diff'] = playerA_points_filled - playerB_points_filled

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1805006488.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['rank_points_diff'] = playerA_points_filled - playerB_points_filled

In [78]:
for threshold in [10, 32, 64, 100]:
    matches_df[f"playerA_top{threshold}"] = (matches_df["playerA_rank_filled"] <= threshold).astype('int8')
    matches_df[f"playerB_top{threshold}"] = (matches_df['playerB_rank_filled'] <= threshold).astype("int8")

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerA_top{threshold}"] = (matches_df["playerA_rank_filled"] <= threshold).astype('int8')
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerB_top{threshold}"] = (matches_df['playerB_rank_filled'] <= threshold).astype("int8")
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerA_top{threshold}"] = (matches_df["playerA_rank_filled"] <= threshold).astype('int8')
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerB_top{threshold}"] = (matches_df['playerB_rank_filled'] <= threshold).astype("int8")
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerA_top{threshold}"] = (matches_df["playerA_rank_filled"] <= threshold).astype('int8')
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerB_top{threshold}"] = (matches_df['playerB_rank_filled'] <= threshold).astype("int8")
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerA_top{threshold}"] = (matches_df["playerA_rank_filled"] <= threshold).astype('int8')
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1132771660.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df[f"playerB_top{threshold}"] = (matches_df['playerB_rank_filled'] <= threshold).astype("int8")

In [79]:
#test-1

matches_df[[
    "playerA_is_unranked",
    "playerB_rank_points_missing",
    "playerA_rank_filled", 
    "playerA_rank", 
    "rank_diff",
    "rank_ratio",
    "rank_points_diff",
    "playerA_top32"
]
    
].sample(15)

,playerA_is_unranked,playerB_rank_points_missing,playerA_rank_filled,playerA_rank,rank_diff,rank_ratio,rank_points_diff,playerA_top32
91924,0,0,814.0,814.0,203.0,1.332242,-14.0,0
315544,0,0,711.0,711.0,451.0,2.734615,-130.0,0
773232,0,0,1383.0,1383.0,404.0,1.412666,-10.0,0
81920,1,0,2268.0,NaN,1087.0,1.920406,69.0,0
667170,0,0,130.0,130.0,-151.0,0.462633,281.0,0
595784,0,0,769.0,769.0,-7.0,0.990979,1.0,0
456889,0,0,415.0,415.0,164.0,1.653386,-95.0,0
479023,0,0,368.0,368.0,80.0,1.277778,-48.0,0
396035,0,0,312.0,312.0,-234.0,0.571429,86.0,0
363,0,1,326.0,326.0,28.0,1.093960,0.0,0
367411,0,0,304.0,304.0,-611.0,0.332240,104.0,0
639959,0,0,142.0,142.0,-172.0,0.452229,242.0,0
401188,0,0,954.0,954.0,533.0,2.266033,-71.0,0
460744,0,0,912.0,912.0,-6.0,0.993464,0.0,0
215360,0,0,709.0,709.0,-319.0,0.689689,12.0,0

## *Physical features*

In [80]:
median_age = pd.concat([matches_df['playerA_age'], matches_df['playerB_age']]).median()

matches_df['playerA_age'] = matches_df['playerA_age'].fillna(median_age)
matches_df['playerB_age'] = matches_df['playerB_age'].fillna(median_age)

matches_df['age_diff'] = matches_df['playerA_age'] - matches_df['playerB_age']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1614477319.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['age_diff'] = matches_df['playerA_age'] - matches_df['playerB_age']

In [81]:
median_height = pd.concat([matches_df['playerA_ht'], matches_df['playerB_ht']]).median()

matches_df['playerA_ht'] = matches_df['playerA_ht'].fillna(median_height)
matches_df['playerB_ht'] = matches_df['playerB_ht'].fillna(median_height)

matches_df['height_diff'] = matches_df['playerA_ht'] - matches_df['playerB_ht']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1595003183.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['height_diff'] = matches_df['playerA_ht'] - matches_df['playerB_ht']

## *Seed features*

In [82]:
matches_df['playerA_seeded'] = matches_df['playerA_seed'].notna().astype('int8')
matches_df['playerB_seeded'] = matches_df['playerB_seed'].notna().astype('int8')

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\672625524.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_seeded'] = matches_df['playerA_seed'].notna().astype('int8')
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\672625524.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_seeded'] = matches_df['playerB_seed'].notna().astype('int8')

In [83]:
matches_df['seed_diff'] = np.where(
    matches_df['playerA_seed'].notna() & matches_df['playerB_seed'].notna(), 
    matches_df['playerA_seed'] - matches_df['playerB_seed'], 
    np.nan
)

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\273368266.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['seed_diff'] = np.where(

In [84]:
matches_df['seed_diff_missing'] = matches_df['seed_diff'].isna().astype('int8')

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\995359959.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['seed_diff_missing'] = matches_df['seed_diff'].isna().astype('int8')

## *Surface Specialization features*

In [85]:
#win rate
matches_df['playerA_win_rate_specialization'] = matches_df["playerA_surface_career_pct"] - matches_df['playerA_career_pct']
matches_df['playerB_win_rate_specialization'] = matches_df['playerB_surface_career_pct'] - matches_df['playerB_career_pct']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1546508238.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_win_rate_specialization'] = matches_df["playerA_surface_career_pct"] - matches_df['playerA_career_pct']
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\1546508238.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_win_rate_specialization'] = matches_df['playerB_surface_career_pct'] - matches_df['playerB_career_pct']

In [86]:
#elo
matches_df['playerA_elo_specialization'] = matches_df['playerA_surface_elo'] - matches_df['playerA_elo']
matches_df['playerB_elo_specialization'] = matches_df['playerB_surface_elo'] - matches_df['playerB_elo']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\167736039.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_elo_specialization'] = matches_df['playerA_surface_elo'] - matches_df['playerA_elo']
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\167736039.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_elo_specialization'] = matches_df['playerB_surface_elo'] - matches_df['playerB_elo']

In [87]:
#p
matches_df['playerA_serve_specialization'] = matches_df['playerA_surface_p'] - matches_df['playerA_career_p']
matches_df['playerB_serve_specialization'] = matches_df['playerB_surface_p'] - matches_df['playerB_career_p']

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\221088805.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_serve_specialization'] = matches_df['playerA_surface_p'] - matches_df['playerA_career_p']
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\221088805.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_serve_specialization'] = matches_df['playerB_surface_p'] - matches_df['playerB_career_p']

## *Experience*

In [88]:
from collections import defaultdict

tournament_matches = defaultdict(int)                # key = (player_id, tourney_name)

level_matches = defaultdict(int)                     # key = (player_id, tourney_level)
level_wins = defaultdict(int)                        # key = (player_id, tourney_level)
level_losses = defaultdict(int)                      # key = (player_id, tourney_level)

tourney_minutes = defaultdict(float)                 # key = (player_id, tourney_id)
tourney_match_count = defaultdict(int)               # key = (player_id, tourney_id)

# Fill missing minutes with median match duration (median is robust to outliers)
median_minutes = matches_df['minutes'].median()
matches_df['minutes'] = matches_df['minutes'].fillna(median_minutes)


# FEATURE LISTS
playerA_tourney_matches = []
playerB_tourney_matches = []

playerA_level_matches = []
playerB_level_matches = []

playerA_level_wins = []
playerB_level_wins = []

playerA_level_losses = []
playerB_level_losses = []

playerA_minutes_tourney = []
playerB_minutes_tourney = []

playerA_avg_minutes_tourney = []
playerB_avg_minutes_tourney = []


for row in matches_df.itertuples():

    playerA = row.playerA_id
    playerB = row.playerB_id

    surface = row.surface
    tourney = row.tourney_name
    tourney_level = row.tourney_level
    tourney_id = row.tourney_id

    # -------------------------
    # TOTAL SAME TOURNAMENT MATCHES
    # -------------------------
    playerA_tourney_matches.append(tournament_matches[(playerA, tourney)])
    playerB_tourney_matches.append(tournament_matches[(playerB, tourney)])

    # -------------------------
    # TOTAL SAME TOURNEY LEVEL MATCHES
    # -------------------------
    playerA_level_matches.append(level_matches[(playerA, tourney_level)])
    playerB_level_matches.append(level_matches[(playerB, tourney_level)])

    # -------------------------
    # TOURNEY LEVEL WINS
    # -------------------------
    playerA_level_wins.append(level_wins[(playerA, tourney_level)])
    playerB_level_wins.append(level_wins[(playerB, tourney_level)])

    # -------------------------
    # TOURNEY LEVEL LOSSES
    # -------------------------
    playerA_level_losses.append(level_losses[(playerA, tourney_level)])
    playerB_level_losses.append(level_losses[(playerB, tourney_level)])

    # -------------------------
    # MINUTES PLAYED IN CURRENT TOURNAMENT
    # -------------------------
    playerA_minutes_tourney.append(tourney_minutes[(playerA, tourney_id)])
    playerB_minutes_tourney.append(tourney_minutes[(playerB, tourney_id)])

    # -------------------------
    # AVERAGE MINUTES IN CURRENT TOURNAMENT
    # -------------------------
    matches_played = tourney_match_count[(playerA, tourney_id)]
    minutes_played = tourney_minutes[(playerA, tourney_id)]

    if matches_played > 0:
        playerA_avg_minutes_tourney.append(minutes_played / matches_played)
    else:
        playerA_avg_minutes_tourney.append(0)

    matches_played = tourney_match_count[(playerB, tourney_id)]
    minutes_played = tourney_minutes[(playerB, tourney_id)]

    if matches_played > 0:
        playerB_avg_minutes_tourney.append(minutes_played / matches_played)
    else:
        playerB_avg_minutes_tourney.append(0)

    # -------------------------
    # UPDATE COUNTERS
    # -------------------------

    tournament_matches[(playerA, tourney)] += 1
    tournament_matches[(playerB, tourney)] += 1

    level_matches[(playerA, tourney_level)] += 1
    level_matches[(playerB, tourney_level)] += 1

    # Winner / loser updates
    if row.playerA_wins == 1:
        level_wins[(playerA, tourney_level)] += 1
        level_losses[(playerB, tourney_level)] += 1
    else:
        level_wins[(playerB, tourney_level)] += 1
        level_losses[(playerA, tourney_level)] += 1

    tourney_minutes[(playerA, tourney_id)] += row.minutes
    tourney_minutes[(playerB, tourney_id)] += row.minutes

    tourney_match_count[(playerA, tourney_id)] += 1
    tourney_match_count[(playerB, tourney_id)] += 1


# -------------------------
# ATTACH FEATURES
# -------------------------
matches_df["playerA_tourney_matches"] = playerA_tourney_matches
matches_df["playerB_tourney_matches"] = playerB_tourney_matches

matches_df["playerA_level_matches"] = playerA_level_matches
matches_df["playerB_level_matches"] = playerB_level_matches

matches_df["playerA_level_wins"] = playerA_level_wins #new
matches_df["playerB_level_wins"] = playerB_level_wins #new

matches_df["playerA_level_losses"] = playerA_level_losses #new
matches_df["playerB_level_losses"] = playerB_level_losses #new 

matches_df['playerA_level_win_pct'] = np.where(matches_df["playerA_level_matches"] > 0, matches_df["playerA_level_wins"]/matches_df["playerA_level_matches"], 0.5) #new
matches_df['playerB_level_win_pct'] = np.where(matches_df["playerB_level_matches"] > 0, matches_df["playerB_level_wins"]/matches_df["playerB_level_matches"], 0.5) #new

matches_df["playerA_minutes_tourney"] = playerA_minutes_tourney
matches_df["playerB_minutes_tourney"] = playerB_minutes_tourney

matches_df["playerA_avg_minutes_tourney"] = playerA_avg_minutes_tourney
matches_df["playerB_avg_minutes_tourney"] = playerB_avg_minutes_tourney

C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:124: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_tourney_matches"] = playerA_tourney_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:125: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_tourney_matches"] = playerB_tourney_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:127: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_level_matches"] = playerA_level_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:128: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_level_matches"] = playerB_level_matches
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:130: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_level_wins"] = playerA_level_wins #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:131: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_level_wins"] = playerB_level_wins #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:133: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_level_losses"] = playerA_level_losses #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:134: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_level_losses"] = playerB_level_losses #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:136: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerA_level_win_pct'] = np.where(matches_df["playerA_level_matches"] > 0, matches_df["playerA_level_wins"]/matches_df["playerA_level_matches"], 0.5) #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:137: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df['playerB_level_win_pct'] = np.where(matches_df["playerB_level_matches"] > 0, matches_df["playerB_level_wins"]/matches_df["playerB_level_matches"], 0.5) #new
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:139: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_minutes_tourney"] = playerA_minutes_tourney
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_minutes_tourney"] = playerB_minutes_tourney
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:142: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerA_avg_minutes_tourney"] = playerA_avg_minutes_tourney
C:\Users\HP\AppData\Local\Temp\ipykernel_17248\3167052848.py:143: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  matches_df["playerB_avg_minutes_tourney"] = playerB_avg_minutes_tourney

# **Saving the File**

In [89]:
matches_df.to_csv(DF_DIR / "matches_1991_2026_features_added.csv", index = False)

In [90]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 855141 entries, 0 to 855193
Columns: 239 entries, tourney_id to playerB_avg_minutes_tourney
dtypes: datetime64[ns](1), float64(109), int64(100), int8(15), object(14)
memory usage: 1.5+ GB