In [1]:
from pathlib import Path
import pandas as pd

DF_DIR = Path("data/created_data")

matches_df = pd.read_csv(DF_DIR / "matches_1991_2026_features_added.csv")

# **Adding the Labels**

In [2]:
import numpy as np

playerA_valid = (
    matches_df["playerA_svpt"].notna() &
    matches_df["playerA_1stWon"].notna() &
    matches_df["playerA_2ndWon"].notna() &
    (matches_df["playerA_svpt"] > 0)
)

matches_df["playerA_match_p"] = np.where(playerA_valid,
    (matches_df["playerA_1stWon"] + matches_df["playerA_2ndWon"]) / matches_df["playerA_svpt"],
    np.nan
)

playerB_valid = (
    matches_df["playerB_svpt"].notna() &
    matches_df["playerB_1stWon"].notna() &
    matches_df["playerB_2ndWon"].notna() &
    (matches_df["playerB_svpt"] > 0)
)

matches_df["playerB_match_p"] = np.where(playerB_valid,
    (matches_df["playerB_1stWon"] + matches_df["playerB_2ndWon"]) / matches_df["playerB_svpt"],
    np.nan
)

# **Data Analysis**

In [3]:
matches_df_copy = matches_df.copy()

In [4]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 855141 entries, 0 to 855140
Columns: 241 entries, tourney_id to playerB_match_p
dtypes: float64(111), int64(115), object(15)
memory usage: 1.5+ GB

In [5]:
pd.set_option("display.max_columns", None)
matches_df.describe()

,draw_size,match_num,best_of,minutes,round_rank,playerA_wins,playerA_id,playerB_id,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank,playerB_rank,playerA_rank_points,playerB_rank_points,playerA_ace,playerB_ace,playerA_df,playerB_df,playerA_svpt,playerB_svpt,playerA_1stIn,playerB_1stIn,playerA_1stWon,playerB_1stWon,playerA_2ndWon,playerB_2ndWon,playerA_SvGms,playerB_SvGms,playerA_bpSaved,playerB_bpSaved,playerA_bpFaced,playerB_bpFaced,match_id,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney,playerA_match_p,playerB_match_p
count,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,284059.000000,283457.000000,855141.000000,855141.000000,855141.000000,855141.000000,779818.000000,779301.000000,770210.000000,769736.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259680.000000,259678.000000,259678.000000,259680.000000,259680.000000,259680.000000,259680.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,547245.000000,547245.000000,547245.000000,547245.000000,547238.000000,547245.000000,546913.000000,546913.000000,546913.000000,546913.000000,546910.000000,546913.000000,855141.000000,855141.000000,94589.000000,94594.000000,855141.000000,855141.000000,492783.000000,492438.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,64710.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,492783.000000,492438.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,855141.000000,259505.000000,259484.000000
mean,37.038065,93.196212,3.057850,96.952808,8.476378,0.499591,122113.641843,122154.231469,5.076150,5.069841,184.482924,184.482871,23.712402,23.706638,542.223020,542.223005,262.348918,262.000625,4.689040,4.692926,2.991039,2.983788,73.672951,73.629652,44.899869,44.885944,31.170903,31.173929,14.281758,14.277680,11.359703,11.362564,4.000273,3.987827,6.777549,6.760421,427576.702734,0.258423,0.257793,0.516215,0.000630,0.168438,0.167894,0.336332,0.000544,0.239655,0.239143,0.478798,0.000512,2.998986,5.568836,8.567822,0.411423,2.990433,5.541169,8.531602,0.411399,77.823578,63.945023,141.768601,0.492274,77.533313,63.706141,141.239454,0.491989,1636.781298,1636.575996,0.205302,1565.462905,1565.271209,0.191696,1586.858423,1586.662645,0.195778,1.004047,2.445203,2.420058,13.887713,13.860074,1.003015,1.002893,119.562260,93.882298,213.444558,0.491658,119.314778,93.721769,213.036547,0.491306,68.759303,52.045000,120.804302,0.499100,68.637852,51.970236,120.608088,0.498743,4.885595,9.454447,4.568851,0.506327,4.881444,9.452313,4.570868,0.505936,11.787044,22.478093,10.691049,0.504078,11.774120,22.466254,10.692134,0.503624,4.747823,9.030595,4.282772,0.511722,4.743679,9.029813,4.286134,0.511278,11.053156,20.650975,9.597818,0.509003,11.043525,20.643531,9.600006,0.508594,23.048017,40.699059,17.651042,0.512916,23.018186,40.665790,17.647603,0.512369,0.053173,0.044674,0.600907,0.667406,0.474488,0.589454,0.053198,0.044634,0.600899,0.667481,0.474600,0.589515,71.519727,71.339081,0.620750,0.620945,18.520623,18.512979,0.592400,0.592452,37.604294,37.547261,0.415779,0.434645,71.519727,0.415813,0.434910,71.339081,2.232983,2.228472,4.776927,4.769091,1.631564,1.627052,3.046011,3.038115,0.601419,0.601420,1.730916,1.730975,0.621095,0.620847,0.555947,0.555505,0.088083,0.088687,0.099318,0.099872,694.233857,695.277212,-1.043354,1.717014,0.419572,0.014283,0.014049,0.039986,0.039472,0.073962,0.073836,0.113197,0.113199,0.005764,0.000053,0.332178,0.331474,0.026688,0.924328,0.007441,0.007437,-71.318393,-71.304787,-0.000779,-0.000797,3.039788,3.036826,91.904867,91.806681,50.231506,50.157309,41.673361,41.649372,0.482594,0.482355,81.218680,81.243367,46.726152,46.749217,0.617733,0.618020
std,20.155630,150.392002,0.335192,21.360347,2.475233,0.500000,35907.589569,35950.844138,3.897833,3.889597,6.677485,6.684271,3.951486,3.949231,422.932112,422.813107,691.229332,693.204023,4.416311,4.411428,2.401149,2.397647,25.767649,25.721725,16.963373,16.952855,12.474571,12.467785,6.455146,6.443252,3.599512,3.600421,3.100779,3.083308,4.239424,4.223841,246868.229301,0.773938,0.770058,1.293077,0.843736,0.561040,0.559001,0.910102,0.652847,0.632868,0.631360,1.005565,0.766233,15.075336,17.058428,30.151059,0.177206,15.062650,16.991389,30.085629,0.177497,101.899124,74.553524,173.615626,0.178671,101.737399,74.350170,173.213949,0.179246,173.621516,173.653399,142.595382,112.837970,112.906853,115.732337,127.257257,127.323546,119.207525,0.089056,33.310875,33.303166,12.263861,12.247785,0.076346,0.074701,131.039053,90.001836,217.769142,0.146562,130.852204,89.850953,217.430140,0.146834,85.008054,55.706879,138.755389,0.163442,84.948127,55.693251,138.690866,0.163701,2.179796,1.960346,1.998041,0.203996,2.178295,1.963960,1.995358,0.203897,5.108697,6.394857,4.212345,0.172707,5.110575,6.407285,4.210771,0.172841,2.308772,2.541639,2.047184,0.208680,2.307944,2.541893,2.046535,0.208754,5.678123,7.979582,4.496956,0.181987,5.678447,7.982859,4.494369,0.182150,16.339383,24.049294,9.283280,0.162125,16.338106,24.053711,9.286414,0.162464,0.031960,0.020004,0.054292,0.065578,0.056980,0.052686,0.032053,0.020075,0.054477,0.065557,0.056943,0.052647,144.348639,144.087876,0.079620,0.079112,83.840030,83.938797,0.054538,0.054406,80.994740,80.894906,0.072870,0.103638,144.348639,0.072866,0.103276,144.087876,2.303572,2.293971,3.792503,3.787264,1.961499,1.952904,3.069630,3.064372,0.680949,0.681186,1.255197,1.254712,0.296365,0.296567,0.263063,0.263467,0.283415,0.284292,0.299089,0.299830,634.307400,635.317515,703.229399,6.592401,689.726877,0.118655,0.117694,0.195927,0.194715,0.261709,0.261504,0.316833,0.316836,5.094651,9.299395,0.470995,0.470743,5.565479,0.264472,0.090595,0.090644,91.589274,91.519860,0.023144,0.023110,6.183064,6.175595,99.713149,99.645671,60.402191,60.335332,41.865252,41.873656,0.167588,0.167858,107.879551,108.204779,49.734274,50.041037,0.096984,0.096968
min,2.000000,1.000000,3.000000,0.000000,1.000000,0.000000,100113.000000,100063.000000,1.000000,1.000000,3.000000,3.000000,14.000000,14.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-23.000000,0.000000,0.000000,0.000000,-20.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1147.030234,1145.156568,-838.666810,1159.889916,1157.890261,-686.655177,1160.116846,1161.235486,-646.767833,0.583761,-444.281549,-437.069233,0.000000,0.000000,0.643244,0.672065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.283019,0.000000,0.000000,0.000000,0.000000,0.000000,0.190476,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2267.000000,0.000441,-16641.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-48.700000,-200.000000,0.000000,0.000000,-32.000000,0.000000,-0.827586,-0.850000,-814.543124,-814.702424,-0.636659,-0.584881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,11.000000,3.000000,95.000000,8.000000,0.000000,103469.000000,103465.000000,2.000000,2.000000,183.000000,183.000000,20.700000,20.700000,209.000000,209.000000,19.000000,19.000000,2.000000,2.000000,1.000000,1.000000,55.000000,55.000000,33.000000,33.000000,23.000000,23.000000,10.000000,10.000000,9.000000,9.000000,2.000000,2.000000,4.000000,4.000000,213785.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.413793,0.000000,0.000000,0.000000,0.414634,8.000000,9.000000,19.000000,0.416667,8.000000,9.000000,18.000000,0.416667,1500.000000,1500.000000,-89.925642,1482.893712,1482.475523,-73.646488,1491.613309,1491.117370,-75.423489,0.946364,-11.710153,-11.752842,5.464401,5.457459,0.953532,0.953992,19.000000,25.000000,45.000000,0.428571,19.000000,25.000000,45.000000,0.428571,8.000000,11.000000,20.000000,0.428571,8.000000,11.000000,20.000000,0.428571,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,9.000000,25.000000,8.000000,0.400000,9.000000,25.000000,8.000000,0.400000,3.000000,10.000000,3.000000,0.400000,3.000000,10.000000,3.000000,0.400000,7.000000,20.000000,7.000000,0.400000,7.000000,20.000000,7.000000,0.400000,9.000000,20.000000,10.000000,0.442308,9.000000,20.000000,10.000000,0.441860,0.030880,0.032690,0.569946,0.636521,0.455537,0.567568,0.030864,0.032675,0.569851,0.636792,0.455696,0.567766,0.000000,0.000000,0.573171,0.573333,0.000000,0.000000,0.568966,0.569002,0.000000,0.000000,0.366721,0.394102,0.000000,0.366772,0.394107,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,233.000000,233.000000,-224.000000,0.561688,-57.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.300000,-3.000000,0.000000,0.000000,-4.000000,1.000000,-0.008649,-0.008695,-110.051763,-109.918881,-0.004803,-0.004775,0.000000,0.000000,18.000000,18.000000,7.000000,7.000000,10.000000,10.000000,0.400000,0.400000,0.000000,0.000000,0.000000,0.000000,0.555556,0.556818
50%,32.000000,23.000000,3.000000,95.000000,8.000000,0.000000,105112.000000,105114.000000,5.000000,4.000000,185.000000,185.000000,23.300000,23.300000,450.000000,450.000000,71.000000,71.000000,4.000000,4.000000,3.000000,3.000000,69.000000,69.000000,42.000000,42.000000,29.000000,29.000000,13.000000,13.000000,10.000000,10.000000,3.000000,3.000000,6.000000,6.000000,427570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.500000,35.000000,35.000000,70.000000,0.518987,34.000000,34.000000,69.000000,0.518750,1627.779723,1627.722392,0.000000,1564.139747,1563.828055,0.000000,1587.445812,1587.145042,0.000000,1.000000,0.000000,0.000000,11.030969,11.026644,1.000000,1.000000,74.000000,66.000000,141.000000,0.531250,73.000000,66.000000,141.000000,0.530864,35.000000,33.000000,69.000000,0.531250,35.000000,33.000000,69.000000,0.530864,5.000000,10.000000,5.000000,0.500000,5.000000,10.000000,5.000000,0.500000,13.000000,25.000000,11.000000,0.520000,13.000000,25.000000,11.000000,0.520000,5.000000,10.000000,4.000000,0.500000,5.000000,10.000000,4.000000,0.500000,12.000000,25.000000,10.000000,0.520000,12.000000,25.000000,10.000000,0.520000,22.000000,42.000000,19.000000,0.534884,22.000000,42.000000,19.000000,0.534483,0.048428,0.041284,0.601612,0.674699,0.486171,0.597893,0.048387,0.041249,0.601562,0.674706,0.486111,0.597902,4.000000,4.000000,0.622047,0.622222,0.000000,0.000000,0.599529,0.599556,2.000000,2.000000,0.398667,0.440000,4.000000,0.398614,0.440000,4.000000,2.000000,2.000000,4.000000,4.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,0.500000,0.500000,0.571429,0.571429,0.000000,0.000000,0.000000,0.000000,501.000000,502.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.008371,0.008403,-41.124076,-41.163297,0.000000,0.000000,1.000000,1.000000,57.000000,57.000000,27.000000,27.000000,28.000000,28.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.620253,0.620690

# **Final Cleanup for v1**

In [6]:
matches_df_before_final_cleanup = matches_df.copy()

## *Dropping Rows where Data isn't Available*

In [7]:
matches_df = matches_df.dropna(subset=["playerA_match_p", "playerB_match_p"])

In [8]:
#test-1
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259423 entries, 116 to 855140
Columns: 241 entries, tourney_id to playerB_match_p
dtypes: float64(111), int64(115), object(15)
memory usage: 479.0+ MB

## *Dropping Leakage Columns*

In [9]:
matches_df = matches_df.drop([
    'playerA_ace',
    'playerB_ace',
    'playerA_df',
    'playerB_df',
    'playerA_svpt',
    'playerB_svpt',
    'playerA_1stIn',
    'playerB_1stIn',
    'playerA_1stWon',
    'playerB_1stWon',
    'playerA_2ndWon',
    'playerB_2ndWon',
    'playerA_SvGms',
    'playerB_SvGms',
    'playerA_bpSaved',
    'playerB_bpSaved',
    'playerA_bpFaced',
    'playerB_bpFaced',
    'minutes',
    'score',
    # 'playerA_wins'
], axis= 1)

In [10]:
#test-1
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259423 entries, 116 to 855140
Columns: 221 entries, tourney_id to playerB_match_p
dtypes: float64(92), int64(115), object(14)
memory usage: 439.4+ MB

## *Dropping Other Useless Columns*

In [11]:
matches_df = matches_df.drop([
    "playerA_name",
    "playerB_name",
    "playerA_ioc",
    "playerB_ioc"
], axis = 1)

In [12]:
pd.set_option("display.max_columns", None)
matches_df.describe()

,draw_size,match_num,best_of,round_rank,playerA_wins,playerA_id,playerB_id,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank,playerB_rank,playerA_rank_points,playerB_rank_points,match_id,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney,playerA_match_p,playerB_match_p
count,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,84683.000000,84324.000000,259423.000000,259423.000000,259423.000000,259423.000000,253300.000000,253146.000000,252339.000000,252194.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,255217.000000,255217.000000,255217.000000,255217.000000,255210.000000,255217.000000,255161.000000,255161.000000,255161.000000,255161.000000,255158.000000,255161.000000,259423.000000,259423.000000,84112.000000,84118.000000,259423.000000,259423.000000,251863.000000,251815.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,20415.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,251863.000000,251815.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000,259423.000000
mean,46.040004,194.621383,3.140003,7.394013,0.498684,130544.541829,130544.750489,6.383442,6.384220,185.008453,185.015507,25.627734,25.624413,284.543881,284.163396,623.415382,622.511745,552958.922582,0.472711,0.470151,0.942862,0.002560,0.274602,0.272439,0.547041,0.002162,0.421150,0.419034,0.840184,0.002116,8.845287,15.496170,24.341458,0.334228,8.844258,15.415642,24.259900,0.334454,148.090165,111.296288,259.386454,0.549996,147.686967,110.935545,258.622512,0.550014,1785.504594,1785.319403,0.185191,1639.109613,1639.170576,-0.060963,1683.028107,1683.015224,0.012884,1.003687,1.485732,1.507193,12.125524,12.114964,1.002575,1.002573,216.573473,155.438242,372.011714,0.557275,216.305933,155.224036,371.529968,0.557003,117.433389,81.192126,198.625515,0.555723,117.447774,81.191984,198.639758,0.555581,5.369744,9.861180,4.491437,0.541318,5.371301,9.858914,4.487613,0.541418,13.519923,24.338898,10.818975,0.549095,13.514870,24.330375,10.815506,0.548849,5.316757,9.657575,4.340818,0.544962,5.316930,9.657305,4.340375,0.544861,13.134498,23.310412,10.175913,0.552528,13.126176,23.302741,10.176565,0.552160,32.088897,54.821851,22.732954,0.557347,32.025992,54.744718,22.718726,0.556957,0.060515,0.041315,0.607023,0.689990,0.494298,0.612321,0.060500,0.041297,0.606890,0.689869,0.494334,0.612230,194.693759,194.337360,0.621550,0.621761,56.076686,56.048407,0.613506,0.613456,101.808205,101.768914,0.385691,0.411231,194.693759,0.385728,0.411403,194.337360,1.993586,1.994592,5.361803,5.361402,1.481349,1.482779,3.395655,3.396576,0.512237,0.511813,1.966148,1.964826,0.629123,0.629317,0.559095,0.559001,0.023602,0.024196,0.027307,0.027866,331.358164,332.164315,-0.806151,2.316332,1.187219,0.044140,0.043354,0.123590,0.121701,0.226537,0.225855,0.333236,0.333432,0.003322,-0.007054,0.326428,0.325044,0.091648,0.921306,-0.001552,-0.001422,-146.394981,-146.148827,0.000703,0.000716,4.583584,4.606299,104.072954,103.895992,57.327122,57.229047,46.745832,46.666945,0.502024,0.501890,87.842635,87.871954,49.074242,49.094922,0.617740,0.618020
std,30.005769,180.805781,0.510300,3.241275,0.499999,42277.783093,42255.581525,5.377285,5.359366,7.349513,7.333128,4.070363,4.079111,339.762257,338.277710,1080.247205,1087.663872,245751.639724,1.121808,1.114552,1.890243,1.195131,0.755895,0.748845,1.235831,0.858496,0.841198,0.837332,1.324832,1.030679,25.507902,26.730113,48.770328,0.202683,25.653747,26.647318,48.835203,0.203615,131.198980,92.583441,218.543612,0.123073,131.446357,92.431252,218.498789,0.123530,173.756753,173.855567,148.412459,111.372067,111.626438,117.709390,123.758519,123.987491,119.209364,0.085156,27.701489,27.731003,10.528673,10.545360,0.071854,0.072430,154.771610,104.232582,252.584018,0.102840,154.877373,104.182391,252.579481,0.103351,104.740582,66.711116,168.255199,0.124069,104.752277,66.774677,168.321870,0.124380,1.884220,1.015146,1.807394,0.183552,1.885292,1.022647,1.806239,0.183718,3.930517,3.434477,3.479505,0.144280,3.939305,3.457172,3.481837,0.144683,1.983722,1.560994,1.837034,0.187072,1.985208,1.564337,1.836981,0.187199,4.554510,5.287663,3.726947,0.152346,4.558142,5.295293,3.725777,0.152572,15.386179,20.803567,8.005042,0.126673,15.379641,20.811182,8.016898,0.126656,0.031689,0.013801,0.043019,0.047543,0.034099,0.035782,0.031801,0.013938,0.043142,0.047666,0.034157,0.035937,197.108879,197.106156,0.078715,0.078289,140.882968,141.056043,0.040112,0.040027,114.993564,114.958024,0.033366,0.054555,197.108879,0.033313,0.055191,197.106156,1.858778,1.863866,3.464847,3.466001,1.653490,1.659105,2.913445,2.915567,0.529495,0.530726,1.159871,1.159258,0.301239,0.300803,0.250148,0.250777,0.151807,0.153658,0.162976,0.164588,450.972958,452.311017,454.661303,11.085539,1213.195289,0.205407,0.203653,0.329113,0.326941,0.418592,0.418145,0.471371,0.471440,5.575913,10.183974,0.468907,0.468392,7.706446,0.269261,0.077552,0.077822,107.434758,107.285837,0.019547,0.019475,7.993970,8.135639,106.782873,106.545847,63.433532,63.311757,46.282812,46.196585,0.150370,0.150737,120.747648,121.688695,54.392946,55.303038,0.096888,0.096871
min,2.000000,1.000000,3.000000,1.000000,0.000000,100282.000000,100282.000000,1.000000,1.000000,3.000000,3.000000,14.400000,14.300000,1.000000,1.000000,1.000000,1.000000,116.000000,0.000000,0.000000,0.000000,-23.000000,0.000000,0.000000,0.000000,-20.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1147.030234,1145.156568,-820.971471,1167.746944,1182.350079,-686.655177,1166.145429,1182.350079,-646.767833,0.583761,-444.281549,-437.069233,0.000000,0.000000,0.643244,0.672065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.190476,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2267.000000,0.000441,-16641.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-48.700000,-200.000000,0.000000,0.000000,-32.000000,0.000000,-0.777778,-0.833333,-814.543124,-811.951894,-0.522727,-0.390937,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,24.000000,3.000000,7.000000,0.000000,104095.000000,104095.000000,3.000000,3.000000,180.000000,180.000000,22.700000,22.700000,70.000000,70.000000,124.000000,124.000000,410693.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.176471,0.000000,0.000000,0.000000,0.176471,39.000000,32.000000,72.000000,0.514286,39.000000,32.000000,71.000000,0.514286,1692.908358,1692.912365,-87.319274,1573.112515,1572.958479,-71.702925,1618.388195,1618.067000,-71.287089,0.952255,-10.519773,-10.510780,5.615169,5.613578,0.958467,0.957114,98.000000,74.000000,174.000000,0.534552,98.000000,74.000000,174.000000,0.534375,34.000000,29.000000,65.000000,0.516484,34.000000,29.000000,65.000000,0.516129,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,11.000000,25.000000,9.000000,0.480000,11.000000,25.000000,9.000000,0.480000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,11.000000,25.000000,8.000000,0.480000,11.000000,25.000000,8.000000,0.480000,22.000000,44.000000,19.000000,0.500000,22.000000,44.000000,19.000000,0.500000,0.038462,0.032402,0.579648,0.662991,0.481177,0.594583,0.038375,0.032381,0.579542,0.662879,0.481239,0.594480,41.000000,41.000000,0.574257,0.574468,0.000000,0.000000,0.592649,0.592593,18.000000,18.000000,0.369086,0.390977,41.000000,0.369185,0.390967,41.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,72.000000,72.000000,-86.000000,0.530303,-171.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.700000,-5.000000,0.000000,0.000000,-5.000000,1.000000,-0.015987,-0.015968,-213.815693,-213.837589,-0.004893,-0.004835,0.000000,0.000000,23.000000,23.000000,10.000000,10.000000,12.000000,12.000000,0.441489,0.441176,0.000000,0.000000,0.000000,0.000000,0.555556,0.556818
50%,32.000000,227.000000,3.000000,8.000000,0.000000,105676.000000,105678.000000,5.000000,5.000000,185.000000,185.000000,25.300000,25.300000,168.000000,168.000000,317.000000,316.000000,611707.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.393258,0.000000,2.000000,2.000000,0.395833,119.000000,93.000000,213.000000,0.558621,118.000000,92.000000,212.000000,0.558541,1790.716592,1790.692182,-0.002193,1643.666145,1643.719468,0.030970,1688.592795,1688.694333,0.000000,0.999999,0.684833,0.651522,9.140871,9.152119,1.000000,1.000019,192.000000,138.000000,332.000000,0.571165,191.000000,138.000000,331.000000,0.571146,91.000000,66.000000,158.000000,0.575758,91.000000,66.000000,158.000000,0.575875,5.000000,10.000000,4.000000,0.500000,5.000000,10.000000,4.000000,0.500000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,5.000000,10.000000,4.000000,0.600000,5.000000,10.000000,4.000000,0.600000,14.000000,25.000000,10.000000,0.560000,14.000000,25.000000,10.000000,0.560000,32.000000,58.000000,24.000000,0.568627,32.000000,58.000000,24.000000,0.568182,0.055215,0.039495,0.605870,0.691413,0.498555,0.614225,0.055157,0.039473,0.605851,0.691278,0.498496,0.614108,128.000000,128.000000,0.622807,0.622857,0.000000,0.000000,0.614743,0.614685,59.000000,59.000000,0.385586,0.411765,128.000000,0.385699,0.411765,128.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.000000,0.000000,2.000000,2.000000,0.666667,0.666667,0.600000,0.600000,0.000000,0.000000,0.000000,0.000000,175.000000,175.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.010125,0.010256,-129.271615,-128.952350,0.000772,0.000770,2.000000,2.000000,68.000000,68.000000,34.000000,34.000000,32.000000,32.000000,0.510638,0.510730,0.000000,0.000000,0.000000,0.000000,0.620253,0.620690
75%,48.000000,288.000000,3.000000,9.000000,1.000000,134329.000000,134329.000000,8.000000,8.000000,188.000000,188.000000,28.200000,28.200000,356.000000,355.000000,686.000000,686.000000,762765.500000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,6.000000,20.000000,27.000000,0.500000,6.000000,20.000000,26.000000,0.500000,225.000000,168.000000,395.000000,0.602339,224.000000,168.000000,394.000000,0.602649,1884.823102,1884.539090,87.709516,1704.832035,1705.093947,71.266327,1753.471647,1753.519622,71.188719,1.050331,13.009769,12.921115,15.232643,15.231818,1.043201,1.044527,312.000000,219.000000,533.000000,0.606511,311.000000,219.000000,532.000000,0.606695,173.000000,117.000000,290.000000,0.620939,173.000000,117.000000,290.000000,0.621181,7.000000,10.000000,6.000000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,7.000000,10.000000,6.000000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,42.000000,69.000000,28.000000,0.633803,42.000000,69.000000,28.000000,0.632911,0.077456,0.047893,0.633143,0.719776,0.512804,0.633576,0.077474,0.047844,0.633200,0.719552,0.512775,0.633399,295.000000,294.000000,0.671233,0.670886,67.000000,67.000000,0.637106,0.636859,146.000000,147.000000,0.402266,0.432412,295.000000,0.402195,0.432432,294.000000,3.000000,3.000000,8.000000,8.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.000000,0.714286,0.727273,0.000000,0.000000,0.000000,0.000000,378.000000,379.000000,86.000000,1.885988,171.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.700000,5.000000,1.000000,1.000000,5.000000,1.000000,0.029917,0.029984,-64.630199,-64.689699,0.006863,0.006867,5.000000,5.000000,152.000000,152.000000,83.000000,83.000000,68.000000,68.000000,0.583333,0.583333,142.000000,142.000000,95.000000,95.000000,0.682540,0.682540

In [13]:
matches_df = matches_df.drop([
    "match_num",
    "match_id",
    "playerA_id",
    "playerB_id",
    "round_rank", 
    'playerA_rank', 
    "playerB_rank"
], axis = 1, errors='ignore')

In [14]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259423 entries, 116 to 855140
Columns: 210 entries, tourney_id to playerB_match_p
dtypes: float64(90), int64(110), object(10)
memory usage: 417.6+ MB

In [15]:
matches_df = matches_df.drop(["tourney_id", "tourney_name"], axis = 1)

In [16]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259423 entries, 116 to 855140
Columns: 208 entries, surface to playerB_match_p
dtypes: float64(90), int64(110), object(8)
memory usage: 413.7+ MB

## *Resetting Index*

In [17]:
matches_df = matches_df.reset_index(drop=True)

In [18]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259423 entries, 0 to 259422
Columns: 208 entries, surface to playerB_match_p
dtypes: float64(90), int64(110), object(8)
memory usage: 411.7+ MB

# **Test/Validation/Train Split**

In [19]:
matches_df_final_cleaned = matches_df.copy()

In [20]:
n = len(matches_df)

train_end = int(0.70 * n)
val_end   = int(0.80 * n)

train_df = matches_df.iloc[:train_end]
val_df   = matches_df.iloc[train_end:val_end]
test_df  = matches_df.iloc[val_end:]

In [21]:
#test-1
print(train_df.shape)
print(val_df.shape)
print(test_df.shape)

print(train_df["tourney_date"].min(), train_df["tourney_date"].max())
print(val_df["tourney_date"].min(), val_df["tourney_date"].max())
print(test_df["tourney_date"].min(), test_df["tourney_date"].max())

(181596, 208)
(25942, 208)
(51885, 208)
1990-12-31 2022-07-25
2022-07-25 2024-07-01
2024-07-01 2026-06-01

In [22]:
train_df = train_df.drop(['tourney_date'], axis = 1)
val_df = val_df.drop(['tourney_date'], axis = 1)
test_df = test_df.drop(['tourney_date'], axis = 1)

# **Preprocessing**

In [23]:
target_cols = ['playerA_match_p', 'playerB_match_p']

X_train = train_df.drop(columns= target_cols)
y_train = train_df[target_cols]

X_val = val_df.drop(columns= target_cols)
y_val = val_df[target_cols]

X_test = test_df.drop(columns= target_cols)
y_test = test_df[target_cols]

## *Identifying Column Types*

In [24]:
categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

numeric_cols = X_train.select_dtypes(include=["number"]).columns.tolist()

In [25]:
print(categorical_cols)

['surface', 'tourney_level', 'round', 'playerA_entry', 'playerB_entry', 'playerA_hand', 'playerB_hand']

## *Filling Missing Values*

In [26]:
y_train.describe()

       playerA_match_p  playerB_match_p
count    181596.000000    181596.000000
mean          0.621069         0.620975
std           0.095395         0.095272
min           0.000000         0.000000
25%           0.560000         0.560440
50%           0.623188         0.623377
75%           0.684932         0.684211
max           1.000000         1.000000

In [27]:
pd.set_option("display.max_columns", None)
X_train.describe()

,draw_size,best_of,playerA_wins,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank_points,playerB_rank_points,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney
count,181596.000000,181596.000000,181596.000000,63667.000000,63213.000000,181596.000000,181596.000000,181596.000000,181596.000000,177993.000000,177895.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.00000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,178799.000000,178799.000000,178799.000000,178799.000000,178798.000000,178799.000000,178805.000000,178805.000000,178805.000000,178805.000000,178803.000000,178805.000000,181596.000000,181596.000000,65524.000000,65526.000000,181596.000000,181596.000000,176399.000000,176412.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,15274.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,176399.000000,176412.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000
mean,48.973700,3.179552,0.499807,6.406207,6.378308,185.184211,185.171920,25.750558,25.738016,732.609530,731.915034,0.550756,0.546956,1.097711,0.003800,0.307000,0.303514,0.610515,0.003486,0.484361,0.481464,0.965825,0.002897,10.998458,19.067865,30.066323,0.310740,10.952262,18.926832,29.879094,0.310564,161.135174,118.823355,279.958529,0.561207,160.425158,118.231563,278.656722,0.561102,1821.155198,1820.819361,0.335838,1657.958637,1658.046488,-0.087851,1706.917605,1706.878350,0.039256,1.003739,1.401060,1.402411,12.226518,12.225717,1.002556,1.002569,231.733662,162.881358,394.615019,0.573653,231.086467,162.404745,393.491211,0.573186,120.886705,81.444999,202.331703,0.570031,120.780794,81.340487,202.121280,0.569831,5.475947,9.915196,4.43925,0.550589,5.474102,9.910852,4.436750,0.550373,13.872426,24.602128,10.729702,0.560638,13.859298,24.588950,10.729653,0.560037,5.427025,9.714526,4.287501,0.554634,5.424145,9.712758,4.288613,0.554176,13.480176,23.554357,10.074181,0.564455,13.459663,23.540056,10.080393,0.563588,33.194404,56.122866,22.928462,0.568881,33.144998,56.056477,22.911479,0.568479,0.063251,0.040983,0.602913,0.695851,0.496890,0.616077,0.063190,0.040959,0.602816,0.695652,0.496806,0.615904,200.230682,199.446866,0.623140,0.623167,65.749400,65.708799,0.617079,0.616922,100.053630,99.927245,0.383163,0.408472,200.230682,0.383121,0.408676,199.446866,1.997148,1.991426,5.454592,5.451552,1.492037,1.487615,3.470445,3.468375,0.505110,0.503811,1.984146,1.983177,0.632757,0.632650,0.562019,0.561456,0.014549,0.015138,0.019841,0.020380,227.143852,228.131754,-0.987902,2.602230,1.037385,0.056158,0.055188,0.157525,0.155141,0.287512,0.287165,0.419051,0.418809,0.012542,0.012291,0.350597,0.348097,0.156017,0.915890,-0.003622,-0.003355,-163.196562,-162.772873,0.000541,0.000535,4.779417,4.797138,106.598119,106.201921,59.156132,58.940291,47.441987,47.261630,0.506544,0.505917,86.781911,86.748442,48.160770,48.133672
std,31.710339,0.571723,0.500001,5.484150,5.448004,6.631787,6.757761,4.007567,4.006646,1148.912632,1159.116445,1.235530,1.225779,2.080309,1.315466,0.813163,0.803782,1.329420,0.920457,0.901316,0.897238,1.408763,1.118124,27.624643,28.370684,52.203740,0.201720,27.653137,28.237342,52.105813,0.202705,130.985007,90.840187,215.845014,0.100933,131.048141,90.576198,215.540214,0.101731,158.441105,158.753268,151.586564,105.247398,105.797302,119.657995,113.421687,113.962779,120.638266,0.084702,27.721829,27.735950,10.613989,10.662258,0.071211,0.072461,150.471170,100.632030,243.595068,0.084179,150.247229,100.394605,243.124674,0.085676,103.314600,64.743240,164.602444,0.113186,102.935247,64.582986,164.090923,0.113943,1.820291,0.801730,1.77480,0.178708,1.825628,0.820400,1.775836,0.179355,3.627171,2.690920,3.355766,0.136117,3.647841,2.742511,3.363917,0.137156,1.928540,1.427229,1.805720,0.182706,1.935045,1.436745,1.810108,0.183381,4.350871,4.895754,3.626613,0.145664,4.361525,4.915839,3.631417,0.146283,14.857565,19.286168,7.351586,0.117201,14.861109,19.300817,7.370441,0.117836,0.032223,0.013326,0.042771,0.045344,0.031668,0.033433,0.032263,0.013431,0.042894,0.045626,0.031822,0.033699,193.411113,193.024297,0.077590,0.077369,156.572207,156.759805,0.038205,0.038260,109.770645,109.485284,0.032234,0.051903,193.411113,0.032321,0.052723,193.024297,1.861717,1.862766,3.447615,3.446434,1.660269,1.661913,2.930058,2.931532,0.527481,0.528858,1.140446,1.138039,0.301543,0.301039,0.249082,0.249945,0.119738,0.122102,0.139453,0.141298,342.031098,344.711291,388.696615,12.514071,1336.089941,0.230226,0.228348,0.364297,0.362040,0.452603,0.452440,0.493405,0.493365,5.485216,9.286042,0.477158,0.476368,7.768862,0.277553,0.080329,0.080487,107.360238,107.091716,0.019844,0.019760,7.386417,7.436478,107.093979,106.726983,64.747006,64.539314,45.510501,45.347389,0.147283,0.147772,119.724186,120.667928,53.265042,54.374335
min,2.000000,3.000000,0.000000,1.000000,1.000000,3.000000,3.000000,14.400000,14.300000,1.000000,1.000000,0.000000,0.000000,0.000000,-23.000000,0.000000,0.000000,0.000000,-20.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1147.030234,1145.156568,-820.971471,1167.746944,1182.350079,-686.655177,1166.145429,1182.350079,-646.767833,0.583761,-444.281549,-437.069233,0.000000,0.000000,0.643244,0.672065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.276596,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140351,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2267.000000,0.000441,-16641.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-27.400000,-195.000000,0.000000,0.000000,-32.000000,0.000000,-0.777778,-0.833333,-814.543124,-811.951894,-0.351567,-0.326079,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,3.000000,0.000000,3.000000,3.000000,180.000000,180.000000,22.800000,22.800000,189.000000,189.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156532,0.000000,0.000000,0.000000,0.153846,54.000000,42.000000,96.000000,0.524867,53.000000,41.000000,95.000000,0.524590,1732.672056,1732.518282,-87.607146,1593.463914,1593.505156,-71.650621,1643.952266,1643.889212,-71.003947,0.952885,-10.739979,-10.772064,5.805868,5.801942,0.959165,0.957601,120.000000,86.000000,208.000000,0.545098,119.000000,86.000000,207.000000,0.544910,39.000000,30.000000,71.000000,0.531250,39.000000,30.000000,71.000000,0.531250,4.000000,10.000000,3.00000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,9.000000,0.480000,12.000000,25.000000,9.000000,0.480000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,8.000000,0.480000,11.000000,25.000000,8.000000,0.480000,24.000000,46.000000,19.000000,0.507937,24.000000,46.000000,19.000000,0.507937,0.040698,0.032395,0.575653,0.668989,0.483821,0.598131,0.040600,0.032367,0.575540,0.668796,0.483856,0.598036,48.000000,47.000000,0.576271,0.576471,0.000000,0.000000,0.596220,0.596115,19.000000,19.000000,0.367236,0.389401,48.000000,0.367248,0.389474,47.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,55.000000,55.000000,-69.000000,0.502070,-236.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.600000,-5.000000,0.000000,0.000000,-4.000000,1.000000,-0.019782,-0.019466,-230.578829,-230.102590,-0.005615,-0.005581,0.000000,0.000000,24.000000,24.000000,11.000000,11.000000,12.000000,12.000000,0.444444,0.444444,0.000000,0.000000,0.000000,0.000000
50%,32.000000,3.000000,0.000000,5.000000,5.000000,185.000000,185.000000,25.500000,25.500000,423.000000,422.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5.000000,6.000000,0.327434,1.000000,5.000000,6.000000,0.329377,137.000000,104.000000,242.000000,0.562937,136.000000,103.000000,241.000000,0.562660,1815.445841,1815.275263,0.099714,1657.931016,1657.833761,0.034218,1704.671077,1704.661933,0.012857,1.000056,0.809155,0.734485,9.176183,9.187770,1.000007,1.000020,211.000000,148.000000,362.000000,0.577000,210.000000,148.000000,360.000000,0.576772,96.000000,68.000000,165.000000,0.583106,96.000000,67.000000,165.000000,0.583051,6.000000,10.000000,4.00000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,6.000000,10.000000,4.000000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,10.000000,0.560000,14.000000,25.000000,10.000000,0.560000,33.000000,59.000000,24.000000,0.574074,33.000000,59.000000,24.000000,0.574074,0.057478,0.039308,0.602144,0.695161,0.500000,0.616831,0.057401,0.039279,0.602094,0.695047,0.500000,0.616780,141.000000,141.000000,0.624217,0.623853,0.000000,0.000000,0.617488,0.617457,60.000000,60.000000,0.383641,0.409677,141.000000,0.383651,0.409729,141.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.000000,0.000000,2.000000,2.000000,0.666667,0.666667,0.600000,0.600000,0.000000,0.000000,0.000000,0.000000,126.000000,127.000000,-1.000000,0.995726,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.010448,0.010602,-149.336080,-148.803840,0.000926,0.000908,2.000000,2.000000,70.000000,70.000000,36.000000,36.000000,33.000000,33.000000,0.511658,0.511628,0.000000,0.000000,0.000000,0.000000
75%,56.000000,3.000000,1.000000,8.000000,8.000000,188.000000,188.000000,28.400000,28.400000,806.000000,804.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,10.000000,27.000000,38.000000,0.500000,10.000000,27.000000,37.000000,0.500000,238.000000,175.000000,415.000000,0.603960,237.000000,174.000000,413.000000,0.604120,1907.365680,1906.462601,88.564130,1717.594293,1717.840089,71.222895,1767.537406,1767.572022,71.046907,1.049901,12.936097,12.830367,15.032104,15.036800,1.042657,1.044016,322.000000,224.000000,549.000000,0.611486,321.000000,224.000000,548.000000,0.611465,177.000000,118.000000,296.000000,0.626437,178.000000,118.000000,296.000000,0.626775,7.000000,10.000000,6.00000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,7.000000,10.000000,5.000000,0.700000,7.000000,10.000000,5.000000,0.700000,16.000000,25.000000,12.000000,0.640000,16.000000,25.000000,12.000000,0.640000,42.000000,69.000000,28.000000,0.640000,42.000000,69.000000,28.000000,0.639535,0.080593,0.047583,0.628777,0.724411,0.513955,0.635454,0.080515,0.047491,0.628919,0.724366,0.513919,0.635228,301.000000,300.000000,0.671875,0.671642,80.000000,80.000000,0.638914,0.638726,145.000000,146.000000,0.399591,0.429407,301.000000,0.399510,0.429546,300.000000,3.000000,3.000000,8.000000,8.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.000000,0.727273,0.727273,0.000000,0.000000,0.000000,0.000000,262.000000,262.000000,69.000000,1.989204,238.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,3.700000,5.000000,1.000000,1.000000,5.000000,1.000000,0.031185,0.031286,-84.214470,-84.321404,0.007077,0.007039,6.000000,6.000000,159.000000,158.000000,86.000000,86.000000,70.000000,70.000000,0.585714,0.585034,139.000000,140.000000,94.000000,94.000000

### playerA_entry & playerB_entry

In [28]:
#check-1
pd.set_option("display.max_columns", None)
X_train[categorical_cols].describe()

,surface,tourney_level,round,playerA_entry,playerB_entry,playerA_hand,playerB_hand
count,181596,181596,181596,33538,33575,181596,181596
unique,4,6,13,19,18,4,4
top,Hard,C,R32,Q,Q,R,R
freq,91731,73902,62083,15239,15312,152512,152759

In [29]:
#check-2
X_train['playerA_entry'].unique()

array([nan, 'Q', 'WC', 'LL', 'S', 'PR', 'AL', '1)', '6)', '6) A', '3)',
       '8)', '2) A', 'SE', 'ALT', 'Alt', 'P', 'ITF', 'J', 'A'],
      dtype=object)

In [30]:
#check-3
X_train["playerA_entry"].value_counts(dropna=False)

playerA_entry
NaN     148058
Q        15239
WC       13405
LL        2008
Alt       1122
PR         642
ITF        391
SE         348
ALT        294
S           31
P           23
AL          18
3)           4
A            3
6) A         3
1)           2
6)           2
8)           1
2) A         1
J            1
Name: count, dtype: int64

In [31]:
entry_map = {
    "Alt": "ALT",
    "AL": "ALT",
    "L": "LL",

    "1)": np.nan,
    "3)": np.nan,
    "6)": np.nan,
    "8)": np.nan,
    "2) A": np.nan,
    "6) A": np.nan
}

X_train["playerA_entry"] = X_train["playerA_entry"].replace(entry_map).fillna("NONE")

X_train["playerB_entry"] = X_train["playerB_entry"].replace(entry_map).fillna("NONE")

X_test["playerA_entry"] = X_test["playerA_entry"].replace(entry_map).fillna("NONE")
X_test["playerB_entry"] = X_test["playerB_entry"].replace(entry_map).fillna("NONE")

X_val["playerA_entry"] = X_val["playerA_entry"].replace(entry_map).fillna("NONE")
X_val["playerB_entry"] = X_val["playerB_entry"].replace(entry_map).fillna("NONE")

In [32]:
#test-1
X_train['playerA_entry'].value_counts(dropna= False)

playerA_entry
NONE    148071
Q        15239
WC       13405
LL        2008
ALT       1434
PR         642
ITF        391
SE         348
S           31
P           23
A            3
J            1
Name: count, dtype: int64

In [33]:
#test-2
X_train['playerB_entry'].value_counts(dropna= False)

playerB_entry
NONE    148033
Q        15312
WC       13458
LL        2003
ALT       1445
PR         661
ITF        335
SE         294
S           27
P           22
A            4
I            2
Name: count, dtype: int64

In [34]:
other_cat = ['NG', 'JR', 'CO', 'S', 'P', 'A', 'I', 'UP', "W", 'J']

X_train['playerA_entry'] = X_train['playerA_entry'].replace(other_cat, 'OTHER')
X_train['playerB_entry'] = X_train['playerB_entry'].replace(other_cat, 'OTHER')

X_test['playerA_entry'] = X_test['playerA_entry'].replace(other_cat, 'OTHER')
X_test['playerB_entry'] = X_test['playerB_entry'].replace(other_cat, 'OTHER')

X_val['playerA_entry'] = X_val['playerA_entry'].replace(other_cat, 'OTHER')
X_val['playerB_entry'] = X_val['playerB_entry'].replace(other_cat, 'OTHER')

In [35]:
#test-3
X_train['playerB_entry'].value_counts(dropna= False)

playerB_entry
NONE     148033
Q         15312
WC        13458
LL         2003
ALT        1445
PR          661
ITF         335
SE          294
OTHER        55
Name: count, dtype: int64

### playerA_seed and playerB_seed

In [36]:
#check-1
X_train[['playerA_seed', 'playerB_seed']].describe()

       playerA_seed  playerB_seed
count  63667.000000  63213.000000
mean       6.406207      6.378308
std        5.484150      5.448004
min        1.000000      1.000000
25%        3.000000      3.000000
50%        5.000000      5.000000
75%        8.000000      8.000000
max       35.000000     35.000000

In [37]:
MAX_SEED = max(X_train['playerA_seed'].max(), X_train['playerB_seed'].max())

X_train['playerA_seed'] = X_train['playerA_seed'].fillna(MAX_SEED + 1, axis= 0)
X_train['playerB_seed'] = X_train['playerB_seed'].fillna(MAX_SEED + 1, axis= 0)

X_test['playerA_seed'] = X_test['playerA_seed'].fillna(MAX_SEED + 1, axis= 0)
X_test['playerB_seed'] = X_test['playerB_seed'].fillna(MAX_SEED + 1, axis= 0)

X_val['playerA_seed'] = X_val['playerA_seed'].fillna(MAX_SEED + 1, axis= 0)
X_val['playerB_seed'] = X_val['playerB_seed'].fillna(MAX_SEED + 1, axis= 0)

In [38]:
#test-1
X_train[['playerA_seed', 'playerB_seed']].describe()

        playerA_seed   playerB_seed
count  181596.000000  181596.000000
mean       25.624507      25.688782
std        14.489474      14.472293
min         1.000000       1.000000
25%         7.000000       7.000000
50%        36.000000      36.000000
75%        36.000000      36.000000
max        36.000000      36.000000

### playerA_rank_points and playerB_rank_points

In [39]:
#check-1
X_train[['playerA_rank_points', 'playerB_rank_points']].describe()

       playerA_rank_points  playerB_rank_points
count        177993.000000        177895.000000
mean            732.609530           731.915034
std            1148.912632          1159.116445
min               1.000000             1.000000
25%             189.000000           189.000000
50%             423.000000           422.000000
75%             806.000000           804.000000
max           16790.000000         16950.000000

In [40]:
MIN_RANK_POINTS = 0

X_train['playerA_rank_points'] = X_train['playerA_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)
X_train['playerB_rank_points'] = X_train['playerB_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)

X_test['playerA_rank_points'] = X_test['playerA_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)
X_test['playerB_rank_points'] = X_test['playerB_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)

X_val['playerA_rank_points'] = X_val['playerA_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)
X_val['playerB_rank_points'] = X_val['playerB_rank_points'].fillna(MIN_RANK_POINTS, axis = 0)

In [41]:
#test-1
X_train[['playerA_rank_points', 'playerB_rank_points']].describe()

       playerA_rank_points  playerB_rank_points
count        181596.000000        181596.000000
mean            718.074010           716.998309
std            1142.036751          1151.895827
min               0.000000             0.000000
25%             179.000000           178.000000
50%             411.000000           411.000000
75%             795.000000           791.000000
max           16790.000000         16950.000000

### Serve/Return Percentage Features

In [42]:
#check-1
X_train[['playerA_ace_pct', 'playerA_df_pct', 'playerA_1stIn_pct', 'playerA_1stWon_pct', 'playerA_2ndWon_pct', 'playerA_career_p',
         'playerB_ace_pct', 'playerB_df_pct', 'playerB_1stIn_pct', 'playerB_1stWon_pct', 'playerB_2ndWon_pct', 'playerB_career_p']].describe()

,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p
count,178799.000000,178799.000000,178799.000000,178799.000000,178798.000000,178799.000000,178805.000000,178805.000000,178805.000000,178805.000000,178803.000000,178805.000000
mean,0.063251,0.040983,0.602913,0.695851,0.496890,0.616077,0.063190,0.040959,0.602816,0.695652,0.496806,0.615904
std,0.032223,0.013326,0.042771,0.045344,0.031668,0.033433,0.032263,0.013431,0.042894,0.045626,0.031822,0.033699
min,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.276596,0.000000,0.000000,0.000000
25%,0.040698,0.032395,0.575653,0.668989,0.483821,0.598131,0.040600,0.032367,0.575540,0.668796,0.483856,0.598036
50%,0.057478,0.039308,0.602144,0.695161,0.500000,0.616831,0.057401,0.039279,0.602094,0.695047,0.500000,0.616780
75%,0.080593,0.047583,0.628777,0.724411,0.513955,0.635454,0.080515,0.047491,0.628919,0.724366,0.513919,0.635228
max,0.297297,0.300000,1.000000,1.000000,1.000000,0.872727,0.333333,0.325000,1.000000,1.000000,0.888889,1.000000

In [43]:
serve_cols = ['playerA_ace_pct', 'playerA_df_pct', 'playerA_1stIn_pct', 'playerA_1stWon_pct', 'playerA_2ndWon_pct', 'playerA_career_p',
         'playerB_ace_pct', 'playerB_df_pct', 'playerB_1stIn_pct', 'playerB_1stWon_pct', 'playerB_2ndWon_pct', 'playerB_career_p']

In [44]:
means = X_train[serve_cols].mean()

X_train[serve_cols] = X_train[serve_cols].fillna(means)

X_test[serve_cols] = X_test[serve_cols].fillna(means)
X_val[serve_cols] = X_val[serve_cols].fillna(means)

In [45]:
#test-1
X_train[['playerA_ace_pct', 'playerA_df_pct', 'playerA_1stIn_pct', 'playerA_1stWon_pct', 'playerA_2ndWon_pct', 'playerA_career_p',
         'playerB_ace_pct', 'playerB_df_pct', 'playerB_1stIn_pct', 'playerB_1stWon_pct', 'playerB_2ndWon_pct', 'playerB_career_p']].describe()

,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p
count,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000
mean,0.063251,0.040983,0.602913,0.695851,0.496890,0.616077,0.063190,0.040959,0.602816,0.695652,0.496806,0.615904
std,0.031974,0.013223,0.042441,0.044993,0.031423,0.033175,0.032014,0.013328,0.042563,0.045274,0.031576,0.033439
min,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.276596,0.000000,0.000000,0.000000
25%,0.040957,0.032505,0.576155,0.669526,0.484150,0.598451,0.040846,0.032476,0.576067,0.669274,0.484155,0.598367
50%,0.058053,0.039552,0.602855,0.695809,0.499612,0.616290,0.057978,0.039500,0.602816,0.695652,0.499528,0.616228
75%,0.080119,0.047418,0.628240,0.723750,0.513713,0.635105,0.080083,0.047323,0.628406,0.723700,0.513662,0.634845
max,0.297297,0.300000,1.000000,1.000000,1.000000,0.872727,0.333333,0.325000,1.000000,1.000000,0.888889,1.000000

### 'p' Features

In [46]:
#check-1
X_train[['playerA_matchup_p', 'playerB_matchup_p', 'playerA_surface_p', 'playerB_surface_p' ]].describe()

,playerA_matchup_p,playerB_matchup_p,playerA_surface_p,playerB_surface_p
count,65524.000000,65526.000000,176399.000000,176412.000000
mean,0.623140,0.623167,0.617079,0.616922
std,0.077590,0.077369,0.038205,0.038260
min,0.000000,0.000000,0.140351,0.000000
25%,0.576271,0.576471,0.596220,0.596115
50%,0.624217,0.623853,0.617488,0.617457
75%,0.671875,0.671642,0.638914,0.638726
max,1.000000,1.000000,0.900000,1.000000

In [47]:
means = X_train[['playerA_matchup_p', 'playerB_matchup_p', 
                 'playerA_surface_p', 'playerB_surface_p' ]].mean()

X_train[['playerA_matchup_p', 'playerB_matchup_p', 
         'playerA_surface_p', 'playerB_surface_p' ]] = X_train[['playerA_matchup_p', 'playerB_matchup_p', 
                                                                'playerA_surface_p', 'playerB_surface_p' ]].fillna(means)

X_test[['playerA_matchup_p', 'playerB_matchup_p', 
         'playerA_surface_p', 'playerB_surface_p' ]] = X_test[['playerA_matchup_p', 'playerB_matchup_p', 
                                                                'playerA_surface_p', 'playerB_surface_p' ]].fillna(means)
X_val[['playerA_matchup_p', 'playerB_matchup_p', 
         'playerA_surface_p', 'playerB_surface_p' ]] = X_val[['playerA_matchup_p', 'playerB_matchup_p', 
                                                                'playerA_surface_p', 'playerB_surface_p' ]].fillna(means)

In [48]:
#test-1
X_train[['playerA_matchup_p', 'playerB_matchup_p', 'playerA_surface_p', 'playerB_surface_p' ]].describe()

,playerA_matchup_p,playerB_matchup_p,playerA_surface_p,playerB_surface_p
count,181596.000000,181596.000000,181596.000000,181596.000000
mean,0.623140,0.623167,0.617079,0.616922
std,0.046607,0.046475,0.037655,0.037710
min,0.000000,0.000000,0.140351,0.000000
25%,0.623140,0.623167,0.596969,0.596852
50%,0.623140,0.623167,0.617079,0.616922
75%,0.623140,0.623167,0.638158,0.637980
max,1.000000,1.000000,0.900000,1.000000

### seed_diff

In [49]:
#check-1
X_train["seed_diff"].describe()

count    15274.000000
mean         0.156017
std          7.768862
min        -32.000000
25%         -4.000000
50%          1.000000
75%          5.000000
max         31.000000
Name: seed_diff, dtype: float64

In [50]:
X_train["seed_diff"] = X_train["playerA_seed"] - X_train["playerB_seed"]

X_test["seed_diff"] = X_test["playerA_seed"] - X_test["playerB_seed"]
X_val["seed_diff"] = X_val["playerA_seed"] - X_val["playerB_seed"]

In [51]:
#test-1
X_train["seed_diff"].describe()

count    181596.000000
mean         -0.064275
std          22.047887
min         -35.000000
25%         -21.000000
50%           0.000000
75%          20.000000
max          35.000000
Name: seed_diff, dtype: float64

### serve_specialization

In [52]:

X_train['playerA_serve_specialization'] = X_train['playerA_career_p'] - X_train['playerA_surface_p']
X_train['playerB_serve_specialization'] = X_train['playerB_career_p'] - X_train['playerB_surface_p']


X_val['playerA_serve_specialization'] = X_val['playerA_career_p'] - X_val['playerA_surface_p']
X_val['playerB_serve_specialization'] = X_val['playerB_career_p'] - X_val['playerB_surface_p']


X_test['playerA_serve_specialization'] = X_test['playerA_career_p'] - X_test['playerA_surface_p']
X_test['playerB_serve_specialization'] = X_test['playerB_career_p'] - X_test['playerB_surface_p']

In [53]:
X_train[['playerA_serve_specialization', 'playerB_serve_specialization']].describe()

       playerA_serve_specialization  playerB_serve_specialization
count                 181596.000000                 181596.000000
mean                      -0.001002                     -0.001019
std                        0.020990                      0.021094
min                       -0.342079                     -0.440452
25%                       -0.007142                     -0.007104
50%                       -0.001002                     -0.001019
75%                        0.005406                      0.005359
max                        0.351567                      0.326079

### *Final Check*

In [54]:
pd.set_option("display.max_columns", None)
X_train.describe()

,draw_size,best_of,playerA_wins,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank_points,playerB_rank_points,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney
count,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.00000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000
mean,48.973700,3.179552,0.499807,25.624507,25.688782,185.184211,185.171920,25.750558,25.738016,718.074010,716.998309,0.550756,0.546956,1.097711,0.003800,0.307000,0.303514,0.610515,0.003486,0.484361,0.481464,0.965825,0.002897,10.998458,19.067865,30.066323,0.310740,10.952262,18.926832,29.879094,0.310564,161.135174,118.823355,279.958529,0.561207,160.425158,118.231563,278.656722,0.561102,1821.155198,1820.819361,0.335838,1657.958637,1658.046488,-0.087851,1706.917605,1706.878350,0.039256,1.003739,1.401060,1.402411,12.226518,12.225717,1.002556,1.002569,231.733662,162.881358,394.615019,0.573653,231.086467,162.404745,393.491211,0.573186,120.886705,81.444999,202.331703,0.570031,120.780794,81.340487,202.121280,0.569831,5.475947,9.915196,4.43925,0.550589,5.474102,9.910852,4.436750,0.550373,13.872426,24.602128,10.729702,0.560638,13.859298,24.588950,10.729653,0.560037,5.427025,9.714526,4.287501,0.554634,5.424145,9.712758,4.288613,0.554176,13.480176,23.554357,10.074181,0.564455,13.459663,23.540056,10.080393,0.563588,33.194404,56.122866,22.928462,0.568881,33.144998,56.056477,22.911479,0.568479,0.063251,0.040983,0.602913,0.695851,0.496890,0.616077,0.063190,0.040959,0.602816,0.695652,0.496806,0.615904,200.230682,199.446866,0.623140,0.623167,65.749400,65.708799,0.617079,0.616922,100.053630,99.927245,0.383163,0.408472,200.230682,0.383121,0.408676,199.446866,1.997148,1.991426,5.454592,5.451552,1.492037,1.487615,3.470445,3.468375,0.505110,0.503811,1.984146,1.983177,0.632757,0.632650,0.562019,0.561456,0.014549,0.015138,0.019841,0.020380,227.143852,228.131754,-0.987902,2.602230,1.037385,0.056158,0.055188,0.157525,0.155141,0.287512,0.287165,0.419051,0.418809,0.012542,0.012291,0.350597,0.348097,-0.064275,0.915890,-0.003622,-0.003355,-163.196562,-162.772873,-0.001002,-0.001019,4.779417,4.797138,106.598119,106.201921,59.156132,58.940291,47.441987,47.261630,0.506544,0.505917,86.781911,86.748442,48.160770,48.133672
std,31.710339,0.571723,0.500001,14.489474,14.472293,6.631787,6.757761,4.007567,4.006646,1142.036751,1151.895827,1.235530,1.225779,2.080309,1.315466,0.813163,0.803782,1.329420,0.920457,0.901316,0.897238,1.408763,1.118124,27.624643,28.370684,52.203740,0.201720,27.653137,28.237342,52.105813,0.202705,130.985007,90.840187,215.845014,0.100933,131.048141,90.576198,215.540214,0.101731,158.441105,158.753268,151.586564,105.247398,105.797302,119.657995,113.421687,113.962779,120.638266,0.084702,27.721829,27.735950,10.613989,10.662258,0.071211,0.072461,150.471170,100.632030,243.595068,0.084179,150.247229,100.394605,243.124674,0.085676,103.314600,64.743240,164.602444,0.113186,102.935247,64.582986,164.090923,0.113943,1.820291,0.801730,1.77480,0.178708,1.825628,0.820400,1.775836,0.179355,3.627171,2.690920,3.355766,0.136117,3.647841,2.742511,3.363917,0.137156,1.928540,1.427229,1.805720,0.182706,1.935045,1.436745,1.810108,0.183381,4.350871,4.895754,3.626613,0.145664,4.361525,4.915839,3.631417,0.146283,14.857565,19.286168,7.351586,0.117201,14.861109,19.300817,7.370441,0.117836,0.031974,0.013223,0.042441,0.044993,0.031423,0.033175,0.032014,0.013328,0.042563,0.045274,0.031576,0.033439,193.411113,193.024297,0.046607,0.046475,156.572207,156.759805,0.037655,0.037710,109.770645,109.485284,0.032234,0.051903,193.411113,0.032321,0.052723,193.024297,1.861717,1.862766,3.447615,3.446434,1.660269,1.661913,2.930058,2.931532,0.527481,0.528858,1.140446,1.138039,0.301543,0.301039,0.249082,0.249945,0.119738,0.122102,0.139453,0.141298,342.031098,344.711291,388.696615,12.514071,1336.089941,0.230226,0.228348,0.364297,0.362040,0.452603,0.452440,0.493405,0.493365,5.485216,9.286042,0.477158,0.476368,22.047887,0.277553,0.080329,0.080487,107.360238,107.091716,0.020990,0.021094,7.386417,7.436478,107.093979,106.726983,64.747006,64.539314,45.510501,45.347389,0.147283,0.147772,119.724186,120.667928,53.265042,54.374335
min,2.000000,3.000000,0.000000,1.000000,1.000000,3.000000,3.000000,14.400000,14.300000,0.000000,0.000000,0.000000,0.000000,0.000000,-23.000000,0.000000,0.000000,0.000000,-20.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1147.030234,1145.156568,-820.971471,1167.746944,1182.350079,-686.655177,1166.145429,1182.350079,-646.767833,0.583761,-444.281549,-437.069233,0.000000,0.000000,0.643244,0.672065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.276596,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140351,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2267.000000,0.000441,-16641.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-27.400000,-195.000000,0.000000,0.000000,-35.000000,0.000000,-0.777778,-0.833333,-814.543124,-811.951894,-0.342079,-0.440452,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,3.000000,0.000000,7.000000,7.000000,180.000000,180.000000,22.800000,22.800000,179.000000,178.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156532,0.000000,0.000000,0.000000,0.153846,54.000000,42.000000,96.000000,0.524867,53.000000,41.000000,95.000000,0.524590,1732.672056,1732.518282,-87.607146,1593.463914,1593.505156,-71.650621,1643.952266,1643.889212,-71.003947,0.952885,-10.739979,-10.772064,5.805868,5.801942,0.959165,0.957601,120.000000,86.000000,208.000000,0.545098,119.000000,86.000000,207.000000,0.544910,39.000000,30.000000,71.000000,0.531250,39.000000,30.000000,71.000000,0.531250,4.000000,10.000000,3.00000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,9.000000,0.480000,12.000000,25.000000,9.000000,0.480000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,8.000000,0.480000,11.000000,25.000000,8.000000,0.480000,24.000000,46.000000,19.000000,0.507937,24.000000,46.000000,19.000000,0.507937,0.040957,0.032505,0.576155,0.669526,0.484150,0.598451,0.040846,0.032476,0.576067,0.669274,0.484155,0.598367,48.000000,47.000000,0.623140,0.623167,0.000000,0.000000,0.596969,0.596852,19.000000,19.000000,0.367236,0.389401,48.000000,0.367248,0.389474,47.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,55.000000,55.000000,-69.000000,0.502070,-236.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.600000,-5.000000,0.000000,0.000000,-21.000000,1.000000,-0.019782,-0.019466,-230.578829,-230.102590,-0.007142,-0.007104,0.000000,0.000000,24.000000,24.000000,11.000000,11.000000,12.000000,12.000000,0.444444,0.444444,0.000000,0.000000,0.000000,0.000000
50%,32.000000,3.000000,0.000000,36.000000,36.000000,185.000000,185.000000,25.500000,25.500000,411.000000,411.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5.000000,6.000000,0.327434,1.000000,5.000000,6.000000,0.329377,137.000000,104.000000,242.000000,0.562937,136.000000,103.000000,241.000000,0.562660,1815.445841,1815.275263,0.099714,1657.931016,1657.833761,0.034218,1704.671077,1704.661933,0.012857,1.000056,0.809155,0.734485,9.176183,9.187770,1.000007,1.000020,211.000000,148.000000,362.000000,0.577000,210.000000,148.000000,360.000000,0.576772,96.000000,68.000000,165.000000,0.583106,96.000000,67.000000,165.000000,0.583051,6.000000,10.000000,4.00000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,6.000000,10.000000,4.000000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,10.000000,0.560000,14.000000,25.000000,10.000000,0.560000,33.000000,59.000000,24.000000,0.574074,33.000000,59.000000,24.000000,0.574074,0.058053,0.039552,0.602855,0.695809,0.499612,0.616290,0.057978,0.039500,0.602816,0.695652,0.499528,0.616228,141.000000,141.000000,0.623140,0.623167,0.000000,0.000000,0.617079,0.616922,60.000000,60.000000,0.383641,0.409677,141.000000,0.383651,0.409729,141.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.000000,0.000000,2.000000,2.000000,0.666667,0.666667,0.600000,0.600000,0.000000,0.000000,0.000000,0.000000,126.000000,127.000000,-1.000000,0.995726,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.010448,0.010602,-149.336080,-148.803840,-0.001002,-0.001019,2.000000,2.000000,70.000000,70.000000,36.000000,36.000000,33.000000,33.000000,0.511658,0.511628,0.000000,0.000000,0.000000,0.000000
75%,56.000000,3.000000,1.000000,36.000000,36.000000,188.000000,188.000000,28.400000,28.400000,795.000000,791.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,10.000000,27.000000,38.000000,0.500000,10.000000,27.000000,37.000000,0.500000,238.000000,175.000000,415.000000,0.603960,237.000000,174.000000,413.000000,0.604120,1907.365680,1906.462601,88.564130,1717.594293,1717.840089,71.222895,1767.537406,1767.572022,71.046907,1.049901,12.936097,12.830367,15.032104,15.036800,1.042657,1.044016,322.000000,224.000000,549.000000,0.611486,321.000000,224.000000,548.000000,0.611465,177.000000,118.000000,296.000000,0.626437,178.000000,118.000000,296.000000,0.626775,7.000000,10.000000,6.00000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,7.000000,10.000000,5.000000,0.700000,7.000000,10.000000,5.000000,0.700000,16.000000,25.000000,12.000000,0.640000,16.000000,25.000000,12.000000,0.640000,42.000000,69.000000,28.000000,0.640000,42.000000,69.000000,28.000000,0.639535,0.080119,0.047418,0.628240,0.723750,0.513713,0.635105,0.080083,0.047323,0.628406,0.723700,0.513662,0.634845,301.000000,300.000000,0.623140,0.623167,80.000000,80.000000,0.638158,0.637980,145.000000,146.000000,0.399591,0.429407,301.000000,0.399510,0.429546,300.000000,3.000000,3.000000,8.000000,8.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.000000,0.727273,0.727273,0.000000,0.000000,0.000000,0.000000,262.000000,262.000000,69.000000,1.989204,238.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,3.700000,5.000000,1.000000,1.000000,20.000000,1.000000,0.031185,0.031286,-84.214470,-84.321404,0.005406,0.005359,6.000000,6.000000,159.000000,158.000000,86.000000,86.000000,70.000000,70.000000,0.585714,0.585034,139.000000,140.000000,94.000000,94.000000

In [55]:
X_test.describe()

,draw_size,best_of,playerA_wins,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank_points,playerB_rank_points,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney
count,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.00000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.00000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000,51885.000000
mean,37.043654,3.035656,0.495211,29.719649,29.735473,184.402390,184.443057,25.046320,25.054303,274.066705,274.954553,0.254910,0.255026,0.509935,-0.000116,0.180187,0.180746,0.360933,-0.000559,0.241419,0.241399,0.482818,0.000019,2.860808,5.431088,8.291896,0.413043,2.981825,5.489930,8.471755,0.415263,97.697196,79.395856,177.093052,0.513079,97.656953,79.320459,176.977412,0.513440,1664.987601,1665.320375,-0.332774,1575.088368,1575.635737,-0.547368,1602.058138,1602.541128,-0.482990,1.003877,1.664793,1.877671,12.314750,12.269973,1.002665,1.002469,156.289775,122.772805,279.062581,0.497730,156.707256,123.007806,279.715062,0.497864,96.783232,73.584793,170.368025,0.503257,97.423379,74.011217,171.434596,0.503570,4.974713,9.634191,4.659478,0.508128,4.994449,9.639742,4.645292,0.509873,12.198767,23.255893,11.057126,0.507731,12.221740,23.266166,11.044425,0.50860,4.902534,9.386354,4.483820,0.511392,4.915968,9.392599,4.476631,0.512616,11.785314,22.131965,10.346651,0.510714,11.824978,22.152510,10.327532,0.512111,26.857936,47.630471,20.772535,0.516167,26.801812,47.585699,20.783887,0.515963,0.051692,0.042515,0.618035,0.671011,0.485083,0.599297,0.051779,0.042501,0.617725,0.671123,0.485504,0.599443,155.024843,154.890489,0.621175,0.621384,28.053117,28.046757,0.601232,0.601502,92.471543,92.561434,0.393816,0.420231,155.024843,0.394050,0.420456,154.890489,1.932620,1.953647,4.893264,4.91009,1.431223,1.452693,3.074916,3.092666,0.501397,0.500954,1.818348,1.817423,0.625590,0.627767,0.551763,0.553682,0.060596,0.061058,0.060596,0.061058,697.825981,697.466050,0.359931,1.576573,-0.920690,0.011487,0.011564,0.032225,0.032456,0.062311,0.062022,0.098795,0.099085,-0.007983,-0.040667,0.211699,0.211988,-0.015823,0.947750,0.005527,0.005707,-89.899233,-89.684639,-0.001935,-0.002060,4.476265,4.528226,88.324583,88.416845,47.724082,47.751065,40.600501,40.665780,0.486474,0.487292,89.395394,89.959449,51.030296,51.353497
std,20.061248,0.264654,0.499982,12.339179,12.306937,8.638854,8.407600,4.095767,4.135591,764.154824,774.865282,0.715164,0.706336,1.184620,0.785758,0.563869,0.554503,0.906612,0.654904,0.619779,0.616716,0.985594,0.746681,15.609129,17.465989,30.970523,0.183479,16.407792,17.688262,31.927221,0.183097,119.257014,90.218864,206.559528,0.181665,119.642238,89.904889,206.391601,0.181548,181.394970,181.625704,145.434428,115.672318,115.588430,116.443255,131.988114,132.015422,120.563043,0.090757,29.181487,29.356098,10.903935,10.832017,0.077395,0.075439,152.668484,106.837656,256.100385,0.140739,153.681519,107.060849,257.154623,0.139811,103.092788,69.118440,169.981827,0.151953,104.285708,69.782464,171.753760,0.151292,2.090951,1.619301,1.941306,0.199242,2.082359,1.607457,1.932910,0.198270,4.778719,5.406941,3.979025,0.167465,4.755019,5.381341,3.951928,0.16615,2.177889,2.060459,1.974608,0.202279,2.166725,2.053477,1.960990,0.200894,5.217994,6.733405,4.173685,0.172956,5.204532,6.712771,4.143767,0.172074,16.619647,24.646965,9.724336,0.153449,16.551530,24.567414,9.684344,0.151872,0.029028,0.015542,0.043040,0.051570,0.040904,0.041142,0.029545,0.015784,0.043127,0.051347,0.040693,0.041012,192.030884,192.657026,0.038902,0.038216,83.554798,83.544163,0.044423,0.044007,118.000609,118.574601,0.037491,0.064526,192.030884,0.036972,0.064667,192.657026,1.851122,1.870548,3.519549,3.53035,1.634765,1.656127,2.862868,2.869796,0.526990,0.526918,1.206615,1.206699,0.298619,0.298692,0.257724,0.257178,0.238589,0.239439,0.238589,0.239439,610.781931,609.843615,646.354279,6.494335,799.410872,0.106561,0.106914,0.176599,0.177211,0.241722,0.241197,0.298390,0.298778,5.602355,11.863006,0.408516,0.408720,17.090501,0.222533,0.072680,0.072760,93.003781,93.114797,0.021731,0.021980,10.506880,10.855470,99.099689,98.885883,56.194457,56.184133,44.970695,44.845937,0.164642,0.164524,121.737638,123.118787,56.911355,57.681455
min,2.000000,3.000000,0.000000,1.000000,1.000000,13.000000,13.000000,14.700000,14.900000,0.000000,0.000000,0.000000,0.000000,0.000000,-11.000000,0.000000,0.000000,0.000000,-12.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1182.492005,1175.895885,-603.859293,1184.284575,1195.148880,-520.763968,1188.060137,1198.728561,-492.006999,0.688190,-237.912334,-262.072272,0.000000,0.000000,0.711294,0.713558,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000,0.153846,0.000000,0.193548,0.000000,0.000000,0.190476,0.125000,0.000000,0.200000,0.000000,0.000000,0.157895,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.066667,0.000000,0.000000,0.066667,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2237.000000,0.002729,-13639.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-48.700000,-181.000000,0.000000,0.000000,-35.000000,0.000000,-0.765957,-0.706294,-680.103385,-674.869862,-0.432039,-0.444444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,3.000000,0.000000,36.000000,36.000000,183.000000,183.000000,22.300000,22.300000,18.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.419355,0.000000,0.000000,0.000000,0.441860,11.000000,10.000000,24.000000,0.446429,11.000000,10.000000,24.000000,0.445545,1523.371004,1523.051491,-92.233446,1491.410241,1492.389798,-75.529376,1500.160479,1500.582343,-76.789843,0.946156,-10.396996,-10.088370,5.013768,5.033420,0.953577,0.953262,32.000000,39.000000,73.000000,0.444444,32.000000,39.000000,74.000000,0.444444,16.000000,20.000000,38.000000,0.444444,17.000000,20.000000,39.000000,0.444444,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,10.000000,25.000000,9.000000,0.400000,10.000000,25.000000,9.000000,0.40000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,9.000000,25.000000,8.000000,0.421053,9.000000,25.000000,8.000000,0.434783,13.000000,28.000000,14.000000,0.454545,13.000000,28.000000,14.000000,0.454545,0.029851,0.032528,0.591423,0.642130,0.471014,0.580298,0.030070,0.032485,0.591006,0.642298,0.470964,0.580231,23.000000,23.000000,0.623140,0.623167,0.000000,0.000000,0.580797,0.580943,13.000000,13.000000,0.375321,0.395215,23.000000,0.375501,0.395238,23.000000,0.000000,0.000000,2.000000,2.00000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,246.000000,245.000000,-224.000000,0.584080,-62.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.600000,-5.000000,0.000000,0.000000,0.000000,1.000000,-0.006903,-0.006449,-134.063552,-132.687881,-0.006003,-0.006070,0.000000,0.000000,19.000000,19.000000,8.000000,8.000000,10.000000,10.000000,0.416667,0.416667,0.000000,0.000000,0.000000,0.000000
50%,32.000000,3.000000,0.000000,36.000000,36.000000,185.000000,185.000000,24.500000,24.600000,78.000000,79.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.500000,45.000000,43.000000,87.000000,0.535452,46.000000,44.000000,88.000000,0.535714,1669.112826,1668.516647,-0.723298,1584.065256,1584.527309,-0.472990,1613.910666,1613.793654,-0.839374,0.999560,0.000000,0.194521,9.419350,9.395502,0.999475,0.999702,115.000000,94.000000,210.000000,0.541485,114.000000,94.000000,210.000000,0.541096,64.000000,55.000000,121.000000,0.540630,64.000000,55.000000,121.000000,0.540816,5.000000,10.000000,5.000000,0.500000,5.000000,10.000000,5.000000,0.500000,13.000000,25.000000,11.000000,0.520000,13.000000,25.000000,11.000000,0.52000,5.000000,10.000000,4.000000,0.500000,5.000000,10.000000,4.000000,0.500000,13.000000,25.000000,11.000000,0.520000,13.000000,25.000000,11.000000,0.520000,28.000000,52.000000,23.000000,0.541667,28.000000,52.000000,23.000000,0.540984,0.047824,0.040584,0.616577,0.675056,0.492929,0.604430,0.047796,0.040627,0.616306,0.675095,0.492872,0.604363,74.000000,74.000000,0.623140,0.623167,0.000000,0.000000,0.605354,0.605479,45.000000,45.000000,0.392889,0.419150,74.000000,0.392997,0.419091,74.000000,1.000000,1.000000,5.000000,5.00000,1.000000,1.000000,2.000000,2.000000,0.000000,0.000000,2.000000,2.000000,0.500000,0.500000,0.571429,0.571429,0.000000,0.000000,0.000000,0.000000,512.000000,510.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.009320,0.009615,-62.191695,-61.757378,-0.000481,-0.000539,2.000000,2.000000,55.000000,55.000000,28.000000,28.000000,26.000000,26.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,1.000000,36.000000,36.000000,188.000000,188.000000,27.400000,27.400000,228.000000,229.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.000000,1.000000,1.000000,0.500000,147.000000,121.000000,267.000000,0.600000,146.000000,121.000000,266.000000,0.600000,1786.819875,1787.799454,90.878715,1657.558607,1658.228042,73.704374,1695.018937,1695.634232,75.376744,1.055967,13.893058,13.971811,16.675076,16.687685,1.047948,1.047869,233.000000,176.000000,407.000000,0.583673,234.000000,176.000000,407.000000,0.584118,142.000000,106.000000,249.000000,0.598361,143.000000,107.000000,249.000000,0.598784,6.000000,10.000000,6.000000,0.600000,6.000000,10.000000,6.000000,0.600000,15.000000,25.000000,14.000000,0.625000,15.000000,25.000000,14.000000,0.60000,6.000000,10.000000,6.000000,0.600000,6.000000,10.000000,6.000000,0.600000,15.000000,25.000000,13.000000,0.640000,15.000000,25.000000,13.000000,0.640000,39.000000,67.000000,28.000000,0.611111,39.000000,67.000000,28.000000,0.611111,0.067929,0.049042,0.643138,0.705087,0.507642,0.625184,0.067552,0.049074,0.643224,0.704726,0.507860,0.624868,215.000000,213.000000,0.623140,0.623167,0.000000,0.000000,0.627991,0.627797,125.000000,125.000000,0.412445,0.444980,215.000000,0.412238,0.445017,213.000000,3.000000,3.000000,7.000000,7.00000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.875000,0.875000,0.714286,0.714286,0.000000,0.000000,0.000000,0.000000,946.000000,947.000000,225.000000,1.711499,62.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.600000,5.000000,0.000000,0.000000,0.000000,1.000000,0.027322,0.027507,-24.584175,-24.687485,0.002623,0.002462,4.000000,4.000000,118.000000,119.000000,66.000000,66.000000,53.000000,54.000000,0.582367,0.583333,148.000000,148.000000,98.666667,99.500000
max,128.000000,5.000000,1.000000,36.000000,36.000000,211.000000,211.000000,48.700000,72.100000,14350.000000,14350.000000,30.000000,29.000000,59.000000,19.000000,17.000000,20.000000,28.000000,17.000000,5.000000,5.000000,5.000000,5.000000,413.000000,174.000000,568.000000,1.000000,413.000000,174.000000,567.000000,1.000000,1093.000000,515.000000,1302.000000,1.000000,1091.000000,509.000000,1300.000000,1.000000,2429.886231,2428.135015,670.203008,2095.191378,2093.016453,508.416343,2187.895104,2183.902339,541.915156,1.511531,217.801596,203.436740,94.069900,111.979896,1.414275,1.372499,1250.000000,589.000000,1504.000000,1.000000,1248.000000,583.000000,1501.000000,1.000000,762.000000,417.000000,995.000000,1.000000,760.000000,418.000000,996.000000,1.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,1.000000,25.000000,25.000000,24.000000,1.000000,25.000000,25.000000,24.000000,1.00000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,1.000000,25.000000,25.000000,24.000000,1.000000,25.000000,25.000000,24.000000,1.000000,86.000000,118.000000,47.000000,1.000000,88.000000,117.000000,47.000000,1.000000,0.333333,0.333333,1.000000,1.000000,1.000000,1.000000,0.645833,0.571429,1.000000,1.000000,1.000000,1.000000,1358.000000,1355.000000,1.000000,1.000000,4821.000000,4865.000000,1.000000,1.000000,849.000000,847.000000,0.923077,1.000000,1358.000000,1.000000,1.000000,1355.000000,12.000000,11.000000,21.000000,20.00000,11.000000,11.000000,20.000000,19.000000,3.000000,3.000000,6.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2268.000000,2268.000000,2266.000000,1134.000000,13957.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,28.600000,181.000000,1.000000,1.000000,35.000000,1.000000,0.833333,0.857143,180.689959,194.257904,0.522727,0.390937,210.000000,209.000000,643.000000,644.000000,427.000000,425.000000,341.000000,342.000000,1.000000,1.000000,1452.000000,1563.000000,685.500000,1251.000000

In [56]:
X_val.describe()

,draw_size,best_of,playerA_wins,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank_points,playerB_rank_points,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney
count,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000,25942.000000
mean,43.496955,3.071853,0.497764,24.512258,24.443065,184.990286,185.065531,25.930811,25.969424,489.272030,482.757112,0.362000,0.362771,0.724771,-0.000771,0.236643,0.238301,0.474944,-0.001658,0.338139,0.337291,0.675430,0.000848,5.742117,10.624586,16.366703,0.341017,5.813160,10.688844,16.502004,0.340062,157.561984,122.408334,279.970318,0.545350,158.580603,123.094249,281.674852,0.545539,1776.986247,1776.819642,0.166605,1635.209952,1634.109864,1.100088,1677.742841,1676.922797,0.820043,1.002944,1.720315,1.499705,11.040099,11.029667,1.002525,1.002804,231.020700,168.667990,399.688690,0.561719,232.040706,169.392221,401.432927,0.562004,134.561021,94.636959,229.197980,0.560500,134.165947,94.514263,228.680210,0.559850,5.416390,9.937052,4.520661,0.542804,5.405404,9.933698,4.528294,0.541819,13.694742,24.662324,10.967582,0.551020,13.690155,24.648793,10.958639,0.551036,5.373333,9.801365,4.428032,0.544403,5.368360,9.798551,4.430190,0.544142,13.413152,23.959718,10.546565,0.552671,13.394187,23.942025,10.547837,0.552265,34.812389,60.097679,25.285290,0.558977,34.641431,59.880618,25.239187,0.558287,0.059456,0.041184,0.613103,0.687869,0.495002,0.612684,0.059555,0.041193,0.613069,0.687827,0.495099,0.612696,235.274227,237.465693,0.621916,0.622175,44.415157,44.429304,0.614083,0.614115,132.764051,133.076054,0.387131,0.412546,235.274227,0.387333,0.412385,237.465693,2.090587,2.098643,5.649372,5.632989,1.506784,1.509097,3.513607,3.501812,0.583802,0.589546,2.135764,2.131177,0.610756,0.609088,0.553290,0.552452,0.012991,0.013877,0.012991,0.013877,327.916622,329.782708,-1.866086,1.794577,6.451970,0.025326,0.024092,0.068769,0.066109,0.128171,0.124354,0.201411,0.204495,-0.038613,-0.075245,0.386709,0.389793,0.069193,0.906330,-0.001220,-0.002154,-141.776295,-142.709778,-0.001398,-0.001419,3.427376,3.426567,117.893956,118.713206,63.730360,64.206538,54.163596,54.506669,0.501483,0.502904,92.162208,91.561560,51.556436,51.306516
std,30.515835,0.372220,0.500005,14.802405,14.797964,9.060023,8.710735,4.339539,4.353703,913.495075,892.201119,0.852153,0.872571,1.428167,0.967176,0.650124,0.667519,1.074626,0.762669,0.722406,0.719917,1.150539,0.869806,23.742878,24.186709,44.524596,0.205692,24.100972,24.248192,45.004075,0.206958,131.259830,95.497494,221.875763,0.102605,132.959952,96.552713,224.387696,0.103331,149.546942,148.901453,130.811334,95.074422,94.548352,105.876401,105.519136,104.812342,105.652771,0.076289,24.310303,24.109006,8.990364,8.960479,0.064445,0.065766,159.223663,110.598778,264.245404,0.086926,160.422444,111.469973,266.109915,0.086514,111.819097,72.874082,181.734166,0.105427,112.478516,73.295839,182.696145,0.105806,1.780873,0.657551,1.733157,0.176512,1.783677,0.677013,1.734450,0.176562,3.511767,2.421633,3.222687,0.134259,3.550945,2.473756,3.257126,0.135343,1.843657,1.194500,1.748224,0.177615,1.845524,1.186109,1.747826,0.177851,3.989587,4.186135,3.424714,0.138746,4.024534,4.203952,3.451817,0.140185,14.106978,19.135326,7.674459,0.113539,14.187519,19.375041,7.795814,0.113137,0.028806,0.012767,0.038705,0.042286,0.031048,0.032724,0.028715,0.012860,0.038975,0.042316,0.031399,0.033049,218.876867,219.806052,0.043080,0.042810,102.726320,103.140061,0.036899,0.036840,137.429502,137.667204,0.029489,0.048587,218.876867,0.029370,0.049217,219.806052,1.848958,1.854407,3.390239,3.394467,1.641238,1.644582,2.852143,2.854025,0.543023,0.544871,1.167150,1.177815,0.303580,0.302547,0.241669,0.243241,0.113235,0.116983,0.113235,0.116983,352.330053,357.221638,417.179379,6.811131,971.803782,0.157116,0.153338,0.253065,0.248477,0.334286,0.329992,0.401062,0.403340,6.125543,12.331200,0.487005,0.487713,23.251622,0.291375,0.065422,0.067073,95.179038,95.703892,0.018999,0.018883,5.891377,6.118895,115.627619,116.162662,65.793075,66.065690,52.383813,52.805823,0.139382,0.140303,125.668210,125.736616,56.820389,56.680377
min,2.000000,3.000000,0.000000,1.000000,1.000000,3.000000,3.000000,14.800000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-18.000000,0.000000,0.000000,0.000000,-16.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1245.918807,1245.474411,-680.230205,1229.046371,1256.172225,-494.620457,1234.108102,1254.915762,-487.895320,0.676016,-247.124495,-250.577983,0.000000,0.000000,0.741627,0.747114,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377778,0.309524,0.090909,0.295455,0.000000,0.000000,0.355556,0.214286,0.090909,0.172414,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.295455,0.172414,0.000000,0.000000,0.096774,0.000000,0.000000,0.111111,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2241.000000,0.001845,-10734.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-23.400000,-200.000000,0.000000,0.000000,-35.000000,0.000000,-0.664234,-0.734375,-649.219897,-652.689575,-0.346942,-0.361943,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,3.000000,0.000000,7.000000,7.000000,180.000000,180.000000,22.600000,22.600000,114.000000,114.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.172414,0.000000,0.000000,0.000000,0.166667,52.000000,44.000000,98.000000,0.514531,51.250000,44.000000,97.000000,0.514859,1695.081641,1695.452648,-76.455398,1579.649227,1578.405196,-65.421222,1620.671554,1619.858048,-63.207111,0.957854,-9.328216,-9.497402,5.240726,5.237564,0.963211,0.960750,105.000000,80.000000,189.000000,0.540900,106.000000,80.000000,188.000000,0.540323,49.000000,38.000000,89.000000,0.526482,49.000000,38.000000,88.000000,0.525000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,9.000000,0.480000,12.000000,25.000000,9.000000,0.480000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,8.250000,0.480000,11.000000,25.000000,8.000000,0.480000,26.000000,52.000000,22.000000,0.500000,26.000000,51.000000,22.000000,0.500000,0.039483,0.032601,0.588397,0.662532,0.483171,0.596244,0.039508,0.032632,0.588528,0.662595,0.483508,0.596204,58.000000,58.000000,0.623140,0.623167,0.000000,0.000000,0.594375,0.594416,28.000000,28.000000,0.372483,0.393949,58.000000,0.372790,0.393705,58.000000,1.000000,1.000000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,121.000000,120.000000,-101.000000,0.585442,-130.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.200000,-6.000000,0.000000,0.000000,-26.000000,1.000000,-0.013115,-0.013472,-199.204194,-201.566677,-0.007360,-0.007482,0.000000,0.000000,26.000000,26.000000,12.000000,12.000000,14.000000,14.000000,0.450980,0.453754,0.000000,0.000000,0.000000,0.000000
50%,32.000000,3.000000,0.000000,36.000000,36.000000,185.000000,185.000000,25.500000,25.600000,237.000000,237.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.000000,1.000000,1.000000,0.500000,127.000000,98.000000,225.000000,0.555556,128.000000,100.000000,226.000000,0.555781,1772.781944,1772.882885,0.047245,1639.727409,1637.930692,1.114480,1681.043723,1680.369567,0.655633,1.000026,1.072257,0.939296,8.406386,8.484862,1.000382,1.000688,203.000000,150.000000,349.000000,0.570847,202.000000,150.000000,351.000000,0.571429,105.000000,77.000000,183.000000,0.577071,104.000000,77.000000,182.000000,0.576923,6.000000,10.000000,4.000000,0.600000,5.000000,10.000000,4.000000,0.500000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,5.000000,10.000000,4.000000,0.600000,5.000000,10.000000,4.000000,0.600000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,35.000000,63.000000,27.000000,0.571429,35.000000,63.000000,27.000000,0.569444,0.056587,0.039817,0.612091,0.690401,0.498647,0.614858,0.056716,0.039952,0.612268,0.690358,0.498724,0.614839,171.000000,175.000000,0.623140,0.623167,0.000000,0.000000,0.614781,0.614682,86.000000,86.000000,0.387058,0.413161,171.000000,0.387276,0.413043,175.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.000000,2.000000,2.000000,0.600000,0.500000,0.571429,0.571429,0.000000,0.000000,0.000000,0.000000,241.000000,241.000000,-1.000000,0.996262,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.100000,0.000000,0.000000,0.000000,0.000000,1.000000,0.010084,0.009743,-123.008513,-124.329584,-0.001002,-0.001019,2.000000,2.000000,80.000000,81.000000,41.000000,42.000000,37.000000,38.000000,0.516129,0.516667,0.000000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,1.000000,36.000000,36.000000,191.000000,191.000000,28.800000,28.900000,498.000000,503.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,8.000000,10.000000,0.500000,2.000000,9.000000,10.000000,0.500000,237.000000,182.000000,423.000000,0.594839,239.000000,184.000000,426.000000,0.595238,1862.845827,1862.778908,77.044714,1689.638357,1689.153749,66.992506,1736.729412,1736.199728,65.132329,1.044238,12.086699,11.868863,14.000180,13.930757,1.039375,1.041880,332.000000,238.000000,574.000000,0.605909,334.000000,239.000000,576.000000,0.605734,198.000000,133.000000,331.000000,0.618557,198.000000,134.000000,332.000000,0.618384,7.000000,10.000000,6.000000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,7.000000,10.000000,6.000000,0.700000,7.000000,10.000000,6.000000,0.700000,16.000000,25.000000,13.000000,0.640000,16.000000,25.000000,13.000000,0.640000,44.000000,73.000000,30.000000,0.628205,44.000000,73.000000,31.000000,0.628205,0.073757,0.047282,0.636513,0.714168,0.512071,0.633025,0.073868,0.047361,0.636664,0.713931,0.511823,0.632733,358.000000,364.000000,0.623140,0.623167,59.000000,59.000000,0.636933,0.636758,195.000000,196.000000,0.402303,0.430996,358.000000,0.402192,0.430959,364.000000,3.000000,3.000000,8.000000,8.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.833333,0.833333,0.714286,0.714286,0.000000,0.000000,0.000000,0.000000,401.000000,402.000000,102.000000,1.710383,130.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.100000,6.000000,1.000000,1.000000,26.000000,1.000000,0.027580,0.026794,-70.383990,-70.930125,0.003923,0.004160,4.000000,4.000000,179.000000,181.000000,98.000000,98.000000,81.000000,82.000000,0.575000,0.575758,150.000000,149.000000,98.500000,98.333333
max,128.000000,5.000000,1.000000,36.000000,36.000000,208.000000,211.000000,45.700000,48.400000,11245.000000,11795.000000,22.000000,19.000000,28.000000,16.000000,11.000000,16.000000,16.000000,10.000000,5.000000,5.000000,5.000000,5.000000,397.000000,174.000000,543.000000,1.000000,397.000000,174.000000,543.000000,1.000000,1033.000000,559.000000,1265.000000,1.000000,1034.000000,559.000000,1267.000000,1.000000,2360.156303,2358.966694,574.313525,2042.614277,2034.938578,436.103758,2125.284594,2117.708455,433.670633,1.430642,237.194527,237.874458,104.708963,101.635851,1.336522,1.310027,1178.000000,626.000000,1420.000000,1.000000,1182.000000,626.000000,1422.000000,0.835007,721.000000,364.000000,924.000000,1.000000,720.000000,374.000000,927.000000,1.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,1.000000,24.000000,25.000000,24.000000,1.000000,24.000000,25.000000,24.000000,0.960000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,1.000000,25.000000,25.000000,24.000000,1.000000,25.000000,25.000000,24.000000,1.000000,92.000000,121.000000,51.000000,1.000000,91.000000,120.000000,50.000000,1.000000,0.217949,0.210526,0.901961,0.964286,0.900000,0.837209,0.243590,0.195652,0.860000,1.000000,0.923077,0.923077,1272.000000,1277.000000,0.941176,0.969697,2051.000000,2307.000000,1.000000,0.923077,799.000000,798.000000,0.576923,1.000000,1272.000000,0.583333,1.000000,1277.000000,12.000000,13.000000,21.000000,21.000000,12.000000,13.000000,20.000000,19.000000,3.000000,3.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2268.000000,2268.000000,2265.000000,756.000000,10360.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,26.400000,191.000000,1.000000,1.000000,35.000000,1.000000,0.812500,0.666667,125.030130,125.224326,0.294148,0.255364,110.000000,116.000000,653.000000,654.000000,415.000000,416.000000,371.000000,372.000000,1.000000,1.000000,1359.000000,1632.000000,1274.000000,816.000000

## *Handling Categorical Attributes*

In [57]:
#check-1
categorical_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
print(categorical_cols)

['surface', 'tourney_level', 'round', 'playerA_entry', 'playerB_entry', 'playerA_hand', 'playerB_hand']

In [58]:
#check-2
X_train[categorical_cols].describe()

,surface,tourney_level,round,playerA_entry,playerB_entry,playerA_hand,playerB_hand
count,181596,181596,181596,181596,181596,181596,181596
unique,4,6,13,9,9,4,4
top,Hard,C,R32,NONE,NONE,R,R
freq,91731,73902,62083,148071,148033,152512,152759

In [59]:
#check-3
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181596 entries, 0 to 181595
Columns: 205 entries, surface to playerB_avg_minutes_tourney
dtypes: float64(88), int64(110), object(7)
memory usage: 284.0+ MB

In [60]:
cat_df_train = X_train[categorical_cols]

cat_df_test = X_test[categorical_cols]
cat_df_val = X_val[categorical_cols]

In [61]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder(handle_unknown= 'ignore', sparse_output= False)
cat_encoder.fit(cat_df_train)



cat_df_train_new = cat_encoder.transform(cat_df_train)
cat_df_test_new = cat_encoder.transform(cat_df_test)
cat_df_val_new = cat_encoder.transform(cat_df_val)

cat_df_train_new.shape

(181596, 49)

In [62]:
cat_df_train_new = pd.DataFrame(cat_df_train_new, columns= cat_encoder.get_feature_names_out(), index = cat_df_train.index)
cat_df_train_new.head()


cat_df_test_new = pd.DataFrame(cat_df_test_new, columns= cat_encoder.get_feature_names_out(), index = cat_df_test.index)
cat_df_val_new = pd.DataFrame(cat_df_val_new, columns= cat_encoder.get_feature_names_out(), index = cat_df_val.index)

In [63]:
X_train_num = X_train.drop(columns= categorical_cols)

X_test_num = X_test.drop(columns= categorical_cols)
X_val_num = X_val.drop(columns= categorical_cols)

In [64]:
X_train = pd.concat([X_train_num, cat_df_train_new], axis = 1)

X_test = pd.concat([X_test_num, cat_df_test_new], axis = 1)
X_val = pd.concat([X_val_num, cat_df_val_new], axis = 1)

In [65]:
#test-1
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181596 entries, 0 to 181595
Columns: 247 entries, draw_size to playerB_hand_U
dtypes: float64(137), int64(110)
memory usage: 342.2 MB

## *Feature Scaling*

For tree models like RandomForest, XGBoost Etc. standardization can be completely avoided.

In [66]:
pd.set_option("display.max_columns", None)
X_train.describe()

,draw_size,best_of,playerA_wins,playerA_seed,playerB_seed,playerA_ht,playerB_ht,playerA_age,playerB_age,playerA_rank_points,playerB_rank_points,playerA_h2h_wins,playerB_h2h_wins,h2h_total,h2h_diff,playerA_surface_h2h_wins,playerB_surface_h2h_wins,surface_h2h_total,surface_h2h_diff,playerA_last5_h2h_wins,playerB_last5_h2h_wins,last5_h2h_total,last5_h2h_diff,playerA_top20_wins,playerA_top20_losses,playerA_top20_total,playerA_top20_win_pct,playerB_top20_wins,playerB_top20_losses,playerB_top20_total,playerB_top20_win_pct,playerA_hand_wins,playerA_hand_losses,playerA_hand_total,playerA_hand_win_pct,playerB_hand_wins,playerB_hand_losses,playerB_hand_total,playerB_hand_win_pct,playerA_elo,playerB_elo,elo_diff,playerA_surface_elo,playerB_surface_elo,surface_elo_diff,playerA_blended_elo,playerB_blended_elo,blended_elo_diff,elo_ratio,playerA_elo_momentum,playerB_elo_momentum,playerA_elo_volatility,playerB_elo_volatility,blended_elo_ratio,surface_elo_ratio,playerA_career_wins,playerA_career_losses,playerA_career_matches,playerA_career_pct,playerB_career_wins,playerB_career_losses,playerB_career_matches,playerB_career_pct,playerA_surface_career_wins,playerA_surface_career_losses,playerA_surface_career_matches,playerA_surface_career_pct,playerB_surface_career_wins,playerB_surface_career_losses,playerB_surface_career_matches,playerB_surface_career_pct,playerA_last10_wins,playerA_last10_matches,playerA_last10_losses,playerA_last10_pct,playerB_last10_wins,playerB_last10_matches,playerB_last10_losses,playerB_last10_pct,playerA_last25_wins,playerA_last25_matches,playerA_last25_losses,playerA_last25_pct,playerB_last25_wins,playerB_last25_matches,playerB_last25_losses,playerB_last25_pct,playerA_surface10_wins,playerA_surface10_matches,playerA_surface10_losses,playerA_surface10_pct,playerB_surface10_wins,playerB_surface10_matches,playerB_surface10_losses,playerB_surface10_pct,playerA_surface25_wins,playerA_surface25_matches,playerA_surface25_losses,playerA_surface25_pct,playerB_surface25_wins,playerB_surface25_matches,playerB_surface25_losses,playerB_surface25_pct,playerA_52w_wins,playerA_52w_matches,playerA_52w_losses,playerA_52w_pct,playerB_52w_wins,playerB_52w_matches,playerB_52w_losses,playerB_52w_pct,playerA_ace_pct,playerA_df_pct,playerA_1stIn_pct,playerA_1stWon_pct,playerA_2ndWon_pct,playerA_career_p,playerB_ace_pct,playerB_df_pct,playerB_1stIn_pct,playerB_1stWon_pct,playerB_2ndWon_pct,playerB_career_p,playerA_serve_matches,playerB_serve_matches,playerA_matchup_p,playerB_matchup_p,playerA_matchup_service_points,playerB_matchup_service_points,playerA_surface_p,playerB_surface_p,playerA_surface_serve_matches,playerB_surface_serve_matches,playerA_return_pct,playerA_bp_convert_pct,playerA_return_matches,playerB_return_pct,playerB_bp_convert_pct,playerB_return_matches,playerA_matches_7d,playerB_matches_7d,playerA_matches_30d,playerB_matches_30d,playerA_wins_7d,playerB_wins_7d,playerA_wins_30d,playerB_wins_30d,playerA_losses_7d,playerB_losses_7d,playerA_losses_30d,playerB_losses_30d,playerA_winpct_7d,playerB_winpct_7d,playerA_winpct_30d,playerB_winpct_30d,playerA_is_unranked,playerB_is_unranked,playerA_rank_points_missing,playerB_rank_points_missing,playerA_rank_filled,playerB_rank_filled,rank_diff,rank_ratio,rank_points_diff,playerA_top10,playerB_top10,playerA_top32,playerB_top32,playerA_top64,playerB_top64,playerA_top100,playerB_top100,age_diff,height_diff,playerA_seeded,playerB_seeded,seed_diff,seed_diff_missing,playerA_win_rate_specialization,playerB_win_rate_specialization,playerA_elo_specialization,playerB_elo_specialization,playerA_serve_specialization,playerB_serve_specialization,playerA_tourney_matches,playerB_tourney_matches,playerA_level_matches,playerB_level_matches,playerA_level_wins,playerB_level_wins,playerA_level_losses,playerB_level_losses,playerA_level_win_pct,playerB_level_win_pct,playerA_minutes_tourney,playerB_minutes_tourney,playerA_avg_minutes_tourney,playerB_avg_minutes_tourney,surface_Carpet,surface_Clay,surface_Grass,surface_Hard,tourney_level_A,tourney_level_C,tourney_level_D,tourney_level_F,tourney_level_G,tourney_level_M,round_BR,round_ER,round_F,round_Q1,round_Q2,round_Q3,round_QF,round_R128,round_R16,round_R32,round_R64,round_RR,round_SF,playerA_entry_ALT,playerA_entry_ITF,playerA_entry_LL,playerA_entry_NONE,playerA_entry_OTHER,playerA_entry_PR,playerA_entry_Q,playerA_entry_SE,playerA_entry_WC,playerB_entry_ALT,playerB_entry_ITF,playerB_entry_LL,playerB_entry_NONE,playerB_entry_OTHER,playerB_entry_PR,playerB_entry_Q,playerB_entry_SE,playerB_entry_WC,playerA_hand_A,playerA_hand_L,playerA_hand_R,playerA_hand_U,playerB_hand_A,playerB_hand_L,playerB_hand_R,playerB_hand_U
count,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.00000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.00000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.00000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000,181596.000000
mean,48.973700,3.179552,0.499807,25.624507,25.688782,185.184211,185.171920,25.750558,25.738016,718.074010,716.998309,0.550756,0.546956,1.097711,0.003800,0.307000,0.303514,0.610515,0.003486,0.484361,0.481464,0.965825,0.002897,10.998458,19.067865,30.066323,0.310740,10.952262,18.926832,29.879094,0.310564,161.135174,118.823355,279.958529,0.561207,160.425158,118.231563,278.656722,0.561102,1821.155198,1820.819361,0.335838,1657.958637,1658.046488,-0.087851,1706.917605,1706.878350,0.039256,1.003739,1.401060,1.402411,12.226518,12.225717,1.002556,1.002569,231.733662,162.881358,394.615019,0.573653,231.086467,162.404745,393.491211,0.573186,120.886705,81.444999,202.331703,0.570031,120.780794,81.340487,202.121280,0.569831,5.475947,9.915196,4.43925,0.550589,5.474102,9.910852,4.436750,0.550373,13.872426,24.602128,10.729702,0.560638,13.859298,24.588950,10.729653,0.560037,5.427025,9.714526,4.287501,0.554634,5.424145,9.712758,4.288613,0.554176,13.480176,23.554357,10.074181,0.564455,13.459663,23.540056,10.080393,0.563588,33.194404,56.122866,22.928462,0.568881,33.144998,56.056477,22.911479,0.568479,0.063251,0.040983,0.602913,0.695851,0.496890,0.616077,0.063190,0.040959,0.602816,0.695652,0.496806,0.615904,200.230682,199.446866,0.623140,0.623167,65.749400,65.708799,0.617079,0.616922,100.053630,99.927245,0.383163,0.408472,200.230682,0.383121,0.408676,199.446866,1.997148,1.991426,5.454592,5.451552,1.492037,1.487615,3.470445,3.468375,0.505110,0.503811,1.984146,1.983177,0.632757,0.632650,0.562019,0.561456,0.014549,0.015138,0.019841,0.020380,227.143852,228.131754,-0.987902,2.602230,1.037385,0.056158,0.055188,0.157525,0.155141,0.287512,0.287165,0.419051,0.418809,0.012542,0.012291,0.350597,0.348097,-0.064275,0.915890,-0.003622,-0.003355,-163.196562,-162.772873,-0.001002,-0.001019,4.779417,4.797138,106.598119,106.201921,59.156132,58.940291,47.441987,47.261630,0.506544,0.505917,86.781911,86.748442,48.160770,48.133672,0.036554,0.391038,0.06727,0.505138,0.370983,0.406958,0.005804,0.002737,0.106599,0.106919,0.000011,0.000176,0.022192,0.095261,0.054682,0.017198,0.087265,0.052187,0.174371,0.341874,0.099336,0.011327,0.044120,0.007897,0.002153,0.011058,0.815387,0.000319,0.003535,0.083917,0.001916,0.073818,0.007957,0.001845,0.011030,0.815178,0.000303,0.003640,0.084319,0.001619,0.07411,0.000105,0.140934,0.839842,0.019119,0.000116,0.139458,0.841202,0.019224
std,31.710339,0.571723,0.500001,14.489474,14.472293,6.631787,6.757761,4.007567,4.006646,1142.036751,1151.895827,1.235530,1.225779,2.080309,1.315466,0.813163,0.803782,1.329420,0.920457,0.901316,0.897238,1.408763,1.118124,27.624643,28.370684,52.203740,0.201720,27.653137,28.237342,52.105813,0.202705,130.985007,90.840187,215.845014,0.100933,131.048141,90.576198,215.540214,0.101731,158.441105,158.753268,151.586564,105.247398,105.797302,119.657995,113.421687,113.962779,120.638266,0.084702,27.721829,27.735950,10.613989,10.662258,0.071211,0.072461,150.471170,100.632030,243.595068,0.084179,150.247229,100.394605,243.124674,0.085676,103.314600,64.743240,164.602444,0.113186,102.935247,64.582986,164.090923,0.113943,1.820291,0.801730,1.77480,0.178708,1.825628,0.820400,1.775836,0.179355,3.627171,2.690920,3.355766,0.136117,3.647841,2.742511,3.363917,0.137156,1.928540,1.427229,1.805720,0.182706,1.935045,1.436745,1.810108,0.183381,4.350871,4.895754,3.626613,0.145664,4.361525,4.915839,3.631417,0.146283,14.857565,19.286168,7.351586,0.117201,14.861109,19.300817,7.370441,0.117836,0.031974,0.013223,0.042441,0.044993,0.031423,0.033175,0.032014,0.013328,0.042563,0.045274,0.031576,0.033439,193.411113,193.024297,0.046607,0.046475,156.572207,156.759805,0.037655,0.037710,109.770645,109.485284,0.032234,0.051903,193.411113,0.032321,0.052723,193.024297,1.861717,1.862766,3.447615,3.446434,1.660269,1.661913,2.930058,2.931532,0.527481,0.528858,1.140446,1.138039,0.301543,0.301039,0.249082,0.249945,0.119738,0.122102,0.139453,0.141298,342.031098,344.711291,388.696615,12.514071,1336.089941,0.230226,0.228348,0.364297,0.362040,0.452603,0.452440,0.493405,0.493365,5.485216,9.286042,0.477158,0.476368,22.047887,0.277553,0.080329,0.080487,107.360238,107.091716,0.020990,0.021094,7.386417,7.436478,107.093979,106.726983,64.747006,64.539314,45.510501,45.347389,0.147283,0.147772,119.724186,120.667928,53.265042,54.374335,0.187664,0.487984,0.25049,0.499975,0.483069,0.491268,0.075963,0.052243,0.308604,0.309011,0.003319,0.013273,0.147308,0.293576,0.227359,0.130007,0.282224,0.222405,0.379429,0.474339,0.299113,0.105826,0.205362,0.088512,0.046352,0.104572,0.387984,0.017869,0.059354,0.277264,0.043734,0.261475,0.088848,0.042911,0.104443,0.388154,0.017401,0.060222,0.277866,0.040204,0.26195,0.010228,0.347954,0.366753,0.136945,0.010753,0.346425,0.365488,0.137312
min,2.000000,3.000000,0.000000,1.000000,1.000000,3.000000,3.000000,14.400000,14.300000,0.000000,0.000000,0.000000,0.000000,0.000000,-23.000000,0.000000,0.000000,0.000000,-20.000000,0.000000,0.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1147.030234,1145.156568,-820.971471,1167.746944,1182.350079,-686.655177,1166.145429,1182.350079,-646.767833,0.583761,-444.281549,-437.069233,0.000000,0.000000,0.643244,0.672065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.288889,0.100000,0.000000,0.140351,0.000000,0.000000,0.276596,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.140351,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,-2267.000000,0.000441,-16641.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-27.400000,-195.000000,0.000000,0.000000,-35.000000,0.000000,-0.777778,-0.833333,-814.543124,-811.951894,-0.342079,-0.440452,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32.000000,3.000000,0.000000,7.000000,7.000000,180.000000,180.000000,22.800000,22.800000,179.000000,178.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.156532,0.000000,0.000000,0.000000,0.153846,54.000000,42.000000,96.000000,0.524867,53.000000,41.000000,95.000000,0.524590,1732.672056,1732.518282,-87.607146,1593.463914,1593.505156,-71.650621,1643.952266,1643.889212,-71.003947,0.952885,-10.739979,-10.772064,5.805868,5.801942,0.959165,0.957601,120.000000,86.000000,208.000000,0.545098,119.000000,86.000000,207.000000,0.544910,39.000000,30.000000,71.000000,0.531250,39.000000,30.000000,71.000000,0.531250,4.000000,10.000000,3.00000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,9.000000,0.480000,12.000000,25.000000,9.000000,0.480000,4.000000,10.000000,3.000000,0.400000,4.000000,10.000000,3.000000,0.400000,12.000000,25.000000,8.000000,0.480000,11.000000,25.000000,8.000000,0.480000,24.000000,46.000000,19.000000,0.507937,24.000000,46.000000,19.000000,0.507937,0.040957,0.032505,0.576155,0.669526,0.484150,0.598451,0.040846,0.032476,0.576067,0.669274,0.484155,0.598367,48.000000,47.000000,0.623140,0.623167,0.000000,0.000000,0.596969,0.596852,19.000000,19.000000,0.367236,0.389401,48.000000,0.367248,0.389474,47.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,55.000000,55.000000,-69.000000,0.502070,-236.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.600000,-5.000000,0.000000,0.000000,-21.000000,1.000000,-0.019782,-0.019466,-230.578829,-230.102590,-0.007142,-0.007104,0.000000,0.000000,24.000000,24.000000,11.000000,11.000000,12.000000,12.000000,0.444444,0.444444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,32.000000,3.000000,0.000000,36.000000,36.000000,185.000000,185.000000,25.500000,25.500000,411.000000,411.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5.000000,6.000000,0.327434,1.000000,5.000000,6.000000,0.329377,137.000000,104.000000,242.000000,0.562937,136.000000,103.000000,241.000000,0.562660,1815.445841,1815.275263,0.099714,1657.931016,1657.833761,0.034218,1704.671077,1704.661933,0.012857,1.000056,0.809155,0.734485,9.176183,9.187770,1.000007,1.000020,211.000000,148.000000,362.000000,0.577000,210.000000,148.000000,360.000000,0.576772,96.000000,68.000000,165.000000,0.583106,96.000000,67.000000,165.000000,0.583051,6.000000,10.000000,4.00000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,11.000000,0.560000,14.000000,25.000000,11.000000,0.560000,6.000000,10.000000,4.000000,0.600000,6.000000,10.000000,4.000000,0.600000,14.000000,25.000000,10.000000,0.560000,14.000000,25.000000,10.000000,0.560000,33.000000,59.000000,24.000000,0.574074,33.000000,59.000000,24.000000,0.574074,0.058053,0.039552,0.602855,0.695809,0.499612,0.616290,0.057978,0.039500,0.602816,0.695652,0.499528,0.616228,141.000000,141.000000,0.623140,0.623167,0.000000,0.000000,0.617079,0.616922,60.000000,60.000000,0.383641,0.409677,141.000000,0.383651,0.409729,141.000000,2.000000,2.000000,5.000000,5.000000,1.000000,1.000000,3.000000,3.000000,0.000000,0.000000,2.000000,2.000000,0.666667,0.666667,0.600000,0.600000,0.000000,0.000000,0.000000,0.000000,126.000000,127.000000,-1.000000,0.995726,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.010448,0.010602,-149.336080,-148.803840,-0.001002,-0.001019,2.000000,2.000000,70.000000,70.000000,36.000000,36.000000,33.000000,33.000000,0.511658,0.511628,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000

In [67]:
log_cols = ['playerA_top20_wins', 'playerA_top20_losses', 
                    'playerB_top20_wins', 'playerB_top20_losses', 'playerA_hand_wins', 'playerA_hand_losses', 'playerB_hand_wins', 
                    'playerB_hand_losses', 'playerA_career_wins', 'playerA_career_losses', 'playerB_career_wins',
                    'playerB_career_losses', 'playerA_surface_career_wins', 'playerA_surface_career_losses', 
                    'playerB_surface_career_wins', 'playerB_surface_career_losses', 'playerA_52w_wins', 'playerA_52w_matches', 
                    'playerB_52w_wins', 'playerB_52w_matches', 'playerA_serve_matches', 'playerB_serve_matches', 'playerA_matchup_service_points', 
                    'playerB_matchup_service_points', 'playerA_surface_serve_matches', 'playerB_surface_serve_matches', 'playerA_return_matches', 
                    'playerB_return_matches', 'playerA_tourney_matches', 'playerB_tourney_matches', 'playerA_level_matches', 
                    'playerB_level_matches', 'playerA_minutes_tourney', 'playerB_minutes_tourney', 
                    "playerA_top20_total", "playerB_top20_total", "playerA_hand_total", "playerB_hand_total", "playerA_career_matches", 
                    "playerB_career_matches", "playerA_surface_career_matches", "playerB_surface_career_matches", "playerA_52w_losses", 
                    "playerB_52w_losses", "playerA_level_wins", "playerB_level_wins", "playerA_level_losses", "playerB_level_losses"]

In [68]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

log_trans = FunctionTransformer(func= np.log1p, inverse_func= np.expm1)
X_train_log = X_train.copy()
X_train_log[log_cols] = log_trans.fit_transform(X_train_log[log_cols])
X_train_log.head()

X_test_log = X_test.copy()
X_test_log[log_cols] = log_trans.transform(X_test_log[log_cols])

X_val_log = X_val.copy()
X_val_log[log_cols] = log_trans.transform(X_val_log[log_cols])

# **Reducing File Size**

In [69]:
#check-1
X_train.info(memory_usage= 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181596 entries, 0 to 181595
Columns: 247 entries, draw_size to playerB_hand_U
dtypes: float64(137), int64(110)
memory usage: 342.2 MB

In [70]:
import pandas as pd
import numpy as np

def reduce_mem_usage(df):
    for col in df.columns:
        col_type = df[col].dtype

        if col_type == "bool" or "bool" in col_type.name:
            continue
        if col_type == "object" or col_type == "category" or "datetime" in col_type.name:
            continue

        c_min = df[col].min()
        c_max = df[col].max()

        if str(col_type)[:3] == 'int':
            if c_min >= np.iinfo(np.int8).min and c_max <= np.iinfo(np.int8).max:
                df[col] = df[col].astype(np.int8)
            elif c_min >= np.iinfo(np.int16).min and c_max <= np.iinfo(np.int16).max:
                df[col] = df[col].astype(np.int16)
            elif c_min >= np.iinfo(np.int32).min and c_max <= np.iinfo(np.int32).max:
                df[col] = df[col].astype(np.int32)
            else:
                df[col] = df[col].astype(np.int64)

        else:
            # Downcast binary-like floats (e.g. One-Hot encoded) to int8
            if c_min >= 0 and c_max <= 1 and df[col].isin([0.0, 1.0]).all():
                df[col] = df[col].astype(np.int8)
            elif c_min >= np.finfo(np.float32).min and c_max <= np.finfo(np.float32).max:
                df[col] = df[col].astype(np.float32)
            else:
                df[col] = df[col].astype(np.float64)

    return df

# matches_df = reduce_mem_usage(matches_df)

In [71]:
X_train= reduce_mem_usage(X_train)
X_train.info(memory_usage= 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181596 entries, 0 to 181595
Columns: 247 entries, draw_size to playerB_hand_U
dtypes: float32(88), int16(39), int8(120)
memory usage: 95.3 MB

In [72]:
X_test = reduce_mem_usage(X_test)
X_val = reduce_mem_usage(X_val)
X_train_log = reduce_mem_usage(X_train_log)
X_test_log = reduce_mem_usage(X_test_log)
X_val_log = reduce_mem_usage(X_val_log)

y_train= reduce_mem_usage(y_train)
y_test = reduce_mem_usage(y_test)
y_val = reduce_mem_usage(y_val)

C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)
C:\Users\HP\AppData\Local\Temp\ipykernel_25400\2841014663.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(np.float32)

# **Saving The Files**

In [73]:
train = pd.concat([X_train, y_train], axis = 1)
test = pd.concat([X_test, y_test], axis = 1)
val = pd.concat([X_val, y_val], axis = 1)

train_log = pd.concat([X_train_log, y_train], axis = 1)
test_log = pd.concat([X_test_log, y_test], axis = 1)
val_log = pd.concat([X_val_log, y_val], axis = 1)

In [74]:
from pathlib import Path

v1_DIR = Path("data/v1")

train.to_parquet(v1_DIR / "v1_train.parquet", index = False)
test.to_parquet(v1_DIR / "v1_test.parquet", index= False)
val.to_parquet(v1_DIR / "v1_val.parquet", index= False)

train_log.to_parquet(v1_DIR / "v1_train_log.parquet", index = False)
test_log.to_parquet(v1_DIR / "v1_test_log.parquet", index= False)
val_log.to_parquet(v1_DIR / "v1_val_log.parquet", index = False)